function Nqb(){}
function Hqb(){}
function xxc(){}
function Vxc(){}
function Txc(){}
function Xxc(){}
function cyc(){}
function ayc(){}
function Nxc(b){if(b==Bxc){return true}DW();return b==Exc}
function Oxc(b){if(b==Axc){return true}DW();return b==zxc}
function $xc(b){this.c=(FAc(),AAc).b;this.e=(VAc(),UAc).b;this.b=b}
function Pxc(){Fxc();irc.call(this);this.c=(FAc(),AAc);this.d=(VAc(),UAc);this.f[Zqd]=0;this.f[$qd]=0}
function Kxc(b,c){var d;d=$_(b.L,116);d.c=c.b;!!d.d&&(d.d[Xqd]=c.b,undefined)}
function Lxc(b,c){var d;d=$_(b.L,116);d.e=c.b;!!d.d&&(d.d.style[Yqd]=c.b,undefined)}
function Fxc(){Fxc=Mcd;yxc=new Vxc;Bxc=new Vxc;Axc=new Vxc;zxc=new Vxc;Cxc=new Vxc;Dxc=new Vxc;Exc=new Vxc}
function Pqb(){Kqb=new Nqb;KB((HB(),GB),27);!!$stats&&$stats(BC(lTd,kfd,-1,-1));Kqb.kd();!!$stats&&$stats(BC(lTd,fCd,-1,-1))}
function Hxc(b,c,d){var e;if(d==yxc){if(c==b.b){return}else if(b.b){throw new f$c(mTd)}}mv(c);OPc(b.j,c);d==yxc&&(b.b=c);e=new $xc(d);c.L=e;Kxc(c,b.c);Lxc(c,b.d);Jxc(b);ov(c,b)}
function Ixc(b,c){var d,e,f,g,i,j,k,n;qOc(b.N,afd,c);j=new _8c;k=new cQc(b.j);while(k.b<k.c.d-1){d=aQc(k);i=$_(d.L,116).b;f=$_(j.Pc(i),10);e=!f?1:f.b;g=i==Cxc?nTd+e:i==Dxc?oTd+e:i==Exc?pTd+e:i==zxc?qTd+e:i==Bxc?rTd+e:i==Axc?sTd+e:Dqd;qOc((n=d.N.parentNode,(!n||n.nodeType!=1)&&(n=null),n),c,g);j.Rc(i,F$c(e+1))}}
function Mqb(){var b,c,d,e;while(Iqb){b=Iqb;Iqb=Iqb.c;!Iqb&&(Jqb=null);GDb(b.b.b,(d=new Pxc,d.N[Ped]=aTd,d.f[Zqd]=4,d.c=(FAc(),zAc),Hxc(d,new uvc(bTd),(Fxc(),Cxc)),Hxc(d,new uvc(cTd),Dxc),Hxc(d,new uvc(dTd),zxc),Hxc(d,new uvc(eTd),Exc),Hxc(d,new uvc(fTd),Cxc),Hxc(d,new uvc(gTd),Dxc),c=new uvc(hTd),e=new lJc(c),e.N.style[gjd]=iTd,e.N.style[hjd]=jTd,Hxc(d,e,yxc),Ixc(d,kTd),d))}}
function Jxc(b){var c,d,e,f,g,i,j,k,n,o,p,q,r,s,t,u;c=b.e;while(Aoc(c)>0){c.removeChild(zoc(c,0))}r=1;f=1;for(j=new cQc(b.j);j.b<j.c.d-1;){e=aQc(j);g=$_(e.L,116).b;g==Cxc||g==Dxc?++r:(g==zxc||g==Exc||g==Bxc||g==Axc)&&++f}s=K_(Phb,{19:1},81,r,0);for(i=0;i<r;++i){s[i]=new cyc;s[i].c=$doc.createElement(Vqd);c.appendChild(s[i].c)}n=0;o=f-1;p=0;t=r-1;d=null;for(j=new cQc(b.j);j.b<j.c.d-1;){e=aQc(j);k=$_(e.L,116);u=$doc.createElement(Wqd);k.d=u;k.d[Xqd]=k.c;k.d.style[Yqd]=k.e;k.d[gjd]=afd;k.d[hjd]=afd;if(k.b==Cxc){Doc(s[p].c,u,s[p].b);u.appendChild(e.N);u[KId]=o-n+1;++p}else if(k.b==Dxc){Doc(s[t].c,u,s[t].b);u.appendChild(e.N);u[KId]=o-n+1;--t}else if(k.b==yxc){d=u}else if(Nxc(k.b)){q=s[p];Doc(q.c,u,q.b++);u.appendChild(e.N);u[tTd]=t-p+1;++n}else if(Oxc(k.b)){q=s[p];Doc(q.c,u,q.b);u.appendChild(e.N);u[tTd]=t-p+1;--o}}if(b.b){q=s[p];Doc(q.c,d,q.b);d.appendChild(b.b.N)}}
var jTd='100px',uTd='AsyncLoader27',xTd='DockPanel',yTd='DockPanel$DockLayoutConstant',zTd='DockPanel$LayoutData',vTd='DockPanel$TmpRow',wTd='DockPanel$TmpRow;',mTd='Only one CENTER widget may be added',hTd="This is a <code>ScrollPanel<\/code> contained at the center of a <code>DockPanel<\/code>.  By putting some fairly large contents in the middle and setting its size explicitly, it becomes a scrollable area within the page, but without requiring the use of an IFRAME.<br><br>Here's quite a bit more meaningless text that will serve primarily to make this thing scroll off the bottom of its visible area.  Otherwise, you might have to make it really, really small in order to see the nifty scroll bars!",dTd='This is the east component',bTd='This is the first north component',cTd='This is the first south component',fTd='This is the second north component',gTd='This is the second south component',eTd='This is the west component',aTd='cw-DockPanel',kTd='cwDockPanel',qTd='east',sTd='lineend',rTd='linestart',nTd='north',lTd='runCallbacks27',oTd='south',pTd='west';_=Nqb.prototype=Hqb.prototype=new dr;_.gC=function Oqb(){return r4};_.kd=function Sqb(){Mqb()};_.cM={};_=Pxc.prototype=xxc.prototype=new crc;_.gC=function Qxc(){return Ucb};_.sb=function Rxc(b){Ixc(this,b)};_.Hb=function Sxc(b){var c;c=Jpc(this,b);if(c){b==this.b&&(this.b=null);Jxc(this)}return c};_.cM={14:1,15:1,17:1,18:1,83:1,85:1,128:1};_.b=null;var yxc,zxc,Axc,Bxc,Cxc,Dxc,Exc;_=Vxc.prototype=Txc.prototype=new dr;_.gC=function Wxc(){return Rcb};_.cM={};_=$xc.prototype=Xxc.prototype=new dr;_.gC=function _xc(){return Scb};_.cM={116:1};_.b=null;_.d=null;_=cyc.prototype=ayc.prototype=new dr;_.gC=function dyc(){return Tcb};_.cM={81:1};_.b=0;_.c=null;var r4=FZc(Iud,uTd),Tcb=FZc(qsd,vTd),Phb=EZc(Zzd,wTd,Tcb),Ucb=FZc(qsd,xTd),Rcb=FZc(qsd,yTd),Scb=FZc(qsd,zTd);$entry(Pqb)();