function wxb(){}
function qxb(){}
function V5b(){}
function $5b(){}
function d6b(){}
function a6b(b){this.b=b}
function f6b(b){this.b=b}
function X5b(b){this.b=b}
function l6b(b){IPb(b.c,O5b(b.b))}
function vxb(){var b;while(rxb){b=rxb;rxb=rxb.c;!rxb&&(sxb=null);l6b(b.b)}}
function P5b(b,c){if(c==null){Wv(b.d.N,lYd,false)}else{eIc(b.d.b,c,false);Wv(b.d.rb(),lYd,true)}}
function yxb(){txb=new wxb;JC((GC(),FC),14);!!$stats&&$stats(AD(_Yd,vsd,-1,-1));txb.Cd();!!$stats&&$stats(AD(_Yd,iQd,-1,-1))}
function HRb(b){var c,d;c=Tab(b.b.Zc(aZd),54);if(c==null){d=Eab(Stb,{19:1,54:1},1,[bZd,cZd,dZd,eZd,fZd]);b.b._c(aZd,d);return d}else{return c}}
function Q5b(c){var b,e,f,g;f=dG(c.g.N,NRd);if(Ccd(f,lsd)){eIc(c.d.b,mYd,false)}else{try{g=ebd(f);e=f$(c.b,g);eIc(c.d.b,e,false);P5b(c,null)}catch(b){b=dub(b);if(Xab(b,55)){P5b(c,nYd)}else throw b}}}
function R5b(c){var b,e;switch(c.f.N.selectedIndex){case 0:c.b=(_Z(),!WZ&&(WZ=new r$(ZZ.Ic(),hX((rV(),qV)),false)),_Z(),WZ);rSc(c.e,c.b.v);c.e.N[xRd]=!false;break;case 1:c.b=(_Z(),!VZ&&(VZ=new r$(ZZ.Hc(),hX((rV(),qV)),false)),_Z(),VZ);rSc(c.e,c.b.v);c.e.N[xRd]=!false;break;case 2:c.b=(_Z(),!YZ&&(YZ=new r$(ZZ.Uc(),hX((rV(),qV)),false)),_Z(),YZ);rSc(c.e,c.b.v);c.e.N[xRd]=!false;break;case 3:c.b=(_Z(),!XZ&&(XZ=new r$(ZZ.Tc(),hX((rV(),qV)),false)),_Z(),XZ);rSc(c.e,c.b.v);c.e.N[xRd]=!false;break;case 4:c.e.N[xRd]=!true;e=dG(c.e.N,NRd);try{c.b=(_Z(),new r$(e,hX((rV(),qV)),true))}catch(b){b=dub(b);if(Xab(b,98)){P5b(c,hZd);return}else throw b}}Q5b(c)}
function O5b(b){var c,d,e,f,g,i,j,k,n,o,p;c=new ZLc(4,2);c.p[VEd]=5;b.f=new VPc;b.f.N.style[rwd]=iXd;g=HRb(b.c);for(e=0,f=g.length;e<f;++e){d=g[e];QPc(b.f,d)}cw(b.f,new X5b(b),(KN(),KN(),JN));c.of(0,0);i=(j=c.k.b.j.rows[0].cells[0],WKc(c,j,false),j);i.innerHTML=hYd;eLc(c,0,1,b.f);b.e=new ESc;b.e.N.style[rwd]=iXd;cw(b.e,new a6b(b),(JP(),JP(),IP));eLc(c,1,1,b.e);b.g=new ESc;b.g.N.style[rwd]=iXd;rSc(b.g,gZd);cw(b.g,new f6b(b),IP);c.of(2,0);k=(n=c.k.b.j.rows[2].cells[0],WKc(c,n,false),n);k.innerHTML=jYd;eLc(c,2,1,b.g);b.d=new KHc;b.d.N.style[rwd]=iXd;c.of(3,0);o=(p=c.k.b.j.rows[3].cells[0],WKc(c,p,false),p);o.innerHTML=kYd;eLc(c,3,1,b.d);R5b(b);return c}
var YYd='#,##0%',ZYd='#E0',gZd='31415926535.897932',iZd='AsyncLoader14',jZd='CwNumberFormat$1',kZd='CwNumberFormat$2',lZd='CwNumberFormat$3',aZd='cwNumberFormatPatterns',_Yd='runCallbacks14',$Yd='\xA4#0.00',XYd='\xA4\xA0#,##0.00;\xA4\xA0#,##0.00-',fZd='\u062A\u062E\u0635\u064A\u0635',bZd='\u0639\u0634\u0631\u064A',dZd='\u0639\u0644\u0645\u064A',cZd='\u0639\u0645\u0644\u0629',eZd='\u0646\u0633\u0628\u0629 \u0645\u0624\u0648\u064A\u0629',hZd='\u0646\u0645\u0637 \u063A\u064A\u0631 \u0635\u0627\u0644\u062D';var VZ=null,XZ=null,YZ=null;_=I$.prototype;_.Hc=function L$(){return XYd};_.Tc=function Y$(){return YYd};_.Uc=function Z$(){return ZYd};_=_$.prototype;_.Hc=function c_(){return XYd};_.Tc=function p_(){return YYd};_.Uc=function q_(){return ZYd};_=s_.prototype;_.Hc=function v_(){return XYd};_.Tc=function I_(){return YYd};_.Uc=function J_(){return ZYd};_=L_.prototype;_.Hc=function O_(){return XYd};_.Tc=function __(){return YYd};_.Uc=function a0(){return ZYd};_=c0.prototype;_.Hc=function f0(){return XYd};_.Tc=function s0(){return YYd};_.Uc=function t0(){return ZYd};_=v0.prototype;_.Hc=function y0(){return XYd};_.Tc=function L0(){return YYd};_.Uc=function M0(){return ZYd};_=O0.prototype;_.Hc=function R0(){return XYd};_.Tc=function c1(){return YYd};_.Uc=function d1(){return ZYd};_=f1.prototype;_.Hc=function i1(){return XYd};_.Tc=function v1(){return YYd};_.Uc=function w1(){return ZYd};_=y1.prototype;_.Hc=function B1(){return XYd};_.Tc=function O1(){return YYd};_.Uc=function P1(){return ZYd};_=R1.prototype;_.Hc=function U1(){return XYd};_.Tc=function f2(){return YYd};_.Uc=function g2(){return ZYd};_=i2.prototype;_.Hc=function l2(){return XYd};_.Tc=function y2(){return YYd};_.Uc=function z2(){return ZYd};_=B2.prototype;_.Hc=function E2(){return $Yd};_.Tc=function R2(){return YYd};_.Uc=function S2(){return ZYd};_=U2.prototype;_.Hc=function X2(){return $Yd};_.Tc=function i3(){return YYd};_.Uc=function j3(){return ZYd};_=l3.prototype;_.Hc=function o3(){return XYd};_.Tc=function B3(){return YYd};_.Uc=function C3(){return ZYd};_=E3.prototype;_.Hc=function H3(){return $Yd};_.Tc=function U3(){return YYd};_.Uc=function V3(){return ZYd};_=X3.prototype;_.Hc=function $3(){return $Yd};_.Tc=function l4(){return YYd};_.Uc=function m4(){return ZYd};_=o4.prototype;_.Hc=function r4(){return $Yd};_.Tc=function E4(){return YYd};_.Uc=function F4(){return ZYd};_=wxb.prototype=qxb.prototype=new ds;_.gC=function xxb(){return rfb};_.Cd=function Bxb(){vxb()};_.cM={};_=X5b.prototype=V5b.prototype=new ds;_.gC=function Y5b(){return okb};_.gc=function Z5b(b){R5b(this.b)};_.cM={26:1,47:1};_.b=null;_=a6b.prototype=$5b.prototype=new ds;_.gC=function b6b(){return pkb};_.jc=function c6b(b){R5b(this.b)};_.cM={32:1,47:1};_.b=null;_=f6b.prototype=d6b.prototype=new ds;_.gC=function g6b(){return qkb};_.jc=function h6b(b){Q5b(this.b)};_.cM={32:1,47:1};_.b=null;var rfb=Pad(GId,iZd),okb=Pad(ZKd,jZd),pkb=Pad(ZKd,kZd),qkb=Pad(ZKd,lZd);$entry(yxb)();