function E9(){}
function y9(){}
function pHb(){}
function jHb(){}
function Xec(){}
function afc(){}
function iSc(){}
function D9(){D9=Wpd;C9=new E9}
function Zec(b,c){this.c=b;this.b=c}
function cfc(b,c){this.c=b;this.b=c}
function Oec(b,c){eIc(c.b,u8d+b.uf()+qud+b.vf(),false)}
function rHb(){mHb=new pHb;JC((GC(),FC),38);!!$stats&&$stats(AD(s8d,vsd,-1,-1));mHb.Cd();!!$stats&&$stats(AD(s8d,iQd,-1,-1))}
function I2c(c){try{var d=c.document.selection.createRange();if(d.parentElement()!==c)return 0;return d.text.length}catch(b){return 0}}
function H2c(c){try{var d=c.document.selection.createRange();if(d.parentElement()!==c)return -1;return -d.move(x8d,-65535)}catch(b){return 0}}
function ISc(){var b;zSc();sSc.call(this,(b=$doc.createElement(qEd),b.type=v8d,b),(!kic&&(kic=new mic),!fic&&(fic=new hic)));this.N[Zrd]=w8d}
function Mec(b,c){var d,e,f,i;d=new ANc;d.f[VEd]=4;f=vNc(d);d.c.appendChild(f);mw(b);O0c(d.j,b);f.appendChild(b.N);ow(b,d);if(c){e=new LHc(t8d);cw(b,new Zec(b,e),(JP(),JP(),IP));cw(b,new cfc(b,e),(bO(),bO(),aO));i=vNc(d);d.c.appendChild(i);mw(e);O0c(d.j,e);i.appendChild(e.N);ow(e,d)}return d}
function K2c(c){try{var d=c.document.selection.createRange();if(d.parentElement()!==c)return 0;var e=d.text.length;var f=0;var g=d.duplicate();g.moveEnd(x8d,-1);var i=g.text.length;while(i==e&&g.parentElement()==c&&d.compareEndPoints(z8d,g)<=0){f+=2;g.moveEnd(x8d,-1);i=g.text.length}return e+f}catch(b){return 0}}
function J2c(c){try{var d=c.document.selection.createRange();if(d.parentElement()!==c)return -1;var e=d.duplicate();e.moveToElementText(c);e.setEndPoint(y8d,d);var f=e.text.length;var g=0;var i=e.duplicate();i.moveEnd(x8d,-1);var j=i.text.length;while(j==f&&i.parentElement()==c){g+=2;i.moveEnd(x8d,-1);j=i.text.length}return f+g}catch(b){return 0}}
function oHb(){var b,c,d,e,f,g,i;while(kHb){b=kHb;kHb=kHb.c;!kHb&&(lHb=null);IPb(b.b.b,(i=new O_c,i.f[VEd]=5,f=new ESc,b_c(f.N,lsd,j8d),VU(f.b,(D9(),D9(),C9)),d=new ESc,b_c(d.N,lsd,k8d),d.N[NRd]=l8d,UU(d.b),d.N[xRd]=true,K_c(i,new THc(m8d)),K_c(i,Mec(f,true)),K_c(i,Mec(d,false)),e=new ISc,b_c(e.N,lsd,n8d),c=new ISc,b_c(c.N,lsd,o8d),c.N[NRd]=l8d,UU(c.b),c.N[xRd]=true,K_c(i,new THc(p8d)),K_c(i,Mec(e,true)),K_c(i,Mec(c,false)),g=new TYc,b_c(g.N,lsd,q8d),g.N.rows=5,K_c(i,new THc(r8d)),K_c(i,Mec(g,true)),i))}}
var m8d='<b>\u0645\u0631\u0628\u0639 \u0646\u0635 \u0639\u0627\u062F\u064A:<\/b>',p8d='<br><br><b>\u0645\u0631\u0628\u0639 \u0646\u0635 \u0643\u0644\u0645\u0629 \u0627\u0644\u0633\u0631:<\/b>',r8d='<br><br><b>\u0645\u0646\u0637\u0642\u0629 \u0627\u0644\u0646\u0635:<\/b>',A8d='AnyRtlDirectionEstimator',B8d='AsyncLoader38',C8d='CwBasicText$2',D8d='CwBasicText$3',y8d='EndToStart',E8d='PasswordTextBox',z8d='StartToEnd',x8d='character',n8d='cwBasicText-password',o8d='cwBasicText-password-disabled',q8d='cwBasicText-textarea',j8d='cwBasicText-textbox',k8d='cwBasicText-textbox-disabled',w8d='gwt-PasswordTextBox',v8d='password',s8d='runCallbacks38',l8d='\u0642\u0631\u0627\u0621\u0629 \u0641\u0642\u0637',u8d='\u0645\u062E\u062A\u0627\u0631\u0629: ',t8d='\u0645\u062E\u062A\u0627\u0631\u0629: 0, 0';_=E9.prototype=y9.prototype=new z9;_.Bd=function F9(b){return V9.test((cab(),b))?(HZ(),GZ):(HZ(),FZ)};_.gC=function G9(){return Yeb};_.cM={};var C9;_=pHb.prototype=jHb.prototype=new ds;_.gC=function qHb(){return Ngb};_.Cd=function uHb(){oHb()};_.cM={};_=Zec.prototype=Xec.prototype=new ds;_.gC=function $ec(){return Mlb};_.jc=function _ec(b){Oec(this.c,this.b)};_.cM={32:1,47:1};_.b=null;_.c=null;_=cfc.prototype=afc.prototype=new ds;_.gC=function dfc(){return Nlb};_.hc=function efc(b){Oec(this.c,this.b)};_.cM={27:1,47:1};_.b=null;_.c=null;_=lSc.prototype;_.uf=function uSc(){return H2c(this.N)};_.vf=function vSc(){return I2c(this.N)};_=ISc.prototype=iSc.prototype=new jSc;_.gC=function JSc(){return Gpb};_.cM={14:1,15:1,17:1,18:1,73:1,75:1};_=RYc.prototype;_.uf=function VYc(){return J2c(this.N)};_.vf=function WYc(){return K2c(this.N)};var Yeb=Pad(BId,A8d),Ngb=Pad(GId,B8d),Mlb=Pad(kMd,C8d),Nlb=Pad(kMd,D8d),Gpb=Pad(oGd,E8d);$entry(rHb)();