function ssb(){}
function msb(){}
function J0b(){}
function O0b(){}
function T0b(){}
function L0b(b){this.b=b}
function Q0b(b){this.b=b}
function V0b(b){this.b=b}
function _0b(b){wKb(b.c,C0b(b.b))}
function rsb(){var b;while(nsb){b=nsb;nsb=nsb.c;!nsb&&(osb=null);_0b(b.b)}}
function D0b(b,c){if(c==null){yv(b.d.N,FRd,false)}else{xCc(b.d.b,c,false);yv(b.d.rb(),FRd,true)}}
function usb(){psb=new ssb;mC((jC(),iC),14);!!$stats&&$stats(dD(wSd,rmd,-1,-1));psb.Rd();!!$stats&&$stats(dD(wSd,EJd,-1,-1))}
function vMb(b){var c,d;c=l6(b.b.gd(xSd),54);if(c==null){d=Y5(Oob,{19:1,54:1},1,[ySd,zSd,ASd,BSd,CSd]);b.b.jd(xSd,d);return d}else{return c}}
function E0b(c){var b,e,f,g;f=eG(c.g.N,hLd);if(z6c(f,hmd)){xCc(c.d.b,GRd,false)}else{try{g=b5c(f);e=mZ(c.b,g);xCc(c.d.b,e,false);D0b(c,null)}catch(b){b=_ob(b);if(p6(b,55)){D0b(c,HRd)}else throw b}}}
function F0b(c){var b,e;switch(c.f.N.selectedIndex){case 0:c.b=(gZ(),!bZ&&(bZ=new yZ(eZ.Rc(),kW((YU(),XU)),false)),gZ(),bZ);AMc(c.e,c.b.v);c.e.N[TKd]=!false;break;case 1:c.b=(gZ(),!aZ&&(aZ=new yZ(eZ.Qc(),kW((YU(),XU)),false)),gZ(),aZ);AMc(c.e,c.b.v);c.e.N[TKd]=!false;break;case 2:c.b=(gZ(),!dZ&&(dZ=new yZ(eZ.bd(),kW((YU(),XU)),false)),gZ(),dZ);AMc(c.e,c.b.v);c.e.N[TKd]=!false;break;case 3:c.b=(gZ(),!cZ&&(cZ=new yZ(eZ.ad(),kW((YU(),XU)),false)),gZ(),cZ);AMc(c.e,c.b.v);c.e.N[TKd]=!false;break;case 4:c.e.N[TKd]=!true;e=eG(c.e.N,hLd);try{c.b=(gZ(),new yZ(e,kW((YU(),XU)),true))}catch(b){b=_ob(b);if(p6(b,98)){D0b(c,IRd);return}else throw b}}E0b(c)}
function C0b(b){var c,d,e,f,g,i,j,k,n,o,p;c=new tGc(4,2);c.p[myd]=5;b.f=new bKc;b.f.N.style[uqd]=CQd;g=vMb(b.c);for(e=0,f=g.length;e<f;++e){d=g[e];YJc(b.f,d)}Gv(b.f,new L0b(b),(pN(),pN(),oN));c.Df(0,0);i=(j=c.k.b.j.rows[0].cells[0],nFc(c,j,false),j);i.innerHTML=DSd;xFc(c,0,1,b.f);b.e=new NMc;b.e.N.style[uqd]=CQd;Gv(b.e,new Q0b(b),(oP(),oP(),nP));xFc(c,1,1,b.e);b.g=new NMc;b.g.N.style[uqd]=CQd;AMc(b.g,ESd);Gv(b.g,new V0b(b),nP);c.Df(2,0);k=(n=c.k.b.j.rows[2].cells[0],nFc(c,n,false),n);k.innerHTML=FSd;xFc(c,2,1,b.g);b.d=new bCc;b.d.N.style[uqd]=CQd;c.Df(3,0);o=(p=c.k.b.j.rows[3].cells[0],nFc(c,p,false),p);o.innerHTML=GSd;xFc(c,3,1,b.d);F0b(b);return c}
var tSd='#,##0%',uSd='#E0',ESd='31415926535.897932',GSd='<b>\u683C\u5F0F\u5316\u503C\uFF1A<\/b>',DSd='<b>\u6A21\u677F\uFF1A<\/b>',FSd='<b>\u9700\u8981\u683C\u5F0F\u7684\u503C\uFF1A<\/b>',HSd='AsyncLoader14',ISd='CwNumberFormat$1',JSd='CwNumberFormat$2',KSd='CwNumberFormat$3',xSd='cwNumberFormatPatterns',wSd='runCallbacks14',sSd='\xA4#,##0.00',vSd='\xA4#,##0.00;(\xA4#,##0.00)',ySd='\u5C0F\u6570',BSd='\u767E\u5206\u6570',ASd='\u79D1\u5B66',CSd='\u81EA\u5B9A\u4E49',zSd='\u8D27\u5E01';var aZ=null,cZ=null,dZ=null;_=PZ.prototype;_.Qc=function SZ(){return sSd};_.ad=function d$(){return tSd};_.bd=function e$(){return uSd};_=g$.prototype;_.Qc=function j$(){return sSd};_.ad=function w$(){return tSd};_.bd=function x$(){return uSd};_=z$.prototype;_.Qc=function C$(){return sSd};_.ad=function P$(){return tSd};_.bd=function Q$(){return uSd};_=S$.prototype;_.Qc=function V$(){return vSd};_.ad=function g_(){return tSd};_.bd=function h_(){return uSd};_=j_.prototype;_.Qc=function m_(){return sSd};_.ad=function z_(){return tSd};_.bd=function A_(){return uSd};_=C_.prototype;_.Qc=function F_(){return sSd};_.ad=function S_(){return tSd};_.bd=function T_(){return uSd};_=ssb.prototype=msb.prototype=new Hr;_.gC=function tsb(){return rab};_.Rd=function xsb(){rsb()};_.cM={};_=L0b.prototype=J0b.prototype=new Hr;_.gC=function M0b(){return nfb};_.jc=function N0b(b){F0b(this.b)};_.cM={26:1,47:1};_.b=null;_=Q0b.prototype=O0b.prototype=new Hr;_.gC=function R0b(){return ofb};_.mc=function S0b(b){F0b(this.b)};_.cM={32:1,47:1};_.b=null;_=V0b.prototype=T0b.prototype=new Hr;_.gC=function W0b(){return pfb};_.mc=function X0b(b){E0b(this.b)};_.cM={32:1,47:1};_.b=null;var rab=M4c(aCd,HSd),nfb=M4c(sEd,ISd),ofb=M4c(sEd,JSd),pfb=M4c(sEd,KSd);$entry(usb)();