function Wrb(){}
function Qrb(){}
function FAc(){}
function _Ac(){}
function bBc(){}
function dBc(){}
function kBc(){}
function iBc(){}
function VAc(b){if(b==JAc){return true}AX();return b==MAc}
function WAc(b){if(b==IAc){return true}AX();return b==HAc}
function gBc(b){this.c=(EDc(),zDc).b;this.e=(UDc(),TDc).b;this.b=b}
function XAc(){NAc();puc.call(this);this.c=(EDc(),zDc);this.d=(UDc(),TDc);this.f[Ivd]=0;this.f[Jvd]=0}
function SAc(b,c){var d;d=X0(b.L,117);d.c=c.b;!!d.d&&(d.d[Gvd]=c.b,undefined)}
function TAc(b,c){var d;d=X0(b.L,117);d.e=c.b;!!d.d&&(d.d.style[Hvd]=c.b,undefined)}
function NAc(){NAc=Vgd;GAc=new bBc;JAc=new bBc;IAc=new bBc;HAc=new bBc;KAc=new bBc;LAc=new bBc;MAc=new bBc}
function Yrb(){Trb=new Wrb;UB((RB(),QB),27);!!$stats&&$stats(LC(jYd,ujd,-1,-1));Trb.od();!!$stats&&$stats(LC(jYd,AHd,-1,-1))}
function PAc(b,c,d){var e;if(d==GAc){if(c==b.b){return}else if(b.b){throw new o2c(kYd)}}wv(c);wTc(b.j,c);d==GAc&&(b.b=c);e=new gBc(d);c.L=e;SAc(c,b.c);TAc(c,b.d);RAc(b);yv(c,b)}
function QAc(b,c){var d,e,f,g,i,j,k,n;KRc(b.N,kjd,c);j=new idd;k=new MTc(b.j);while(k.b<k.c.d-1){d=KTc(k);i=X0(d.L,117).b;f=X0(j.Tc(i),10);e=!f?1:f.b;g=i==KAc?lYd+e:i==LAc?mYd+e:i==MAc?nYd+e:i==HAc?oYd+e:i==JAc?pYd+e:i==IAc?qYd+e:uvd;KRc((n=d.N.parentNode,(!n||n.nodeType!=1)&&(n=null),n),c,g);j.Vc(i,O2c(e+1))}}
function Vrb(){var b,c,d,e;while(Rrb){b=Rrb;Rrb=Rrb.c;!Rrb&&(Srb=null);BFb(b.b.b,(d=new XAc,d.N[Yid]=$Xd,d.f[Ivd]=4,d.c=(EDc(),yDc),PAc(d,new Byc(_Xd),(NAc(),KAc)),PAc(d,new Byc(aYd),LAc),PAc(d,new Byc(bYd),HAc),PAc(d,new Byc(cYd),MAc),PAc(d,new Byc(dYd),KAc),PAc(d,new Byc(eYd),LAc),c=new Byc(fYd),e=new AMc(c),e.N.style[mnd]=gYd,e.N.style[nnd]=hYd,PAc(d,e,GAc),QAc(d,iYd),d))}}
function RAc(b){var c,d,e,f,g,i,j,k,n,o,p,q,r,s,t,u;c=b.e;while(c.children.length>0){c.removeChild(c.children[0])}r=1;f=1;for(j=new MTc(b.j);j.b<j.c.d-1;){e=KTc(j);g=X0(e.L,117).b;g==KAc||g==LAc?++r:(g==HAc||g==MAc||g==JAc||g==IAc)&&++f}s=H0(Yib,{19:1},82,r,0);for(i=0;i<r;++i){s[i]=new kBc;s[i].c=nG($doc,Evd);c.appendChild(s[i].c)}n=0;o=f-1;p=0;t=r-1;d=null;for(j=new MTc(b.j);j.b<j.c.d-1;){e=KTc(j);k=X0(e.L,117);u=nG($doc,Fvd);k.d=u;k.d[Gvd]=k.c;k.d.style[Hvd]=k.e;k.d[mnd]=kjd;k.d[nnd]=kjd;if(k.b==KAc){krc(s[p].c,u,s[p].b);u.appendChild(e.N);u[SNd]=o-n+1;++p}else if(k.b==LAc){krc(s[t].c,u,s[t].b);u.appendChild(e.N);u[SNd]=o-n+1;--t}else if(k.b==GAc){d=u}else if(VAc(k.b)){q=s[p];krc(q.c,u,q.b++);u.appendChild(e.N);u[rYd]=t-p+1;++n}else if(WAc(k.b)){q=s[p];krc(q.c,u,q.b);u.appendChild(e.N);u[rYd]=t-p+1;--o}}if(b.b){q=s[p];krc(q.c,d,q.b);d.appendChild(b.b.N)}}
var hYd='100px',sYd='AsyncLoader27',vYd='DockPanel',wYd='DockPanel$DockLayoutConstant',xYd='DockPanel$LayoutData',tYd='DockPanel$TmpRow',uYd='DockPanel$TmpRow;',kYd='Only one CENTER widget may be added',fYd="This is a <code>ScrollPanel<\/code> contained at the center of a <code>DockPanel<\/code>.  By putting some fairly large contents in the middle and setting its size explicitly, it becomes a scrollable area within the page, but without requiring the use of an IFRAME.<br><br>Here's quite a bit more meaningless text that will serve primarily to make this thing scroll off the bottom of its visible area.  Otherwise, you might have to make it really, really small in order to see the nifty scroll bars!",bYd='This is the east component',_Xd='This is the first north component',aYd='This is the first south component',dYd='This is the second north component',eYd='This is the second south component',cYd='This is the west component',$Xd='cw-DockPanel',iYd='cwDockPanel',oYd='east',qYd='lineend',pYd='linestart',lYd='north',jYd='runCallbacks27',mYd='south',nYd='west';_=Wrb.prototype=Qrb.prototype=new nr;_.gC=function Xrb(){return m5};_.od=function _rb(){Vrb()};_.cM={};_=XAc.prototype=FAc.prototype=new juc;_.gC=function YAc(){return Xdb};_.ub=function ZAc(b){QAc(this,b)};_.Jb=function $Ac(b){var c;c=Qsc(this,b);if(c){b==this.b&&(this.b=null);RAc(this)}return c};_.cM={14:1,15:1,17:1,18:1,84:1,86:1,129:1};_.b=null;var GAc,HAc,IAc,JAc,KAc,LAc,MAc;_=bBc.prototype=_Ac.prototype=new nr;_.gC=function cBc(){return Udb};_.cM={};_=gBc.prototype=dBc.prototype=new nr;_.gC=function hBc(){return Vdb};_.cM={117:1};_.b=null;_.d=null;_=kBc.prototype=iBc.prototype=new nr;_.gC=function lBc(){return Wdb};_.cM={82:1};_.b=0;_.c=null;var m5=O1c(Szd,sYd),Wdb=O1c(Axd,tYd),Yib=N1c(sFd,uYd,Wdb),Xdb=O1c(Axd,vYd),Udb=O1c(Axd,wYd),Vdb=O1c(Axd,xYd);$entry(Yrb)();