function Qqb(){}
function Kqb(){}
function Fxc(){}
function _xc(){}
function byc(){}
function dyc(){}
function kyc(){}
function iyc(){}
function Vxc(b){if(b==Jxc){return true}GW();return b==Mxc}
function Wxc(b){if(b==Ixc){return true}GW();return b==Hxc}
function gyc(b){this.c=(EAc(),zAc).b;this.e=(UAc(),TAc).b;this.b=b}
function Xxc(){Nxc();qrc.call(this);this.c=(EAc(),zAc);this.d=(UAc(),TAc);this.f[nrd]=0;this.f[ord]=0}
function Sxc(b,c){var d;d=b0(b.L,116);d.c=c.b;!!d.d&&(d.d[lrd]=c.b,undefined)}
function Txc(b,c){var d;d=b0(b.L,116);d.e=c.b;!!d.d&&(d.d.style[mrd]=c.b,undefined)}
function Nxc(){Nxc=_cd;Gxc=new byc;Jxc=new byc;Ixc=new byc;Hxc=new byc;Kxc=new byc;Lxc=new byc;Mxc=new byc}
function Sqb(){Nqb=new Qqb;KB((HB(),GB),27);!!$stats&&$stats(BC(CTd,zfd,-1,-1));Nqb.kd();!!$stats&&$stats(BC(CTd,wCd,-1,-1))}
function Pxc(b,c,d){var e;if(d==Gxc){if(c==b.b){return}else if(b.b){throw new u$c(DTd)}}mv(c);NPc(b.j,c);d==Gxc&&(b.b=c);e=new gyc(d);c.L=e;Sxc(c,b.c);Txc(c,b.d);Rxc(b);ov(c,b)}
function Qxc(b,c){var d,e,f,g,i,j,k,n;pOc(b.N,pfd,c);j=new o9c;k=new bQc(b.j);while(k.b<k.c.d-1){d=_Pc(k);i=b0(d.L,116).b;f=b0(j.Pc(i),10);e=!f?1:f.b;g=i==Kxc?ETd+e:i==Lxc?FTd+e:i==Mxc?GTd+e:i==Hxc?HTd+e:i==Jxc?ITd+e:i==Ixc?JTd+e:Tqd;pOc((n=d.N.parentNode,(!n||n.nodeType!=1)&&(n=null),n),c,g);j.Rc(i,U$c(e+1))}}
function Pqb(){var b,c,d,e;while(Lqb){b=Lqb;Lqb=Lqb.c;!Lqb&&(Mqb=null);JDb(b.b.b,(d=new Xxc,d.N[cfd]=rTd,d.f[nrd]=4,d.c=(EAc(),yAc),Pxc(d,new Cvc(sTd),(Nxc(),Kxc)),Pxc(d,new Cvc(tTd),Lxc),Pxc(d,new Cvc(uTd),Hxc),Pxc(d,new Cvc(vTd),Mxc),Pxc(d,new Cvc(wTd),Kxc),Pxc(d,new Cvc(xTd),Lxc),c=new Cvc(yTd),e=new kJc(c),e.N.style[ujd]=zTd,e.N.style[vjd]=ATd,Pxc(d,e,Gxc),Qxc(d,BTd),d))}}
function Rxc(b){var c,d,e,f,g,i,j,k,n,o,p,q,r,s,t,u;c=b.e;while(Boc(c)>0){c.removeChild(Aoc(c,0))}r=1;f=1;for(j=new bQc(b.j);j.b<j.c.d-1;){e=_Pc(j);g=b0(e.L,116).b;g==Kxc||g==Lxc?++r:(g==Hxc||g==Mxc||g==Jxc||g==Ixc)&&++f}s=N_(Shb,{19:1},81,r,0);for(i=0;i<r;++i){s[i]=new kyc;s[i].c=$doc.createElement(jrd);c.appendChild(s[i].c)}n=0;o=f-1;p=0;t=r-1;d=null;for(j=new bQc(b.j);j.b<j.c.d-1;){e=_Pc(j);k=b0(e.L,116);u=$doc.createElement(krd);k.d=u;k.d[lrd]=k.c;k.d.style[mrd]=k.e;k.d[ujd]=pfd;k.d[vjd]=pfd;if(k.b==Kxc){Eoc(s[p].c,u,s[p].b);u.appendChild(e.N);u[_Id]=o-n+1;++p}else if(k.b==Lxc){Eoc(s[t].c,u,s[t].b);u.appendChild(e.N);u[_Id]=o-n+1;--t}else if(k.b==Gxc){d=u}else if(Vxc(k.b)){q=s[p];Eoc(q.c,u,q.b++);u.appendChild(e.N);u[KTd]=t-p+1;++n}else if(Wxc(k.b)){q=s[p];Eoc(q.c,u,q.b);u.appendChild(e.N);u[KTd]=t-p+1;--o}}if(b.b){q=s[p];Eoc(q.c,d,q.b);d.appendChild(b.b.N)}}
var ATd='100px',LTd='AsyncLoader27',OTd='DockPanel',PTd='DockPanel$DockLayoutConstant',QTd='DockPanel$LayoutData',MTd='DockPanel$TmpRow',NTd='DockPanel$TmpRow;',DTd='Only one CENTER widget may be added',yTd="This is a <code>ScrollPanel<\/code> contained at the center of a <code>DockPanel<\/code>.  By putting some fairly large contents in the middle and setting its size explicitly, it becomes a scrollable area within the page, but without requiring the use of an IFRAME.<br><br>Here's quite a bit more meaningless text that will serve primarily to make this thing scroll off the bottom of its visible area.  Otherwise, you might have to make it really, really small in order to see the nifty scroll bars!",uTd='This is the east component',sTd='This is the first north component',tTd='This is the first south component',wTd='This is the second north component',xTd='This is the second south component',vTd='This is the west component',rTd='cw-DockPanel',BTd='cwDockPanel',HTd='east',JTd='lineend',ITd='linestart',ETd='north',CTd='runCallbacks27',FTd='south',GTd='west';_=Qqb.prototype=Kqb.prototype=new dr;_.gC=function Rqb(){return u4};_.kd=function Vqb(){Pqb()};_.cM={};_=Xxc.prototype=Fxc.prototype=new krc;_.gC=function Yxc(){return Ycb};_.sb=function Zxc(b){Qxc(this,b)};_.Hb=function $xc(b){var c;c=Rpc(this,b);if(c){b==this.b&&(this.b=null);Rxc(this)}return c};_.cM={14:1,15:1,17:1,18:1,83:1,85:1,128:1};_.b=null;var Gxc,Hxc,Ixc,Jxc,Kxc,Lxc,Mxc;_=byc.prototype=_xc.prototype=new dr;_.gC=function cyc(){return Vcb};_.cM={};_=gyc.prototype=dyc.prototype=new dr;_.gC=function hyc(){return Wcb};_.cM={116:1};_.b=null;_.d=null;_=kyc.prototype=iyc.prototype=new dr;_.gC=function lyc(){return Xcb};_.cM={81:1};_.b=0;_.c=null;var u4=UZc(Yud,LTd),Xcb=UZc(Gsd,MTd),Shb=TZc(oAd,NTd,Xcb),Ycb=UZc(Gsd,OTd),Vcb=UZc(Gsd,PTd),Wcb=UZc(Gsd,QTd);$entry(Sqb)();