function kwb(){}
function ewb(){}
function VEc(){}
function rFc(){}
function pFc(){}
function tFc(){}
function AFc(){}
function yFc(){}
function jFc(b){if(b==ZEc){return true}MY();return b==aFc}
function kFc(b){if(b==YEc){return true}MY();return b==XEc}
function wFc(b){this.c=(UHc(),PHc).b;this.e=(iIc(),hIc).b;this.b=b}
function lFc(){bFc();Fyc.call(this);this.c=(UHc(),PHc);this.d=(iIc(),hIc);this.f[$zd]=0;this.f[_zd]=0}
function gFc(b,c){var d;d=U4(b.L,117);d.c=c.b;!!d.d&&(d.d[Yzd]=c.b,undefined)}
function hFc(b,c){var d;d=U4(b.L,117);d.e=c.b;!!d.d&&(d.d.style[Zzd]=c.b,undefined)}
function bFc(){bFc=jld;WEc=new rFc;ZEc=new rFc;YEc=new rFc;XEc=new rFc;$Ec=new rFc;_Ec=new rFc;aFc=new rFc}
function mwb(){hwb=new kwb;kC((hC(),gC),27);!!$stats&&$stats(bD(K0d,Knd,-1,-1));hwb.Fd();!!$stats&&$stats(bD(K0d,SLd,-1,-1))}
function dFc(b,c,d){var e;if(d==WEc){if(c==b.b){return}else if(b.b){throw new E6c(L0d)}}Ov(c);MXc(b.j,c);d==WEc&&(b.b=c);e=new wFc(d);c.L=e;gFc(c,b.c);hFc(c,b.d);fFc(b);Qv(c,b)}
function eFc(b,c){var d,e,f,g,i,j,k,n;$Vc(b.N,And,c);j=new yhd;k=new aYc(b.j);while(k.b<k.c.d-1){d=$Xc(k);i=U4(d.L,117).b;f=U4(j.bd(i),10);e=!f?1:f.b;g=i==$Ec?M0d+e:i==_Ec?N0d+e:i==aFc?O0d+e:i==XEc?P0d+e:i==ZEc?Q0d+e:i==YEc?R0d+e:Mzd;$Vc((n=d.N.parentNode,(!n||n.nodeType!=1)&&(n=null),n),c,g);j.dd(i,c7c(e+1))}}
function jwb(){var b,c,d,e;while(fwb){b=fwb;fwb=fwb.c;!fwb&&(gwb=null);RJb(b.b.b,(d=new lFc,d.N[mnd]=z0d,d.f[$zd]=4,d.c=(UHc(),OHc),dFc(d,new RCc(A0d),(bFc(),$Ec)),dFc(d,new RCc(B0d),_Ec),dFc(d,new RCc(C0d),XEc),dFc(d,new RCc(D0d),aFc),dFc(d,new RCc(E0d),$Ec),dFc(d,new RCc(F0d),_Ec),c=new RCc(G0d),e=new QQc(c),e.N.style[Erd]=H0d,e.N.style[Frd]=I0d,dFc(d,e,WEc),eFc(d,J0d),d))}}
function fFc(b){var c,d,e,f,g,i,j,k,n,o,p,q,r,s,t,u;c=b.e;while(c.children.length>0){c.removeChild(c.children[0])}r=1;f=1;for(j=new aYc(b.j);j.b<j.c.d-1;){e=$Xc(j);g=U4(e.L,117).b;g==$Ec||g==_Ec?++r:(g==XEc||g==aFc||g==ZEc||g==YEc)&&++f}s=E4(mnb,{19:1},72,r,0);for(i=0;i<r;++i){s[i]=new AFc;s[i].c=FG($doc,Wzd);c.appendChild(s[i].c)}n=0;o=f-1;p=0;t=r-1;d=null;for(j=new aYc(b.j);j.b<j.c.d-1;){e=$Xc(j);k=U4(e.L,117);u=FG($doc,Xzd);k.d=u;k.d[Yzd]=k.c;k.d.style[Zzd]=k.e;k.d[Erd]=And;k.d[Frd]=And;if(k.b==$Ec){Avc(s[p].c,u,s[p].b);u.appendChild(e.N);u[gSd]=o-n+1;++p}else if(k.b==_Ec){Avc(s[t].c,u,s[t].b);u.appendChild(e.N);u[gSd]=o-n+1;--t}else if(k.b==WEc){d=u}else if(jFc(k.b)){q=s[p];Avc(q.c,u,q.b++);u.appendChild(e.N);u[S0d]=t-p+1;++n}else if(kFc(k.b)){q=s[p];Avc(q.c,u,q.b);u.appendChild(e.N);u[S0d]=t-p+1;--o}}if(b.b){q=s[p];Avc(q.c,d,q.b);d.appendChild(b.b.N)}}
var I0d='100px',T0d='AsyncLoader27',C0d='Ceci est le composant est',D0d='Ceci est le composant ouest',A0d='Ceci est le premier composant nord',B0d='Ceci est le premier composant sud',E0d='Ceci est le second composant nord',F0d='Ceci est le second composant sud',W0d='DockPanel',X0d='DockPanel$DockLayoutConstant',Y0d='DockPanel$LayoutData',U0d='DockPanel$TmpRow',V0d='DockPanel$TmpRow;',L0d='Only one CENTER widget may be added',G0d="Voici un <code>panneau de d\xE9filement<\/code> situ\xE9 au centre d'un <code>panneau d'ancrage<\/code>. Si des contenus relativement volumineux sont ins\xE9r\xE9s au milieu de ce panneau \xE0 d\xE9filement et si sa taille est d\xE9finie, il prend la forme d'une zone dot\xE9e d'une fonction de d\xE9filement \xE0 l'int\xE9rieur de la page, sans l'utilisation d'un IFRAME.<br><br>Voici un texte encore plus obscur qui va surtout servir \xE0 faire d\xE9filer cet \xE9l\xE9ment jusqu'en bas de sa zone visible. Sinon, il vous faudra r\xE9duire ce panneau \xE0 une taille minuscule pour pouvoir afficher ces formidables barres de d\xE9filement!",z0d='cw-DockPanel',J0d='cwDockPanel',P0d='east',R0d='lineend',Q0d='linestart',M0d='north',K0d='runCallbacks27',N0d='south',O0d='west';_=kwb.prototype=ewb.prototype=new Fr;_.gC=function lwb(){return C9};_.Fd=function pwb(){jwb()};_.cM={};_=lFc.prototype=VEc.prototype=new zyc;_.gC=function mFc(){return lib};_.ub=function nFc(b){eFc(this,b)};_.Jb=function oFc(b){var c;c=exc(this,b);if(c){b==this.b&&(this.b=null);fFc(this)}return c};_.cM={14:1,15:1,17:1,18:1,74:1,76:1,129:1};_.b=null;var WEc,XEc,YEc,ZEc,$Ec,_Ec,aFc;_=rFc.prototype=pFc.prototype=new Fr;_.gC=function sFc(){return iib};_.cM={};_=wFc.prototype=tFc.prototype=new Fr;_.gC=function xFc(){return jib};_.cM={117:1};_.b=null;_.d=null;_=AFc.prototype=yFc.prototype=new Fr;_.gC=function BFc(){return kib};_.cM={72:1};_.b=0;_.c=null;var C9=c6c(iEd,T0d),kib=c6c(SBd,U0d),mnb=b6c(KJd,V0d,kib),lib=c6c(SBd,W0d),iib=c6c(SBd,X0d),jib=c6c(SBd,Y0d);$entry(mwb)();