function Cqb(){}
function wqb(){}
function T$b(){}
function Y$b(){}
function b_b(){}
function d_b(b){this.b=b}
function V$b(b){this.b=b}
function $$b(b){this.b=b}
function j_b(b){GIb(b.c,M$b(b.b))}
function Bqb(){var b;while(xqb){b=xqb;xqb=xqb.c;!xqb&&(yqb=null);j_b(b.b)}}
function N$b(b,c){if(c==null){tv(b.d.N,SPd,false)}else{KAc(b.d.b,c,false);tv(b.d.rb(),SPd,true)}}
function Eqb(){zqb=new Cqb;hC((eC(),dC),14);!!$stats&&$stats($C(JQd,Ekd,-1,-1));zqb.Fd();!!$stats&&$stats($C(JQd,QHd,-1,-1))}
function FKb(b){var c,d;c=A4(b.b.bd(KQd),54);if(c==null){d=l4(Ymb,{19:1,54:1},1,[LQd,MQd,NQd,OQd,PQd]);b.b.dd(KQd,d);return d}else{return c}}
function O$b(c){var b,e,f,g;f=_F(c.g.N,tJd);if(M4c(f,ukd)){KAc(c.d.b,TPd,false)}else{try{g=o3c(f);e=MY(c.b,g);KAc(c.d.b,e,false);N$b(c,null)}catch(b){b=jnb(b);if(E4(b,55)){N$b(c,UPd)}else throw b}}}
function P$b(c){var b,e;switch(c.f.N.selectedIndex){case 0:c.b=(GY(),!BY&&(BY=new YY(EY.Mc(),MV((TU(),SU)),false)),GY(),BY);NKc(c.e,c.b.v);c.e.N[dJd]=!false;break;case 1:c.b=(GY(),!AY&&(AY=new YY(EY.Lc(),MV((TU(),SU)),false)),GY(),AY);NKc(c.e,c.b.v);c.e.N[dJd]=!false;break;case 2:c.b=(GY(),!DY&&(DY=new YY(EY.Yc(),MV((TU(),SU)),false)),GY(),DY);NKc(c.e,c.b.v);c.e.N[dJd]=!false;break;case 3:c.b=(GY(),!CY&&(CY=new YY(EY.Xc(),MV((TU(),SU)),false)),GY(),CY);NKc(c.e,c.b.v);c.e.N[dJd]=!false;break;case 4:c.e.N[dJd]=!true;e=_F(c.e.N,tJd);try{c.b=(GY(),new YY(e,MV((TU(),SU)),true))}catch(b){b=jnb(b);if(E4(b,98)){N$b(c,VPd);return}else throw b}}O$b(c)}
function M$b(b){var c,d,e,f,g,i,j,k,n,o,p;c=new GEc(4,2);c.p[ywd]=5;b.f=new oIc;b.f.N.style[Hod]=OOd;g=FKb(b.c);for(e=0,f=g.length;e<f;++e){d=g[e];jIc(b.f,d)}Bv(b.f,new V$b(b),(kN(),kN(),jN));c.rf(0,0);i=(j=c.k.b.j.rows[0].cells[0],ADc(c,j,false),j);i.innerHTML=OPd;KDc(c,0,1,b.f);b.e=new $Kc;b.e.N.style[Hod]=OOd;Bv(b.e,new $$b(b),(jP(),jP(),iP));KDc(c,1,1,b.e);b.g=new $Kc;b.g.N.style[Hod]=OOd;NKc(b.g,QQd);Bv(b.g,new d_b(b),iP);c.rf(2,0);k=(n=c.k.b.j.rows[2].cells[0],ADc(c,n,false),n);k.innerHTML=QPd;KDc(c,2,1,b.g);b.d=new oAc;b.d.N.style[Hod]=OOd;c.rf(3,0);o=(p=c.k.b.j.rows[3].cells[0],ADc(c,p,false),p);o.innerHTML=RPd;KDc(c,3,1,b.d);P$b(b);return c}
var EQd='#,##0.00\xA0\xA4',HQd='#,##0.00\xA0\xA4;(#,##0.00\xA0\xA4)',FQd='#,##0\xA0%',GQd='#E0',QQd='31415926535.897932',RQd='AsyncLoader14',SQd='CwNumberFormat$1',TQd='CwNumberFormat$2',UQd='CwNumberFormat$3',LQd='D\xE9cimales',KQd='cwNumberFormatPatterns',MQd='devise',PQd='personnalis\xE9',OQd='pourcentage',JQd='runCallbacks14',NQd='scientifique',IQd='\xA4\xA0#,##0.00;\xA4-#,##0.00';var AY=null,CY=null,DY=null;_=nZ.prototype;_.Lc=function qZ(){return EQd};_.Xc=function DZ(){return FQd};_.Yc=function EZ(){return GQd};_=GZ.prototype;_.Lc=function JZ(){return EQd};_.Xc=function WZ(){return FQd};_.Yc=function XZ(){return GQd};_=ZZ.prototype;_.Lc=function a$(){return HQd};_.Xc=function n$(){return FQd};_.Yc=function o$(){return GQd};_=q$.prototype;_.Lc=function t$(){return IQd};_.Xc=function G$(){return FQd};_.Yc=function H$(){return GQd};_=J$.prototype;_.Lc=function M$(){return EQd};_.Xc=function Z$(){return FQd};_.Yc=function $$(){return GQd};_=a_.prototype;_.Lc=function d_(){return EQd};_.Xc=function q_(){return FQd};_.Yc=function r_(){return GQd};_=Cqb.prototype=wqb.prototype=new Cr;_.gC=function Dqb(){return B8};_.Fd=function Hqb(){Bqb()};_.cM={};_=V$b.prototype=T$b.prototype=new Cr;_.gC=function W$b(){return xdb};_.jc=function X$b(b){P$b(this.b)};_.cM={26:1,47:1};_.b=null;_=$$b.prototype=Y$b.prototype=new Cr;_.gC=function _$b(){return ydb};_.mc=function a_b(b){P$b(this.b)};_.cM={32:1,47:1};_.b=null;_=d_b.prototype=b_b.prototype=new Cr;_.gC=function e_b(){return zdb};_.mc=function f_b(b){O$b(this.b)};_.cM={32:1,47:1};_.b=null;var B8=Z2c(mAd,RQd),xdb=Z2c(ECd,SQd),ydb=Z2c(ECd,TQd),zdb=Z2c(ECd,UQd);$entry(Eqb)();