function Nvb(){}
function Hvb(){}
function ACc(){}
function YCc(){}
function WCc(){}
function $Cc(){}
function fDc(){}
function dDc(){}
function QCc(b){if(b==ECc){return true}sY();return b==HCc}
function RCc(b){if(b==DCc){return true}sY();return b==CCc}
function bDc(b){this.c=(CFc(),xFc).b;this.e=(SFc(),RFc).b;this.b=b}
function SCc(){ICc();lwc.call(this);this.c=(CFc(),xFc);this.d=(SFc(),RFc);this.f[ywd]=0;this.f[zwd]=0}
function NCc(b,c){var d;d=A4(b.L,116);d.c=c.b;!!d.d&&(d.d[wwd]=c.b,undefined)}
function OCc(b,c){var d;d=A4(b.L,116);d.e=c.b;!!d.d&&(d.d.style[xwd]=c.b,undefined)}
function ICc(){ICc=eid;BCc=new YCc;ECc=new YCc;DCc=new YCc;CCc=new YCc;FCc=new YCc;GCc=new YCc;HCc=new YCc}
function Pvb(){Kvb=new Nvb;hC((eC(),dC),27);!!$stats&&$stats($C(_Yd,Ekd,-1,-1));Kvb.Fd();!!$stats&&$stats($C(_Yd,QHd,-1,-1))}
function KCc(b,c,d){var e;if(d==BCc){if(c==b.b){return}else if(b.b){throw new z3c(aZd)}}Lv(c);QUc(b.j,c);d==BCc&&(b.b=c);e=new bDc(d);c.L=e;NCc(c,b.c);OCc(c,b.d);MCc(b);Nv(c,b)}
function LCc(b,c){var d,e,f,g,i,j,k,n;sTc(b.N,ukd,c);j=new ted;k=new eVc(b.j);while(k.b<k.c.d-1){d=cVc(k);i=A4(d.L,116).b;f=A4(j.bd(i),10);e=!f?1:f.b;g=i==FCc?bZd+e:i==GCc?cZd+e:i==HCc?dZd+e:i==CCc?eZd+e:i==ECc?fZd+e:i==DCc?gZd+e:cwd;sTc((n=d.N.parentNode,(!n||n.nodeType!=1)&&(n=null),n),c,g);j.dd(i,Z3c(e+1))}}
function Mvb(){var b,c,d,e;while(Ivb){b=Ivb;Ivb=Ivb.c;!Ivb&&(Jvb=null);GIb(b.b.b,(d=new SCc,d.N[hkd]=QYd,d.f[ywd]=4,d.c=(CFc(),wFc),KCc(d,new xAc(RYd),(ICc(),FCc)),KCc(d,new xAc(SYd),GCc),KCc(d,new xAc(TYd),CCc),KCc(d,new xAc(UYd),HCc),KCc(d,new xAc(VYd),FCc),KCc(d,new xAc(WYd),GCc),c=new xAc(XYd),e=new nOc(c),e.N.style[Hod]=YYd,e.N.style[Iod]=ZYd,KCc(d,e,BCc),LCc(d,$Yd),d))}}
function MCc(b){var c,d,e,f,g,i,j,k,n,o,p,q,r,s,t,u;c=b.e;while(ytc(c)>0){c.removeChild(xtc(c,0))}r=1;f=1;for(j=new eVc(b.j);j.b<j.c.d-1;){e=cVc(j);g=A4(e.L,116).b;g==FCc||g==GCc?++r:(g==CCc||g==HCc||g==ECc||g==DCc)&&++f}s=k4(Pmb,{19:1},71,r,0);for(i=0;i<r;++i){s[i]=new fDc;s[i].c=$doc.createElement(uwd);c.appendChild(s[i].c)}n=0;o=f-1;p=0;t=r-1;d=null;for(j=new eVc(b.j);j.b<j.c.d-1;){e=cVc(j);k=A4(e.L,116);u=$doc.createElement(vwd);k.d=u;k.d[wwd]=k.c;k.d.style[xwd]=k.e;k.d[Hod]=ukd;k.d[Iod]=ukd;if(k.b==FCc){Btc(s[p].c,u,s[p].b);u.appendChild(e.N);u[oOd]=o-n+1;++p}else if(k.b==GCc){Btc(s[t].c,u,s[t].b);u.appendChild(e.N);u[oOd]=o-n+1;--t}else if(k.b==BCc){d=u}else if(QCc(k.b)){q=s[p];Btc(q.c,u,q.b++);u.appendChild(e.N);u[hZd]=t-p+1;++n}else if(RCc(k.b)){q=s[p];Btc(q.c,u,q.b);u.appendChild(e.N);u[hZd]=t-p+1;--o}}if(b.b){q=s[p];Btc(q.c,d,q.b);d.appendChild(b.b.N)}}
var ZYd='100px',iZd='AsyncLoader27',TYd='Ceci est le composant est',UYd='Ceci est le composant ouest',RYd='Ceci est le premier composant nord',SYd='Ceci est le premier composant sud',VYd='Ceci est le second composant nord',WYd='Ceci est le second composant sud',lZd='DockPanel',mZd='DockPanel$DockLayoutConstant',nZd='DockPanel$LayoutData',jZd='DockPanel$TmpRow',kZd='DockPanel$TmpRow;',aZd='Only one CENTER widget may be added',XYd="Voici un <code>panneau de d\xE9filement<\/code> situ\xE9 au centre d'un <code>panneau d'ancrage<\/code>. Si des contenus relativement volumineux sont ins\xE9r\xE9s au milieu de ce panneau \xE0 d\xE9filement et si sa taille est d\xE9finie, il prend la forme d'une zone dot\xE9e d'une fonction de d\xE9filement \xE0 l'int\xE9rieur de la page, sans l'utilisation d'un IFRAME.<br><br>Voici un texte encore plus obscur qui va surtout servir \xE0 faire d\xE9filer cet \xE9l\xE9ment jusqu'en bas de sa zone visible. Sinon, il vous faudra r\xE9duire ce panneau \xE0 une taille minuscule pour pouvoir afficher ces formidables barres de d\xE9filement!",QYd='cw-DockPanel',$Yd='cwDockPanel',eZd='east',gZd='lineend',fZd='linestart',bZd='north',_Yd='runCallbacks27',cZd='south',dZd='west';_=Nvb.prototype=Hvb.prototype=new Cr;_.gC=function Ovb(){return n9};_.Fd=function Svb(){Mvb()};_.cM={};_=SCc.prototype=ACc.prototype=new fwc;_.gC=function TCc(){return Shb};_.sb=function UCc(b){LCc(this,b)};_.Hb=function VCc(b){var c;c=Kuc(this,b);if(c){b==this.b&&(this.b=null);MCc(this)}return c};_.cM={14:1,15:1,17:1,18:1,73:1,75:1,128:1};_.b=null;var BCc,CCc,DCc,ECc,FCc,GCc,HCc;_=YCc.prototype=WCc.prototype=new Cr;_.gC=function ZCc(){return Phb};_.cM={};_=bDc.prototype=$Cc.prototype=new Cr;_.gC=function cDc(){return Qhb};_.cM={116:1};_.b=null;_.d=null;_=fDc.prototype=dDc.prototype=new Cr;_.gC=function gDc(){return Rhb};_.cM={71:1};_.b=0;_.c=null;var n9=Z2c(mAd,iZd),Rhb=Z2c(Rxd,jZd),Pmb=Y2c(IFd,kZd,Rhb),Shb=Z2c(Rxd,lZd),Phb=Z2c(Rxd,mZd),Qhb=Z2c(Rxd,nZd);$entry(Pvb)();