function Vpb(){}
function Ppb(){}
function k$b(){}
function p$b(){}
function u$b(){}
function m$b(b){this.b=b}
function r$b(b){this.b=b}
function w$b(b){this.b=b}
function C$b(b){ZHb(b.c,d$b(b.b))}
function Upb(){var b;while(Qpb){b=Qpb;Qpb=Qpb.c;!Qpb&&(Rpb=null);C$b(b.b)}}
function e$b(b,c){if(c==null){mv(b.d.N,TOd,false)}else{dAc(b.d.b,c,false);mv(b.d.rb(),TOd,true)}}
function Xpb(){Spb=new Vpb;aC((ZB(),YB),14);!!$stats&&$stats(TC(KPd,Pjd,-1,-1));Spb.Bd();!!$stats&&$stats(TC(KPd,OGd,-1,-1))}
function YJb(b){var c,d;c=$3(b.b.Zc(LPd),54);if(c==null){d=L3(pmb,{19:1,54:1},1,[MPd,NPd,OPd,PPd,QPd]);b.b._c(LPd,d);return d}else{return c}}
function f$b(c){var b,e,f,g;f=BF(c.g.N,tId);if(X3c(f,Fjd)){dAc(c.d.b,UOd,false)}else{try{g=z2c(f);e=kY(c.b,g);dAc(c.d.b,e,false);e$b(c,null)}catch(b){b=Cmb(b);if(c4(b,55)){e$b(c,VOd)}else throw b}}}
function g$b(c){var b,e;switch(c.f.N.selectedIndex){case 0:c.b=(eY(),!_X&&(_X=new wY(cY.Ic(),kV((rU(),qU)),false)),eY(),_X);$Jc(c.e,c.b.v);c.e.N[dId]=!false;break;case 1:c.b=(eY(),!$X&&($X=new wY(cY.Hc(),kV((rU(),qU)),false)),eY(),$X);$Jc(c.e,c.b.v);c.e.N[dId]=!false;break;case 2:c.b=(eY(),!bY&&(bY=new wY(cY.Uc(),kV((rU(),qU)),false)),eY(),bY);$Jc(c.e,c.b.v);c.e.N[dId]=!false;break;case 3:c.b=(eY(),!aY&&(aY=new wY(cY.Tc(),kV((rU(),qU)),false)),eY(),aY);$Jc(c.e,c.b.v);c.e.N[dId]=!false;break;case 4:c.e.N[dId]=!true;e=BF(c.e.N,tId);try{c.b=(eY(),new wY(e,kV((rU(),qU)),true))}catch(b){b=Cmb(b);if(c4(b,98)){e$b(c,WOd);return}else throw b}}f$b(c)}
function d$b(b){var c,d,e,f,g,i,j,k,n,o,p;c=new YDc(4,2);c.p[Fvd]=5;b.f=new CHc;b.f.N.style[Mnd]=PNd;g=YJb(b.c);for(e=0,f=g.length;e<f;++e){d=g[e];xHc(b.f,d)}uv(b.f,new m$b(b),(KM(),KM(),JM));c.nf(0,0);i=(j=c.k.b.j.rows[0].cells[0],VCc(c,j,false),j);i.innerHTML=POd;dDc(c,0,1,b.f);b.e=new lKc;b.e.N.style[Mnd]=PNd;uv(b.e,new r$b(b),(JO(),JO(),IO));dDc(c,1,1,b.e);b.g=new lKc;b.g.N.style[Mnd]=PNd;$Jc(b.g,RPd);uv(b.g,new w$b(b),IO);c.nf(2,0);k=(n=c.k.b.j.rows[2].cells[0],VCc(c,n,false),n);k.innerHTML=ROd;dDc(c,2,1,b.g);b.d=new Jzc;b.d.N.style[Mnd]=PNd;c.nf(3,0);o=(p=c.k.b.j.rows[3].cells[0],VCc(c,p,false),p);o.innerHTML=SOd;dDc(c,3,1,b.d);g$b(b);return c}
var FPd='#,##0.00\xA0\xA4',IPd='#,##0.00\xA0\xA4;(#,##0.00\xA0\xA4)',GPd='#,##0\xA0%',HPd='#E0',RPd='31415926535.897932',SPd='AsyncLoader14',TPd='CwNumberFormat$1',UPd='CwNumberFormat$2',VPd='CwNumberFormat$3',MPd='D\xE9cimales',LPd='cwNumberFormatPatterns',NPd='devise',QPd='personnalis\xE9',PPd='pourcentage',KPd='runCallbacks14',OPd='scientifique',JPd='\xA4\xA0#,##0.00;\xA4-#,##0.00';var $X=null,aY=null,bY=null;_=NY.prototype;_.Hc=function QY(){return FPd};_.Tc=function bZ(){return GPd};_.Uc=function cZ(){return HPd};_=eZ.prototype;_.Hc=function hZ(){return FPd};_.Tc=function uZ(){return GPd};_.Uc=function vZ(){return HPd};_=xZ.prototype;_.Hc=function AZ(){return IPd};_.Tc=function NZ(){return GPd};_.Uc=function OZ(){return HPd};_=QZ.prototype;_.Hc=function TZ(){return JPd};_.Tc=function e$(){return GPd};_.Uc=function f$(){return HPd};_=h$.prototype;_.Hc=function k$(){return FPd};_.Tc=function x$(){return GPd};_.Uc=function y$(){return HPd};_=A$.prototype;_.Hc=function D$(){return FPd};_.Tc=function Q$(){return GPd};_.Uc=function R$(){return HPd};_=Vpb.prototype=Ppb.prototype=new vr;_.gC=function Wpb(){return Y7};_.Bd=function $pb(){Upb()};_.cM={};_=m$b.prototype=k$b.prototype=new vr;_.gC=function n$b(){return Ucb};_.fc=function o$b(b){g$b(this.b)};_.cM={26:1,47:1};_.b=null;_=r$b.prototype=p$b.prototype=new vr;_.gC=function s$b(){return Vcb};_.ic=function t$b(b){g$b(this.b)};_.cM={32:1,47:1};_.b=null;_=w$b.prototype=u$b.prototype=new vr;_.gC=function x$b(){return Wcb};_.ic=function y$b(b){f$b(this.b)};_.cM={32:1,47:1};_.b=null;var Y7=i2c(ozd,SPd),Ucb=i2c(GBd,TPd),Vcb=i2c(GBd,UPd),Wcb=i2c(GBd,VPd);$entry(Xpb)();