function evb(){}
function $ub(){}
function VBc(){}
function rCc(){}
function pCc(){}
function tCc(){}
function ACc(){}
function yCc(){}
function jCc(b){if(b==ZBc){return true}SX();return b==aCc}
function kCc(b){if(b==YBc){return true}SX();return b==XBc}
function wCc(b){this.c=(UEc(),PEc).b;this.e=(iFc(),hFc).b;this.b=b}
function lCc(){bCc();Gvc.call(this);this.c=(UEc(),PEc);this.d=(iFc(),hFc);this.f[Fvd]=0;this.f[Gvd]=0}
function gCc(b,c){var d;d=$3(b.L,116);d.c=c.b;!!d.d&&(d.d[Dvd]=c.b,undefined)}
function hCc(b,c){var d;d=$3(b.L,116);d.e=c.b;!!d.d&&(d.d.style[Evd]=c.b,undefined)}
function bCc(){bCc=phd;WBc=new rCc;ZBc=new rCc;YBc=new rCc;XBc=new rCc;$Bc=new rCc;_Bc=new rCc;aCc=new rCc}
function gvb(){bvb=new evb;aC((ZB(),YB),27);!!$stats&&$stats(TC(bYd,Pjd,-1,-1));bvb.Bd();!!$stats&&$stats(TC(bYd,OGd,-1,-1))}
function dCc(b,c,d){var e;if(d==WBc){if(c==b.b){return}else if(b.b){throw new K2c(cYd)}}Ev(c);bUc(b.j,c);d==WBc&&(b.b=c);e=new wCc(d);c.L=e;gCc(c,b.c);hCc(c,b.d);fCc(b);Gv(c,b)}
function eCc(b,c){var d,e,f,g,i,j,k,n;FSc(b.N,Fjd,c);j=new Edd;k=new rUc(b.j);while(k.b<k.c.d-1){d=pUc(k);i=$3(d.L,116).b;f=$3(j.Zc(i),10);e=!f?1:f.b;g=i==$Bc?dYd+e:i==_Bc?eYd+e:i==aCc?fYd+e:i==XBc?gYd+e:i==ZBc?hYd+e:i==YBc?iYd+e:jvd;FSc((n=d.N.parentNode,(!n||n.nodeType!=1)&&(n=null),n),c,g);j._c(i,i3c(e+1))}}
function dvb(){var b,c,d,e;while(_ub){b=_ub;_ub=_ub.c;!_ub&&(avb=null);ZHb(b.b.b,(d=new lCc,d.N[sjd]=SXd,d.f[Fvd]=4,d.c=(UEc(),OEc),dCc(d,new Szc(TXd),(bCc(),$Bc)),dCc(d,new Szc(UXd),_Bc),dCc(d,new Szc(VXd),XBc),dCc(d,new Szc(WXd),aCc),dCc(d,new Szc(XXd),$Bc),dCc(d,new Szc(YXd),_Bc),c=new Szc(ZXd),e=new ANc(c),e.N.style[Mnd]=$Xd,e.N.style[Nnd]=_Xd,dCc(d,e,WBc),eCc(d,aYd),d))}}
function fCc(b){var c,d,e,f,g,i,j,k,n,o,p,q,r,s,t,u;c=b.e;while(Rsc(c)>0){c.removeChild(Qsc(c,0))}r=1;f=1;for(j=new rUc(b.j);j.b<j.c.d-1;){e=pUc(j);g=$3(e.L,116).b;g==$Bc||g==_Bc?++r:(g==XBc||g==aCc||g==ZBc||g==YBc)&&++f}s=K3(gmb,{19:1},71,r,0);for(i=0;i<r;++i){s[i]=new ACc;s[i].c=$doc.createElement(Bvd);c.appendChild(s[i].c)}n=0;o=f-1;p=0;t=r-1;d=null;for(j=new rUc(b.j);j.b<j.c.d-1;){e=pUc(j);k=$3(e.L,116);u=$doc.createElement(Cvd);k.d=u;k.d[Dvd]=k.c;k.d.style[Evd]=k.e;k.d[Mnd]=Fjd;k.d[Nnd]=Fjd;if(k.b==$Bc){Usc(s[p].c,u,s[p].b);u.appendChild(e.N);u[pNd]=o-n+1;++p}else if(k.b==_Bc){Usc(s[t].c,u,s[t].b);u.appendChild(e.N);u[pNd]=o-n+1;--t}else if(k.b==WBc){d=u}else if(jCc(k.b)){q=s[p];Usc(q.c,u,q.b++);u.appendChild(e.N);u[jYd]=t-p+1;++n}else if(kCc(k.b)){q=s[p];Usc(q.c,u,q.b);u.appendChild(e.N);u[jYd]=t-p+1;--o}}if(b.b){q=s[p];Usc(q.c,d,q.b);d.appendChild(b.b.N)}}
var _Xd='100px',kYd='AsyncLoader27',VXd='Ceci est le composant est',WXd='Ceci est le composant ouest',TXd='Ceci est le premier composant nord',UXd='Ceci est le premier composant sud',XXd='Ceci est le second composant nord',YXd='Ceci est le second composant sud',nYd='DockPanel',oYd='DockPanel$DockLayoutConstant',pYd='DockPanel$LayoutData',lYd='DockPanel$TmpRow',mYd='DockPanel$TmpRow;',cYd='Only one CENTER widget may be added',ZXd="Voici un <code>panneau de d\xE9filement<\/code> situ\xE9 au centre d'un <code>panneau d'ancrage<\/code>. Si des contenus relativement volumineux sont ins\xE9r\xE9s au milieu de ce panneau \xE0 d\xE9filement et si sa taille est d\xE9finie, il prend la forme d'une zone dot\xE9e d'une fonction de d\xE9filement \xE0 l'int\xE9rieur de la page, sans l'utilisation d'un IFRAME.<br><br>Voici un texte encore plus obscur qui va surtout servir \xE0 faire d\xE9filer cet \xE9l\xE9ment jusqu'en bas de sa zone visible. Sinon, il vous faudra r\xE9duire ce panneau \xE0 une taille minuscule pour pouvoir afficher ces formidables barres de d\xE9filement!",SXd='cw-DockPanel',aYd='cwDockPanel',gYd='east',iYd='lineend',hYd='linestart',dYd='north',bYd='runCallbacks27',eYd='south',fYd='west';_=evb.prototype=$ub.prototype=new vr;_.gC=function fvb(){return K8};_.Bd=function jvb(){dvb()};_.cM={};_=lCc.prototype=VBc.prototype=new Avc;_.gC=function mCc(){return mhb};_.sb=function nCc(b){eCc(this,b)};_.Hb=function oCc(b){var c;c=fuc(this,b);if(c){b==this.b&&(this.b=null);fCc(this)}return c};_.cM={14:1,15:1,17:1,18:1,73:1,75:1,128:1};_.b=null;var WBc,XBc,YBc,ZBc,$Bc,_Bc,aCc;_=rCc.prototype=pCc.prototype=new vr;_.gC=function sCc(){return jhb};_.cM={};_=wCc.prototype=tCc.prototype=new vr;_.gC=function xCc(){return khb};_.cM={116:1};_.b=null;_.d=null;_=ACc.prototype=yCc.prototype=new vr;_.gC=function BCc(){return lhb};_.cM={71:1};_.b=0;_.c=null;var K8=i2c(ozd,kYd),lhb=i2c(Ywd,lYd),gmb=h2c(GEd,mYd,lhb),mhb=i2c(Ywd,nYd),jhb=i2c(Ywd,oYd),khb=i2c(Ywd,pYd);$entry(gvb)();