function LGb(){}
function FGb(){}
function vNc(){}
function TNc(){}
function RNc(){}
function VNc(){}
function $Nc(){}
function aOc(){}
function LNc(b){if(b==zNc){return true}l$();return b==CNc}
function MNc(b){if(b==yNc){return true}l$();return b==xNc}
function YNc(b){this.c=(DQc(),yQc).b;this.e=(TQc(),SQc).b;this.b=b}
function NNc(){DNc();gHc.call(this);this.c=(DQc(),yQc);this.d=(TQc(),SQc);this.f[YGd]=0;this.f[ZGd]=0}
function INc(b,c){var d;d=Seb(b.L,116);d.c=c.b;!!d.d&&(d.d[WGd]=c.b,undefined)}
function JNc(b,c){var d;d=Seb(b.L,116);d.e=c.b;!!d.d&&(d.d.style[XGd]=c.b,undefined)}
function DNc(){DNc=Ksd;wNc=new TNc;zNc=new TNc;yNc=new TNc;xNc=new TNc;ANc=new TNc;BNc=new TNc;CNc=new TNc}
function NGb(){IGb=new LGb;PC((MC(),LC),27);!!$stats&&$stats(GD(l7d,ivd,-1,-1));IGb.Dd();!!$stats&&$stats(GD(l7d,eSd,-1,-1))}
function FNc(b,c,d){var e;if(d==wNc){if(c==b.b){return}else if(b.b){throw new ded(m7d)}}rw(c);M3c(b.j,c);d==wNc&&(b.b=c);e=new YNc(d);c.L=e;INc(c,b.c);JNc(c,b.d);HNc(b);tw(c,b)}
function GNc(b,c){var d,e,f,g,i,j,k,n;o2c(b.N,$ud,c);j=new Zod;k=new a4c(b.j);while(k.b<k.c.d-1){d=$3c(k);i=Seb(d.L,116).b;f=Seb(j.Rc(i),10);e=!f?1:f.b;g=i==ANc?n7d+e:i==BNc?o7d+e:i==CNc?p7d+e:i==xNc?q7d+e:i==zNc?r7d+e:i==yNc?s7d+e:CGd;o2c((n=d.N.parentNode,(!n||n.nodeType!=1)&&(n=null),n),c,g);j.Tc(i,Ded(e+1))}}
function KGb(){var b,c,d,e;while(GGb){b=GGb;GGb=GGb.c;!GGb&&(HGb=null);ETb(b.b.b,(d=new NNc,d.N[Nud]=a7d,d.f[YGd]=4,d.c=(DQc(),xQc),FNc(d,new sLc(b7d),(DNc(),ANc)),FNc(d,new sLc(c7d),BNc),FNc(d,new sLc(d7d),xNc),FNc(d,new sLc(e7d),CNc),FNc(d,new sLc(f7d),ANc),FNc(d,new sLc(g7d),BNc),c=new sLc(h7d),e=new jZc(c),e.N.style[gzd]=i7d,e.N.style[hzd]=j7d,FNc(d,e,wNc),GNc(d,k7d),d))}}
function HNc(b){var c,d,e,f,g,i,j,k,n,o,p,q,r,s,t,u;c=b.e;while(yEc(c)>0){c.removeChild(xEc(c,0))}r=1;f=1;for(j=new a4c(b.j);j.b<j.c.d-1;){e=$3c(j);g=Seb(e.L,116).b;g==ANc||g==BNc?++r:(g==xNc||g==CNc||g==zNc||g==yNc)&&++f}s=Ceb(Nxb,{19:1},71,r,0);for(i=0;i<r;++i){s[i]=new aOc;s[i].c=$doc.createElement(UGd);c.appendChild(s[i].c)}n=0;o=f-1;p=0;t=r-1;d=null;for(j=new a4c(b.j);j.b<j.c.d-1;){e=$3c(j);k=Seb(e.L,116);u=$doc.createElement(VGd);k.d=u;k.d[WGd]=k.c;k.d.style[XGd]=k.e;k.d[gzd]=$ud;k.d[hzd]=$ud;if(k.b==ANc){BEc(s[p].c,u,s[p].b);u.appendChild(e.N);u[GYd]=o-n+1;++p}else if(k.b==BNc){BEc(s[t].c,u,s[t].b);u.appendChild(e.N);u[GYd]=o-n+1;--t}else if(k.b==wNc){d=u}else if(LNc(k.b)){q=s[p];BEc(q.c,u,q.b++);u.appendChild(e.N);u[t7d]=t-p+1;++n}else if(MNc(k.b)){q=s[p];BEc(q.c,u,q.b);u.appendChild(e.N);u[t7d]=t-p+1;--o}}if(b.b){q=s[p];BEc(q.c,d,q.b);d.appendChild(b.b.N)}}
var j7d='100px',u7d='AsyncLoader27',x7d='DockPanel',y7d='DockPanel$DockLayoutConstant',z7d='DockPanel$LayoutData',v7d='DockPanel$TmpRow',w7d='DockPanel$TmpRow;',m7d='Only one CENTER widget may be added',h7d="This is a <code>ScrollPanel<\/code> contained at the center of a <code>DockPanel<\/code>.  By putting some fairly large contents in the middle and setting its size explicitly, it becomes a scrollable area within the page, but without requiring the use of an IFRAME.<br><br>Here's quite a bit more meaningless text that will serve primarily to make this thing scroll off the bottom of its visible area.  Otherwise, you might have to make it really, really small in order to see the nifty scroll bars!",d7d='This is the east component',b7d='This is the first north component',c7d='This is the first south component',f7d='This is the second north component',g7d='This is the second south component',e7d='This is the west component',a7d='cw-DockPanel',k7d='cwDockPanel',q7d='east',s7d='lineend',r7d='linestart',n7d='north',l7d='runCallbacks27',o7d='south',p7d='west';_=LGb.prototype=FGb.prototype=new is;_.gC=function MGb(){return pkb};_.Dd=function QGb(){KGb()};_.cM={};_=NNc.prototype=vNc.prototype=new aHc;_.gC=function ONc(){return Ssb};_.sb=function PNc(b){GNc(this,b)};_.Hb=function QNc(b){var c;c=HFc(this,b);if(c){b==this.b&&(this.b=null);HNc(this)}return c};_.cM={14:1,15:1,17:1,18:1,73:1,75:1,128:1};_.b=null;var wNc,xNc,yNc,zNc,ANc,BNc,CNc;_=TNc.prototype=RNc.prototype=new is;_.gC=function UNc(){return Psb};_.cM={};_=YNc.prototype=VNc.prototype=new is;_.gC=function ZNc(){return Qsb};_.cM={116:1};_.b=null;_.d=null;_=aOc.prototype=$Nc.prototype=new is;_.gC=function bOc(){return Rsb};_.cM={71:1};_.b=0;_.c=null;var pkb=Ddd(HKd,u7d),Rsb=Ddd(pId,v7d),Nxb=Cdd(YPd,w7d,Rsb),Ssb=Ddd(pId,x7d),Psb=Ddd(pId,y7d),Qsb=Ddd(pId,z7d);$entry(NGb)();