function Irb(){}
function Crb(){}
function Z_b(){}
function c0b(){}
function h0b(){}
function e0b(b){this.b=b}
function j0b(b){this.b=b}
function __b(b){this.b=b}
function p0b(b){MJb(b.c,S_b(b.b))}
function Hrb(){var b;while(Drb){b=Drb;Drb=Drb.c;!Drb&&(Erb=null);p0b(b.b)}}
function T_b(b,c){if(c==null){rv(b.d.N,pQd,false)}else{KBc(b.d.b,c,false);rv(b.d.rb(),pQd,true)}}
function Krb(){Frb=new Irb;fC((cC(),bC),14);!!$stats&&$stats(YC(gRd,nld,-1,-1));Frb.Nd();!!$stats&&$stats(YC(gRd,lId,-1,-1))}
function LLb(b){var c,d;c=I5(b.b.cd(hRd),54);if(c==null){d=t5(cob,{19:1,54:1},1,[iRd,jRd,kRd,lRd,mRd]);b.b.ed(hRd,d);return d}else{return c}}
function U_b(c){var b,e,f,g;f=IF(c.g.N,SJd);if(v5c(f,dld)){KBc(c.d.b,qQd,false)}else{try{g=Z3c(f);e=JY(c.b,g);KBc(c.d.b,e,false);T_b(c,null)}catch(b){b=pob(b);if(M5(b,55)){T_b(c,rQd)}else throw b}}}
function V_b(c){var b,e;switch(c.f.N.selectedIndex){case 0:c.b=(DY(),!yY&&(yY=new VY(BY.Nc(),HV((tU(),sU)),false)),DY(),yY);OLc(c.e,c.b.v);c.e.N[CJd]=!false;break;case 1:c.b=(DY(),!xY&&(xY=new VY(BY.Mc(),HV((tU(),sU)),false)),DY(),xY);OLc(c.e,c.b.v);c.e.N[CJd]=!false;break;case 2:c.b=(DY(),!AY&&(AY=new VY(BY.Zc(),HV((tU(),sU)),false)),DY(),AY);OLc(c.e,c.b.v);c.e.N[CJd]=!false;break;case 3:c.b=(DY(),!zY&&(zY=new VY(BY.Yc(),HV((tU(),sU)),false)),DY(),zY);OLc(c.e,c.b.v);c.e.N[CJd]=!false;break;case 4:c.e.N[CJd]=!true;e=IF(c.e.N,SJd);try{c.b=(DY(),new VY(e,HV((tU(),sU)),true))}catch(b){b=pob(b);if(M5(b,98)){T_b(c,sQd);return}else throw b}}U_b(c)}
function S_b(b){var c,d,e,f,g,i,j,k,n,o,p;c=new MFc(4,2);c.p[dxd]=5;b.f=new qJc;b.f.N.style[lpd]=mPd;g=LLb(b.c);for(e=0,f=g.length;e<f;++e){d=g[e];lJc(b.f,d)}zv(b.f,new __b(b),(MM(),MM(),LM));c.zf(0,0);i=(j=c.k.b.j.rows[0].cells[0],JEc(c,j,false),j);i.innerHTML=nRd;TEc(c,0,1,b.f);b.e=new _Lc;b.e.N.style[lpd]=mPd;zv(b.e,new e0b(b),(LO(),LO(),KO));TEc(c,1,1,b.e);b.g=new _Lc;b.g.N.style[lpd]=mPd;OLc(b.g,oRd);zv(b.g,new j0b(b),KO);c.zf(2,0);k=(n=c.k.b.j.rows[2].cells[0],JEc(c,n,false),n);k.innerHTML=pRd;TEc(c,2,1,b.g);b.d=new oBc;b.d.N.style[lpd]=mPd;c.zf(3,0);o=(p=c.k.b.j.rows[3].cells[0],JEc(c,p,false),p);o.innerHTML=qRd;TEc(c,3,1,b.d);V_b(b);return c}
var dRd='#,##0%',eRd='#E0',oRd='31415926535.897932',qRd='<b>\u683C\u5F0F\u5316\u503C\uFF1A<\/b>',nRd='<b>\u6A21\u677F\uFF1A<\/b>',pRd='<b>\u9700\u8981\u683C\u5F0F\u7684\u503C\uFF1A<\/b>',rRd='AsyncLoader14',sRd='CwNumberFormat$1',tRd='CwNumberFormat$2',uRd='CwNumberFormat$3',hRd='cwNumberFormatPatterns',gRd='runCallbacks14',cRd='\xA4#,##0.00',fRd='\xA4#,##0.00;(\xA4#,##0.00)',iRd='\u5C0F\u6570',lRd='\u767E\u5206\u6570',kRd='\u79D1\u5B66',mRd='\u81EA\u5B9A\u4E49',jRd='\u8D27\u5E01';var xY=null,zY=null,AY=null;_=kZ.prototype;_.Mc=function nZ(){return cRd};_.Yc=function AZ(){return dRd};_.Zc=function BZ(){return eRd};_=DZ.prototype;_.Mc=function GZ(){return cRd};_.Yc=function TZ(){return dRd};_.Zc=function UZ(){return eRd};_=WZ.prototype;_.Mc=function ZZ(){return cRd};_.Yc=function k$(){return dRd};_.Zc=function l$(){return eRd};_=n$.prototype;_.Mc=function q$(){return fRd};_.Yc=function D$(){return dRd};_.Zc=function E$(){return eRd};_=G$.prototype;_.Mc=function J$(){return cRd};_.Yc=function W$(){return dRd};_.Zc=function X$(){return eRd};_=Z$.prototype;_.Mc=function a_(){return cRd};_.Yc=function n_(){return dRd};_.Zc=function o_(){return eRd};_=Irb.prototype=Crb.prototype=new Ar;_.gC=function Jrb(){return L9};_.Nd=function Nrb(){Hrb()};_.cM={};_=__b.prototype=Z_b.prototype=new Ar;_.gC=function a0b(){return Heb};_.fc=function b0b(b){V_b(this.b)};_.cM={26:1,47:1};_.b=null;_=e0b.prototype=c0b.prototype=new Ar;_.gC=function f0b(){return Ieb};_.ic=function g0b(b){V_b(this.b)};_.cM={32:1,47:1};_.b=null;_=j0b.prototype=h0b.prototype=new Ar;_.gC=function k0b(){return Jeb};_.ic=function l0b(b){U_b(this.b)};_.cM={32:1,47:1};_.b=null;var L9=I3c(OAd,rRd),Heb=I3c(eDd,sRd),Ieb=I3c(eDd,tRd),Jeb=I3c(eDd,uRd);$entry(Krb)();