function xrb(){}
function rrb(){}
function kyc(){}
function Iyc(){}
function Gyc(){}
function Kyc(){}
function Ryc(){}
function Pyc(){}
function Ayc(b){if(b==oyc){return true}gX();return b==ryc}
function Byc(b){if(b==nyc){return true}gX();return b==myc}
function Nyc(b){this.c=(mBc(),hBc).b;this.e=(CBc(),BBc).b;this.b=b}
function Cyc(){syc();Xrc.call(this);this.c=(mBc(),hBc);this.d=(CBc(),BBc);this.f[gsd]=0;this.f[hsd]=0}
function xyc(b,c){var d;d=D0(b.L,116);d.c=c.b;!!d.d&&(d.d[esd]=c.b,undefined)}
function yyc(b,c){var d;d=D0(b.L,116);d.e=c.b;!!d.d&&(d.d.style[fsd]=c.b,undefined)}
function syc(){syc=Qdd;lyc=new Iyc;oyc=new Iyc;nyc=new Iyc;myc=new Iyc;pyc=new Iyc;qyc=new Iyc;ryc=new Iyc}
function zrb(){urb=new xrb;RB((OB(),NB),27);!!$stats&&$stats(IC(AUd,ogd,-1,-1));urb.od();!!$stats&&$stats(IC(AUd,yDd,-1,-1))}
function uyc(b,c,d){var e;if(d==lyc){if(c==b.b){return}else if(b.b){throw new j_c(BUd)}}tv(c);AQc(b.j,c);d==lyc&&(b.b=c);e=new Nyc(d);c.L=e;xyc(c,b.c);yyc(c,b.d);wyc(b);vv(c,b)}
function vyc(b,c){var d,e,f,g,i,j,k,n;cPc(b.N,egd,c);j=new dad;k=new QQc(b.j);while(k.b<k.c.d-1){d=OQc(k);i=D0(d.L,116).b;f=D0(j.Tc(i),10);e=!f?1:f.b;g=i==pyc?CUd+e:i==qyc?DUd+e:i==ryc?EUd+e:i==myc?FUd+e:i==oyc?GUd+e:i==nyc?HUd+e:Mrd;cPc((n=d.N.parentNode,(!n||n.nodeType!=1)&&(n=null),n),c,g);j.Vc(i,J_c(e+1))}}
function wrb(){var b,c,d,e;while(srb){b=srb;srb=srb.c;!srb&&(trb=null);qEb(b.b.b,(d=new Cyc,d.N[Tfd]=pUd,d.f[gsd]=4,d.c=(mBc(),gBc),uyc(d,new hwc(qUd),(syc(),pyc)),uyc(d,new hwc(rUd),qyc),uyc(d,new hwc(sUd),myc),uyc(d,new hwc(tUd),ryc),uyc(d,new hwc(uUd),pyc),uyc(d,new hwc(vUd),qyc),c=new hwc(wUd),e=new ZJc(c),e.N.style[pkd]=xUd,e.N.style[qkd]=yUd,uyc(d,e,lyc),vyc(d,zUd),d))}}
function wyc(b){var c,d,e,f,g,i,j,k,n,o,p,q,r,s,t,u;c=b.e;while(ipc(c)>0){c.removeChild(hpc(c,0))}r=1;f=1;for(j=new QQc(b.j);j.b<j.c.d-1;){e=OQc(j);g=D0(e.L,116).b;g==pyc||g==qyc?++r:(g==myc||g==ryc||g==oyc||g==nyc)&&++f}s=n0(zib,{19:1},81,r,0);for(i=0;i<r;++i){s[i]=new Ryc;s[i].c=$doc.createElement(csd);c.appendChild(s[i].c)}n=0;o=f-1;p=0;t=r-1;d=null;for(j=new QQc(b.j);j.b<j.c.d-1;){e=OQc(j);k=D0(e.L,116);u=$doc.createElement(dsd);k.d=u;k.d[esd]=k.c;k.d.style[fsd]=k.e;k.d[pkd]=egd;k.d[qkd]=egd;if(k.b==pyc){lpc(s[p].c,u,s[p].b);u.appendChild(e.N);u[$Jd]=o-n+1;++p}else if(k.b==qyc){lpc(s[t].c,u,s[t].b);u.appendChild(e.N);u[$Jd]=o-n+1;--t}else if(k.b==lyc){d=u}else if(Ayc(k.b)){q=s[p];lpc(q.c,u,q.b++);u.appendChild(e.N);u[IUd]=t-p+1;++n}else if(Byc(k.b)){q=s[p];lpc(q.c,u,q.b);u.appendChild(e.N);u[IUd]=t-p+1;--o}}if(b.b){q=s[p];lpc(q.c,d,q.b);d.appendChild(b.b.N)}}
var yUd='100px',JUd='AsyncLoader27',MUd='DockPanel',NUd='DockPanel$DockLayoutConstant',OUd='DockPanel$LayoutData',KUd='DockPanel$TmpRow',LUd='DockPanel$TmpRow;',BUd='Only one CENTER widget may be added',wUd="This is a <code>ScrollPanel<\/code> contained at the center of a <code>DockPanel<\/code>.  By putting some fairly large contents in the middle and setting its size explicitly, it becomes a scrollable area within the page, but without requiring the use of an IFRAME.<br><br>Here's quite a bit more meaningless text that will serve primarily to make this thing scroll off the bottom of its visible area.  Otherwise, you might have to make it really, really small in order to see the nifty scroll bars!",sUd='This is the east component',qUd='This is the first north component',rUd='This is the first south component',uUd='This is the second north component',vUd='This is the second south component',tUd='This is the west component',pUd='cw-DockPanel',zUd='cwDockPanel',FUd='east',HUd='lineend',GUd='linestart',CUd='north',AUd='runCallbacks27',DUd='south',EUd='west';_=xrb.prototype=rrb.prototype=new kr;_.gC=function yrb(){return Z4};_.od=function Crb(){wrb()};_.cM={};_=Cyc.prototype=kyc.prototype=new Rrc;_.gC=function Dyc(){return Cdb};_.sb=function Eyc(b){vyc(this,b)};_.Hb=function Fyc(b){var c;c=uqc(this,b);if(c){b==this.b&&(this.b=null);wyc(this)}return c};_.cM={14:1,15:1,17:1,18:1,83:1,85:1,128:1};_.b=null;var lyc,myc,nyc,oyc,pyc,qyc,ryc;_=Iyc.prototype=Gyc.prototype=new kr;_.gC=function Jyc(){return zdb};_.cM={};_=Nyc.prototype=Kyc.prototype=new kr;_.gC=function Oyc(){return Adb};_.cM={116:1};_.b=null;_.d=null;_=Ryc.prototype=Pyc.prototype=new kr;_.gC=function Syc(){return Bdb};_.cM={81:1};_.b=0;_.c=null;var Z4=J$c(Wvd,JUd),Bdb=J$c(ztd,KUd),zib=I$c(qBd,LUd,Bdb),Cdb=J$c(ztd,MUd),zdb=J$c(ztd,NUd),Adb=J$c(ztd,OUd);$entry(zrb)();