function Rsb(){}
function Lsb(){}
function a2b(){}
function f2b(){}
function k2b(){}
function c2b(b){this.b=b}
function h2b(b){this.b=b}
function m2b(b){this.b=b}
function s2b(b){HLb(b.c,V1b(b.b))}
function Qsb(){var b;while(Msb){b=Msb;Msb=Msb.c;!Msb&&(Nsb=null);s2b(b.b)}}
function W1b(b,c){if(c==null){Bv(b.d.N,xVd,false)}else{REc(b.d.b,c,false);Bv(b.d.tb(),xVd,true)}}
function Tsb(){Osb=new Rsb;pC((mC(),lC),14);!!$stats&&$stats(gD(oWd,xpd,-1,-1));Osb.Rd();!!$stats&&$stats(gD(oWd,GNd,-1,-1))}
function GNb(b){var c,d;c=F6(b.b.gd(pWd),54);if(c==null){d=q6(lpb,{19:1,54:1},1,[qWd,rWd,sWd,tWd,uWd]);b.b.jd(pWd,d);return d}else{return c}}
function X1b(c){var b,e,f,g;f=MF(c.g.N,jPd);if(E9c(f,npd)){REc(c.d.b,yVd,false)}else{try{g=g8c(f);e=GZ(c.b,g);REc(c.d.b,e,false);W1b(c,null)}catch(b){b=ypb(b);if(J6(b,55)){W1b(c,zVd)}else throw b}}}
function Y1b(c){var b,e;switch(c.f.N.selectedIndex){case 0:c.b=(AZ(),!vZ&&(vZ=new SZ(yZ.Rc(),EW((qV(),pV)),false)),AZ(),vZ);bPc(c.e,c.b.v);c.e.N[VOd]=!false;break;case 1:c.b=(AZ(),!uZ&&(uZ=new SZ(yZ.Qc(),EW((qV(),pV)),false)),AZ(),uZ);bPc(c.e,c.b.v);c.e.N[VOd]=!false;break;case 2:c.b=(AZ(),!xZ&&(xZ=new SZ(yZ.bd(),EW((qV(),pV)),false)),AZ(),xZ);bPc(c.e,c.b.v);c.e.N[VOd]=!false;break;case 3:c.b=(AZ(),!wZ&&(wZ=new SZ(yZ.ad(),EW((qV(),pV)),false)),AZ(),wZ);bPc(c.e,c.b.v);c.e.N[VOd]=!false;break;case 4:c.e.N[VOd]=!true;e=MF(c.e.N,jPd);try{c.b=(AZ(),new SZ(e,EW((qV(),pV)),true))}catch(b){b=ypb(b);if(J6(b,99)){W1b(c,AVd);return}else throw b}}X1b(c)}
function V1b(b){var c,d,e,f,g,i,j,k,n,o,p;c=new LIc(4,2);c.p[OBd]=5;b.f=new EMc;b.f.N.style[rtd]=uUd;g=GNb(b.c);for(e=0,f=g.length;e<f;++e){d=g[e];zMc(b.f,d)}Jv(b.f,new c2b(b),(JN(),JN(),IN));c.Jf(0,0);i=(j=c.k.b.j.rows[0].cells[0],IHc(c,j,false),j);i.innerHTML=vWd;SHc(c,0,1,b.f);b.e=new oPc;b.e.N.style[rtd]=uUd;Jv(b.e,new h2b(b),(IP(),IP(),HP));SHc(c,1,1,b.e);b.g=new oPc;b.g.N.style[rtd]=uUd;bPc(b.g,wWd);Jv(b.g,new m2b(b),HP);c.Jf(2,0);k=(n=c.k.b.j.rows[2].cells[0],IHc(c,n,false),n);k.innerHTML=xWd;SHc(c,2,1,b.g);b.d=new vEc;b.d.N.style[rtd]=uUd;c.Jf(3,0);o=(p=c.k.b.j.rows[3].cells[0],IHc(c,p,false),p);o.innerHTML=yWd;SHc(c,3,1,b.d);Y1b(b);return c}
var lWd='#,##0%',mWd='#E0',wWd='31415926535.897932',yWd='<b>\u683C\u5F0F\u5316\u503C\uFF1A<\/b>',vWd='<b>\u6A21\u677F\uFF1A<\/b>',xWd='<b>\u9700\u8981\u683C\u5F0F\u7684\u503C\uFF1A<\/b>',zWd='AsyncLoader14',AWd='CwNumberFormat$1',BWd='CwNumberFormat$2',CWd='CwNumberFormat$3',pWd='cwNumberFormatPatterns',oWd='runCallbacks14',kWd='\xA4#,##0.00',nWd='\xA4#,##0.00;(\xA4#,##0.00)',qWd='\u5C0F\u6570',tWd='\u767E\u5206\u6570',sWd='\u79D1\u5B66',uWd='\u81EA\u5B9A\u4E49',rWd='\u8D27\u5E01';var uZ=null,wZ=null,xZ=null;_=h$.prototype;_.Qc=function k$(){return kWd};_.ad=function x$(){return lWd};_.bd=function y$(){return mWd};_=A$.prototype;_.Qc=function D$(){return kWd};_.ad=function Q$(){return lWd};_.bd=function R$(){return mWd};_=T$.prototype;_.Qc=function W$(){return kWd};_.ad=function h_(){return lWd};_.bd=function i_(){return mWd};_=k_.prototype;_.Qc=function n_(){return nWd};_.ad=function A_(){return lWd};_.bd=function B_(){return mWd};_=D_.prototype;_.Qc=function G_(){return kWd};_.ad=function T_(){return lWd};_.bd=function U_(){return mWd};_=W_.prototype;_.Qc=function Z_(){return kWd};_.ad=function k0(){return lWd};_.bd=function l0(){return mWd};_=Rsb.prototype=Lsb.prototype=new Kr;_.gC=function Ssb(){return Gab};_.Rd=function Wsb(){Qsb()};_.cM={};_=c2b.prototype=a2b.prototype=new Kr;_.gC=function d2b(){return Gfb};_.jc=function e2b(b){Y1b(this.b)};_.cM={26:1,47:1};_.b=null;_=h2b.prototype=f2b.prototype=new Kr;_.gC=function i2b(){return Hfb};_.mc=function j2b(b){Y1b(this.b)};_.cM={32:1,47:1};_.b=null;_=m2b.prototype=k2b.prototype=new Kr;_.gC=function n2b(){return Ifb};_.mc=function o2b(b){X1b(this.b)};_.cM={32:1,47:1};_.b=null;var Gab=R7c(YFd,zWd),Gfb=R7c(uId,AWd),Hfb=R7c(uId,BWd),Ifb=R7c(uId,CWd);$entry(Tsb)();