function q5(){}
function k5(){}
function KCb(){}
function ECb(){}
function bbc(){}
function gbc(){}
function UOc(){}
function p5(){p5=Ymd;o5=new q5}
function dbc(b,c){this.c=b;this.b=c}
function ibc(b,c){this.c=b;this.b=c}
function Uac(b,c){REc(c.b,v5d+b.Pf()+urd+b.Qf(),false)}
function MCb(){HCb=new KCb;pC((mC(),lC),38);!!$stats&&$stats(gD(t5d,xpd,-1,-1));HCb.Rd();!!$stats&&$stats(gD(t5d,GNd,-1,-1))}
function K_c(c){try{var d=c.document.selection.createRange();if(d.parentElement()!==c)return 0;return d.text.length}catch(b){return 0}}
function J_c(c){try{var d=c.document.selection.createRange();if(d.parentElement()!==c)return -1;return -d.move(y5d,-65535)}catch(b){return 0}}
function sPc(){var b;jPc();cPc.call(this,(b=$doc.createElement(pBd),b.type=w5d,b),(!rec&&(rec=new tec),!mec&&(mec=new oec)));this.N[_od]=x5d}
function Sac(b,c){var d,e,f,i;d=new mKc;d.f[OBd]=4;f=hKc(d);d.c.appendChild(f);Tv(b);zZc(d.j,b);f.appendChild(b.N);Vv(b,d);if(c){e=new wEc(u5d);Jv(b,new dbc(b,e),(IP(),IP(),HP));Jv(b,new ibc(b,e),(aO(),aO(),_N));i=hKc(d);d.c.appendChild(i);Tv(e);zZc(d.j,e);i.appendChild(e.N);Vv(e,d)}return d}
function M_c(c){try{var d=c.document.selection.createRange();if(d.parentElement()!==c)return 0;var e=d.text.length;var f=0;var g=d.duplicate();g.moveEnd(y5d,-1);var i=g.text.length;while(i==e&&g.parentElement()==c&&d.compareEndPoints(A5d,g)<=0){f+=2;g.moveEnd(y5d,-1);i=g.text.length}return e+f}catch(b){return 0}}
function L_c(c){try{var d=c.document.selection.createRange();if(d.parentElement()!==c)return -1;var e=d.duplicate();e.moveToElementText(c);e.setEndPoint(z5d,d);var f=e.text.length;var g=0;var i=e.duplicate();i.moveEnd(y5d,-1);var j=i.text.length;while(j==f&&i.parentElement()==c){g+=2;i.moveEnd(y5d,-1);j=i.text.length}return f+g}catch(b){return 0}}
function JCb(){var b,c,d,e,f,g,i;while(FCb){b=FCb;FCb=FCb.c;!FCb&&(GCb=null);HLb(b.b.b,(i=new yYc,i.f[OBd]=5,f=new oPc,NXc(f.N,npd,k5d),UU(f.b,(p5(),p5(),o5)),d=new oPc,NXc(d.N,npd,l5d),d.N[jPd]=m5d,TU(d.b),d.N[VOd]=true,uYc(i,new EEc(n5d)),uYc(i,Sac(f,true)),uYc(i,Sac(d,false)),e=new sPc,NXc(e.N,npd,o5d),c=new sPc,NXc(c.N,npd,p5d),c.N[jPd]=m5d,TU(c.b),c.N[VOd]=true,uYc(i,new EEc(q5d)),uYc(i,Sac(e,true)),uYc(i,Sac(c,false)),g=new CVc,NXc(g.N,npd,r5d),g.N.rows=5,uYc(i,new EEc(s5d)),uYc(i,Sac(g,true)),i))}}
var n5d='<b>\u5E38\u89C4\u6587\u672C\u6846:<\/b>',q5d='<br><br><b>\u5BC6\u7801\u6587\u672C\u6846:<\/b>',s5d='<br><br><b>\u6587\u672C\u533A\u57DF:<\/b>',B5d='AnyRtlDirectionEstimator',C5d='AsyncLoader38',D5d='CwBasicText$2',E5d='CwBasicText$3',z5d='EndToStart',F5d='PasswordTextBox',A5d='StartToEnd',y5d='character',o5d='cwBasicText-password',p5d='cwBasicText-password-disabled',r5d='cwBasicText-textarea',k5d='cwBasicText-textbox',l5d='cwBasicText-textbox-disabled',x5d='gwt-PasswordTextBox',w5d='password',t5d='runCallbacks38',m5d='\u53EA\u8BFB',v5d='\u5DF2\u9009\u62E9: ',u5d='\u5DF2\u9009\u62E9: 0, 0';_=q5.prototype=k5.prototype=new l5;_.Qd=function r5(b){return H5.test((Q5(),b))?(gZ(),fZ):(gZ(),eZ)};_.gC=function s5(){return lab};_.cM={};var o5;_=KCb.prototype=ECb.prototype=new Kr;_.gC=function LCb(){return acb};_.Rd=function PCb(){JCb()};_.cM={};_=dbc.prototype=bbc.prototype=new Kr;_.gC=function ebc(){return chb};_.mc=function fbc(b){Uac(this.c,this.b)};_.cM={32:1,47:1};_.b=null;_.c=null;_=ibc.prototype=gbc.prototype=new Kr;_.gC=function jbc(){return dhb};_.kc=function kbc(b){Uac(this.c,this.b)};_.cM={27:1,47:1};_.b=null;_.c=null;_=XOc.prototype;_.Pf=function ePc(){return J_c(this.N)};_.Qf=function fPc(){return K_c(this.N)};_=sPc.prototype=UOc.prototype=new VOc;_.gC=function tPc(){return Ykb};_.cM={14:1,15:1,17:1,18:1,74:1,76:1};_=AVc.prototype;_.Pf=function EVc(){return L_c(this.N)};_.Qf=function FVc(){return M_c(this.N)};var lab=R7c(TFd,B5d),acb=R7c(YFd,C5d),chb=R7c(HJd,D5d),dhb=R7c(HJd,E5d),Ykb=R7c(GDd,F5d);$entry(MCb)();