function vHb(){}
function pHb(){}
function iOc(){}
function GOc(){}
function EOc(){}
function IOc(){}
function POc(){}
function NOc(){}
function yOc(b){if(b==mOc){return true}Q$();return b==pOc}
function zOc(b){if(b==lOc){return true}Q$();return b==kOc}
function LOc(b){this.c=(kRc(),fRc).b;this.e=(ARc(),zRc).b;this.b=b}
function AOc(){qOc();VHc.call(this);this.c=(kRc(),fRc);this.d=(ARc(),zRc);this.f[fId]=0;this.f[gId]=0}
function vOc(b,c){var d;d=vfb(b.L,116);d.c=c.b;!!d.d&&(d.d[dId]=c.b,undefined)}
function wOc(b,c){var d;d=vfb(b.L,116);d.e=c.b;!!d.d&&(d.d.style[eId]=c.b,undefined)}
function qOc(){qOc=Otd;jOc=new GOc;mOc=new GOc;lOc=new GOc;kOc=new GOc;nOc=new GOc;oOc=new GOc;pOc=new GOc}
function xHb(){sHb=new vHb;WC((TC(),SC),27);!!$stats&&$stats(ND(A8d,mwd,-1,-1));sHb.Hd();!!$stats&&$stats(ND(A8d,xTd,-1,-1))}
function sOc(b,c,d){var e;if(d==jOc){if(c==b.b){return}else if(b.b){throw new hfd(B8d)}}yw(c);y4c(b.j,c);d==jOc&&(b.b=c);e=new LOc(d);c.L=e;vOc(c,b.c);wOc(c,b.d);uOc(b);Aw(c,b)}
function tOc(b,c){var d,e,f,g,i,j,k,n;a3c(b.N,cwd,c);j=new bqd;k=new O4c(b.j);while(k.b<k.c.d-1){d=M4c(k);i=vfb(d.L,116).b;f=vfb(j.Vc(i),10);e=!f?1:f.b;g=i==nOc?C8d+e:i==oOc?D8d+e:i==pOc?E8d+e:i==kOc?F8d+e:i==mOc?G8d+e:i==lOc?H8d+e:LHd;a3c((n=d.N.parentNode,(!n||n.nodeType!=1)&&(n=null),n),c,g);j.Xc(i,Hfd(e+1))}}
function uHb(){var b,c,d,e;while(qHb){b=qHb;qHb=qHb.c;!qHb&&(rHb=null);oUb(b.b.b,(d=new AOc,d.N[Rvd]=p8d,d.f[fId]=4,d.c=(kRc(),eRc),sOc(d,new fMc(q8d),(qOc(),nOc)),sOc(d,new fMc(r8d),oOc),sOc(d,new fMc(s8d),kOc),sOc(d,new fMc(t8d),pOc),sOc(d,new fMc(u8d),nOc),sOc(d,new fMc(v8d),oOc),c=new fMc(w8d),e=new XZc(c),e.N.style[pAd]=x8d,e.N.style[qAd]=y8d,sOc(d,e,jOc),tOc(d,z8d),d))}}
function uOc(b){var c,d,e,f,g,i,j,k,n,o,p,q,r,s,t,u;c=b.e;while(gFc(c)>0){c.removeChild(fFc(c,0))}r=1;f=1;for(j=new O4c(b.j);j.b<j.c.d-1;){e=M4c(j);g=vfb(e.L,116).b;g==nOc||g==oOc?++r:(g==kOc||g==pOc||g==mOc||g==lOc)&&++f}s=ffb(xyb,{19:1},71,r,0);for(i=0;i<r;++i){s[i]=new POc;s[i].c=$doc.createElement(bId);c.appendChild(s[i].c)}n=0;o=f-1;p=0;t=r-1;d=null;for(j=new O4c(b.j);j.b<j.c.d-1;){e=M4c(j);k=vfb(e.L,116);u=$doc.createElement(cId);k.d=u;k.d[dId]=k.c;k.d.style[eId]=k.e;k.d[pAd]=cwd;k.d[qAd]=cwd;if(k.b==nOc){jFc(s[p].c,u,s[p].b);u.appendChild(e.N);u[WZd]=o-n+1;++p}else if(k.b==oOc){jFc(s[t].c,u,s[t].b);u.appendChild(e.N);u[WZd]=o-n+1;--t}else if(k.b==jOc){d=u}else if(yOc(k.b)){q=s[p];jFc(q.c,u,q.b++);u.appendChild(e.N);u[I8d]=t-p+1;++n}else if(zOc(k.b)){q=s[p];jFc(q.c,u,q.b);u.appendChild(e.N);u[I8d]=t-p+1;--o}}if(b.b){q=s[p];jFc(q.c,d,q.b);d.appendChild(b.b.N)}}
var y8d='100px',J8d='AsyncLoader27',M8d='DockPanel',N8d='DockPanel$DockLayoutConstant',O8d='DockPanel$LayoutData',K8d='DockPanel$TmpRow',L8d='DockPanel$TmpRow;',B8d='Only one CENTER widget may be added',w8d="This is a <code>ScrollPanel<\/code> contained at the center of a <code>DockPanel<\/code>.  By putting some fairly large contents in the middle and setting its size explicitly, it becomes a scrollable area within the page, but without requiring the use of an IFRAME.<br><br>Here's quite a bit more meaningless text that will serve primarily to make this thing scroll off the bottom of its visible area.  Otherwise, you might have to make it really, really small in order to see the nifty scroll bars!",s8d='This is the east component',q8d='This is the first north component',r8d='This is the first south component',u8d='This is the second north component',v8d='This is the second south component',t8d='This is the west component',p8d='cw-DockPanel',z8d='cwDockPanel',F8d='east',H8d='lineend',G8d='linestart',C8d='north',A8d='runCallbacks27',D8d='south',E8d='west';_=vHb.prototype=pHb.prototype=new ps;_.gC=function wHb(){return Xkb};_.Hd=function AHb(){uHb()};_.cM={};_=AOc.prototype=iOc.prototype=new PHc;_.gC=function BOc(){return Atb};_.sb=function COc(b){tOc(this,b)};_.Hb=function DOc(b){var c;c=sGc(this,b);if(c){b==this.b&&(this.b=null);uOc(this)}return c};_.cM={14:1,15:1,17:1,18:1,73:1,75:1,128:1};_.b=null;var jOc,kOc,lOc,mOc,nOc,oOc,pOc;_=GOc.prototype=EOc.prototype=new ps;_.gC=function HOc(){return xtb};_.cM={};_=LOc.prototype=IOc.prototype=new ps;_.gC=function MOc(){return ytb};_.cM={116:1};_.b=null;_.d=null;_=POc.prototype=NOc.prototype=new ps;_.gC=function QOc(){return ztb};_.cM={71:1};_.b=0;_.c=null;var Xkb=Hed(VLd,J8d),ztb=Hed(yJd,K8d),xyb=Ged(pRd,L8d,ztb),Atb=Hed(yJd,M8d),xtb=Hed(yJd,N8d),ytb=Hed(yJd,O8d);$entry(xHb)();