function oHb(){}
function iHb(){}
function iPc(){}
function bPc(){}
function gPc(){}
function DOc(){}
function _Oc(){}
function ZOc(){}
function TOc(b){if(b==HOc){return true}L$();return b==KOc}
function UOc(b){if(b==GOc){return true}L$();return b==FOc}
function ePc(b){this.c=(CRc(),xRc).b;this.e=(SRc(),RRc).b;this.b=b}
function VOc(){LOc();oIc.call(this);this.c=(CRc(),xRc);this.d=(SRc(),RRc);this.f[uJd]=0;this.f[vJd]=0}
function QOc(b,c){var d;d=qfb(b.L,116);d.c=c.b;!!d.d&&(d.d[sJd]=c.b,undefined)}
function ROc(b,c){var d;d=qfb(b.L,116);d.e=c.b;!!d.d&&(d.d.style[tJd]=c.b,undefined)}
function LOc(){LOc=yud;EOc=new _Oc;HOc=new _Oc;GOc=new _Oc;FOc=new _Oc;IOc=new _Oc;JOc=new _Oc;KOc=new _Oc}
function qHb(){lHb=new oHb;TC((QC(),PC),27);!!$stats&&$stats(KD(O9d,Zwd,-1,-1));lHb.Ed();!!$stats&&$stats(KD(O9d,JUd,-1,-1))}
function NOc(b,c,d){var e;if(d==EOc){if(c==b.b){return}else if(b.b){throw new Tfd(P9d)}}ww(c);q5c(b.j,c);d==EOc&&(b.b=c);e=new ePc(d);c.L=e;QOc(c,b.c);ROc(c,b.d);POc(b);yw(c,b)}
function OOc(b,c){var d,e,f,g,i,j,k,n;F3c(b.N,Pwd,c);j=new Nqd;k=new G5c(b.j);while(k.b<k.c.d-1){d=E5c(k);i=qfb(d.L,116).b;f=qfb(j.Sc(i),10);e=!f?1:f.b;g=i==IOc?Q9d+e:i==JOc?R9d+e:i==KOc?S9d+e:i==FOc?T9d+e:i==HOc?U9d+e:i==GOc?V9d+e:_Id;F3c((n=d.N.parentNode,(!n||n.nodeType!=1)&&(n=null),n),c,g);j.Uc(i,rgd(e+1))}}
function nHb(){var b,c,d,e;while(jHb){b=jHb;jHb=jHb.c;!jHb&&(kHb=null);pUb(b.b.b,(d=new VOc,d.N[Bwd]=D9d,d.f[uJd]=4,d.c=(CRc(),wRc),NOc(d,new AMc(E9d),(LOc(),IOc)),NOc(d,new AMc(F9d),JOc),NOc(d,new AMc(G9d),FOc),NOc(d,new AMc(H9d),KOc),NOc(d,new AMc(I9d),IOc),NOc(d,new AMc(J9d),JOc),c=new AMc(K9d),e=new w$c(c),e.N.style[VAd]=L9d,e.N.style[WAd]=M9d,NOc(d,e,EOc),OOc(d,N9d),d))}}
function POc(b){var c,d,e,f,g,i,j,k,n,o,p,q,r,s,t,u;c=b.e;while(c.children.length>0){c.removeChild(c.children[0])}r=1;f=1;for(j=new G5c(b.j);j.b<j.c.d-1;){e=E5c(j);g=qfb(e.L,116).b;g==IOc||g==JOc?++r:(g==FOc||g==KOc||g==HOc||g==GOc)&&++f}s=afb(qyb,{19:1},71,r,0);for(i=0;i<r;++i){s[i]=new iPc;s[i].c=lH($doc,qJd);c.appendChild(s[i].c)}n=0;o=f-1;p=0;t=r-1;d=null;for(j=new G5c(b.j);j.b<j.c.d-1;){e=E5c(j);k=qfb(e.L,116);u=lH($doc,rJd);k.d=u;k.d[sJd]=k.c;k.d.style[tJd]=k.e;k.d[VAd]=Pwd;k.d[WAd]=Pwd;if(k.b==IOc){AFc(s[p].c,u,s[p].b);u.appendChild(e.N);u[h_d]=o-n+1;++p}else if(k.b==JOc){AFc(s[t].c,u,s[t].b);u.appendChild(e.N);u[h_d]=o-n+1;--t}else if(k.b==EOc){d=u}else if(TOc(k.b)){q=s[p];AFc(q.c,u,q.b++);u.appendChild(e.N);u[W9d]=t-p+1;++n}else if(UOc(k.b)){q=s[p];AFc(q.c,u,q.b);u.appendChild(e.N);u[W9d]=t-p+1;--o}}if(b.b){q=s[p];AFc(q.c,d,q.b);d.appendChild(b.b.N)}}
var M9d='100px',X9d='AsyncLoader27',$9d='DockPanel',_9d='DockPanel$DockLayoutConstant',aae='DockPanel$LayoutData',Y9d='DockPanel$TmpRow',Z9d='DockPanel$TmpRow;',P9d='Only one CENTER widget may be added',K9d="This is a <code>ScrollPanel<\/code> contained at the center of a <code>DockPanel<\/code>.  By putting some fairly large contents in the middle and setting its size explicitly, it becomes a scrollable area within the page, but without requiring the use of an IFRAME.<br><br>Here's quite a bit more meaningless text that will serve primarily to make this thing scroll off the bottom of its visible area.  Otherwise, you might have to make it really, really small in order to see the nifty scroll bars!",G9d='This is the east component',E9d='This is the first north component',F9d='This is the first south component',I9d='This is the second north component',J9d='This is the second south component',H9d='This is the west component',D9d='cw-DockPanel',N9d='cwDockPanel',T9d='east',V9d='lineend',U9d='linestart',Q9d='north',O9d='runCallbacks27',R9d='south',S9d='west';_=oHb.prototype=iHb.prototype=new ns;_.gC=function pHb(){return Nkb};_.Ed=function tHb(){nHb()};_.cM={};_=VOc.prototype=DOc.prototype=new iIc;_.gC=function WOc(){return stb};_.sb=function XOc(b){OOc(this,b)};_.Hb=function YOc(b){var c;c=PGc(this,b);if(c){b==this.b&&(this.b=null);POc(this)}return c};_.cM={14:1,15:1,17:1,18:1,73:1,75:1,128:1};_.b=null;var EOc,FOc,GOc,HOc,IOc,JOc,KOc;_=_Oc.prototype=ZOc.prototype=new ns;_.gC=function aPc(){return ptb};_.cM={};_=ePc.prototype=bPc.prototype=new ns;_.gC=function fPc(){return qtb};_.cM={116:1};_.b=null;_.d=null;_=iPc.prototype=gPc.prototype=new ns;_.gC=function jPc(){return rtb};_.cM={71:1};_.b=0;_.c=null;var Nkb=rfd(fNd,X9d),rtb=rfd(PKd,Y9d),qyb=qfd(zSd,Z9d,rtb),stb=rfd(PKd,$9d),ptb=rfd(PKd,_9d),qtb=rfd(PKd,aae);$entry(qHb)();