function OGb(){}
function IGb(){}
function DNc(){}
function _Nc(){}
function ZNc(){}
function bOc(){}
function iOc(){}
function gOc(){}
function TNc(b){if(b==HNc){return true}o$();return b==KNc}
function UNc(b){if(b==GNc){return true}o$();return b==FNc}
function eOc(b){this.c=(CQc(),xQc).b;this.e=(SQc(),RQc).b;this.b=b}
function VNc(){LNc();oHc.call(this);this.c=(CQc(),xQc);this.d=(SQc(),RQc);this.f[mHd]=0;this.f[nHd]=0}
function QNc(b,c){var d;d=Veb(b.L,116);d.c=c.b;!!d.d&&(d.d[kHd]=c.b,undefined)}
function RNc(b,c){var d;d=Veb(b.L,116);d.e=c.b;!!d.d&&(d.d.style[lHd]=c.b,undefined)}
function LNc(){LNc=Zsd;ENc=new _Nc;HNc=new _Nc;GNc=new _Nc;FNc=new _Nc;INc=new _Nc;JNc=new _Nc;KNc=new _Nc}
function QGb(){LGb=new OGb;PC((MC(),LC),27);!!$stats&&$stats(GD(C7d,xvd,-1,-1));LGb.Dd();!!$stats&&$stats(GD(C7d,vSd,-1,-1))}
function NNc(b,c,d){var e;if(d==ENc){if(c==b.b){return}else if(b.b){throw new sed(D7d)}}rw(c);L3c(b.j,c);d==ENc&&(b.b=c);e=new eOc(d);c.L=e;QNc(c,b.c);RNc(c,b.d);PNc(b);tw(c,b)}
function ONc(b,c){var d,e,f,g,i,j,k,n;n2c(b.N,nvd,c);j=new mpd;k=new _3c(b.j);while(k.b<k.c.d-1){d=Z3c(k);i=Veb(d.L,116).b;f=Veb(j.Rc(i),10);e=!f?1:f.b;g=i==INc?E7d+e:i==JNc?F7d+e:i==KNc?G7d+e:i==FNc?H7d+e:i==HNc?I7d+e:i==GNc?J7d+e:SGd;n2c((n=d.N.parentNode,(!n||n.nodeType!=1)&&(n=null),n),c,g);j.Tc(i,Sed(e+1))}}
function NGb(){var b,c,d,e;while(JGb){b=JGb;JGb=JGb.c;!JGb&&(KGb=null);HTb(b.b.b,(d=new VNc,d.N[avd]=r7d,d.f[mHd]=4,d.c=(CQc(),wQc),NNc(d,new ALc(s7d),(LNc(),INc)),NNc(d,new ALc(t7d),JNc),NNc(d,new ALc(u7d),FNc),NNc(d,new ALc(v7d),KNc),NNc(d,new ALc(w7d),INc),NNc(d,new ALc(x7d),JNc),c=new ALc(y7d),e=new iZc(c),e.N.style[uzd]=z7d,e.N.style[vzd]=A7d,NNc(d,e,ENc),ONc(d,B7d),d))}}
function PNc(b){var c,d,e,f,g,i,j,k,n,o,p,q,r,s,t,u;c=b.e;while(zEc(c)>0){c.removeChild(yEc(c,0))}r=1;f=1;for(j=new _3c(b.j);j.b<j.c.d-1;){e=Z3c(j);g=Veb(e.L,116).b;g==INc||g==JNc?++r:(g==FNc||g==KNc||g==HNc||g==GNc)&&++f}s=Feb(Qxb,{19:1},71,r,0);for(i=0;i<r;++i){s[i]=new iOc;s[i].c=$doc.createElement(iHd);c.appendChild(s[i].c)}n=0;o=f-1;p=0;t=r-1;d=null;for(j=new _3c(b.j);j.b<j.c.d-1;){e=Z3c(j);k=Veb(e.L,116);u=$doc.createElement(jHd);k.d=u;k.d[kHd]=k.c;k.d.style[lHd]=k.e;k.d[uzd]=nvd;k.d[vzd]=nvd;if(k.b==INc){CEc(s[p].c,u,s[p].b);u.appendChild(e.N);u[XYd]=o-n+1;++p}else if(k.b==JNc){CEc(s[t].c,u,s[t].b);u.appendChild(e.N);u[XYd]=o-n+1;--t}else if(k.b==ENc){d=u}else if(TNc(k.b)){q=s[p];CEc(q.c,u,q.b++);u.appendChild(e.N);u[K7d]=t-p+1;++n}else if(UNc(k.b)){q=s[p];CEc(q.c,u,q.b);u.appendChild(e.N);u[K7d]=t-p+1;--o}}if(b.b){q=s[p];CEc(q.c,d,q.b);d.appendChild(b.b.N)}}
var A7d='100px',L7d='AsyncLoader27',O7d='DockPanel',P7d='DockPanel$DockLayoutConstant',Q7d='DockPanel$LayoutData',M7d='DockPanel$TmpRow',N7d='DockPanel$TmpRow;',D7d='Only one CENTER widget may be added',y7d="This is a <code>ScrollPanel<\/code> contained at the center of a <code>DockPanel<\/code>.  By putting some fairly large contents in the middle and setting its size explicitly, it becomes a scrollable area within the page, but without requiring the use of an IFRAME.<br><br>Here's quite a bit more meaningless text that will serve primarily to make this thing scroll off the bottom of its visible area.  Otherwise, you might have to make it really, really small in order to see the nifty scroll bars!",u7d='This is the east component',s7d='This is the first north component',t7d='This is the first south component',w7d='This is the second north component',x7d='This is the second south component',v7d='This is the west component',r7d='cw-DockPanel',B7d='cwDockPanel',H7d='east',J7d='lineend',I7d='linestart',E7d='north',C7d='runCallbacks27',F7d='south',G7d='west';_=OGb.prototype=IGb.prototype=new is;_.gC=function PGb(){return skb};_.Dd=function TGb(){NGb()};_.cM={};_=VNc.prototype=DNc.prototype=new iHc;_.gC=function WNc(){return Wsb};_.sb=function XNc(b){ONc(this,b)};_.Hb=function YNc(b){var c;c=PFc(this,b);if(c){b==this.b&&(this.b=null);PNc(this)}return c};_.cM={14:1,15:1,17:1,18:1,73:1,75:1,128:1};_.b=null;var ENc,FNc,GNc,HNc,INc,JNc,KNc;_=_Nc.prototype=ZNc.prototype=new is;_.gC=function aOc(){return Tsb};_.cM={};_=eOc.prototype=bOc.prototype=new is;_.gC=function fOc(){return Usb};_.cM={116:1};_.b=null;_.d=null;_=iOc.prototype=gOc.prototype=new is;_.gC=function jOc(){return Vsb};_.cM={71:1};_.b=0;_.c=null;var skb=Sdd(XKd,L7d),Vsb=Sdd(FId,M7d),Qxb=Rdd(nQd,N7d,Vsb),Wsb=Sdd(FId,O7d),Tsb=Sdd(FId,P7d),Usb=Sdd(FId,Q7d);$entry(QGb)();