function PPb(){}
function JPb(){}
function d7b(){}
function i7b(){}
function k7b(b){this.b=b}
function f7b(b,c){this.b=b;this.c=c}
function q7b(b){HTb(b.c,$6b(b.b))}
function Mdb(b,c){var d;d=jeb((eeb(),c));return Ndb(b,d,c,false)}
function OPb(){var b;while(KPb){b=KPb;KPb=KPb.c;!KPb&&(LPb=null);q7b(b.b)}}
function P6b(b,c,d){return Agd(Agd(Agd(Agd(Agd(Agd(Agd(new Egd,TYd),b),UYd),c),VYd),d),Czd).b.b}
function RPb(){MPb=new PPb;PC((MC(),LC),7);!!$stats&&$stats(GD(SYd,xvd,-1,-1));MPb.Dd();!!$stats&&$stats(GD(SYd,vSd,-1,-1))}
function _6b(b){var c,d,e;c=Xfd(oG(b.b.N,aUd));d=Xfd(oG(b.c.N,aUd));e=Xfd(oG(b.d.N,aUd));NLc(b.g.b,Agd(Agd(Agd(Agd(Agd(Agd(Agd(new Egd,TYd),c),UYd),d),VYd),e),Czd).b.b,false);NLc(b.e.b,P6b(Mdb(b.f,c),ESb(d),Mdb(b.f,e)),true)}
function $6b(b){var c,d,e,f,g,i,j,k,n,p,q,r,s,t,u,v,w,x,y,z,A,B,C;e=new XOc;c=Veb(e.k,96);e.p[mHd]=5;i=(k=bob.d,Sfd(k,k.lastIndexOf(Jzd)+1));f=new AGc(i);hw(f,new f7b(b,i),(QN(),QN(),PN));g=new hRc;g.f[mHd]=3;bRc(g,new ALc(WYd));n=cRc(g);g.c.appendChild(n);rw(f);L3c(g.j,f);n.appendChild(f.N);tw(f,g);NOc(e,0,0,g);(c.b.pf(0,0),c.b.j.rows[0].cells[0])[XYd]=2;j=Agd(Agd(Agd(Agd(Agd(Agd(Agd(new Egd,TYd),YYd),UYd),ZYd),VYd),$Yd),Czd).b.b;e.pf(1,0);p=(q=e.k.b.j.rows[1].cells[0],DOc(e,q,false),q);p.innerHTML=_Yd;e.pf(1,1);r=(s=e.k.b.j.rows[1].cells[1],DOc(e,s,j==null),s);j!=null&&(r.innerHTML=j||nvd,undefined);b.b=new VVc;IVc(b.b,(o$(),aZd));e.pf(2,0);t=(u=e.k.b.j.rows[2].cells[0],DOc(e,u,false),u);t.innerHTML=bZd;NOc(e,2,1,b.b);b.c=new VVc;IVc(b.c,cZd);e.pf(3,0);v=(w=e.k.b.j.rows[3].cells[0],DOc(e,w,false),w);v.innerHTML=dZd;NOc(e,3,1,b.c);b.d=new VVc;IVc(b.d,eZd);e.pf(4,0);x=(y=e.k.b.j.rows[4].cells[0],DOc(e,y,false),y);x.innerHTML=fZd;NOc(e,4,1,b.d);b.g=new yLc;e.pf(5,0);z=(A=e.k.b.j.rows[5].cells[0],DOc(e,A,false),A);z.innerHTML=gZd;NOc(e,5,1,b.g);lPc(c,5,0,(SQc(),RQc));b.e=new yLc;e.pf(6,0);B=(C=e.k.b.j.rows[6].cells[0],DOc(e,C,false),C);B.innerHTML=hZd;NOc(e,6,1,b.e);lPc(c,6,0,RQc);d=new k7b(b);hw(b.b,d,(wP(),wP(),vP));hw(b.c,d,vP);hw(b.d,d,vP);_6b(b);return e}
var VYd=" posts) added a comment on '",cZd='16',hZd='<b>Message formatted with BidiFormatter:<\/b>',gZd='<b>Message formatted without BidiFormatter:<\/b>',jZd='AsyncLoader7',kZd='BlogMessages',lZd='CwBidiFormatting$1',mZd='CwBidiFormatting$2',TYd='User ',SYd='runCallbacks7',eZd='\u05DB\u05DE\u05D4 \u05D7\u05D5\u05DC \u05D9\u05E9 \u05D1\u05D7\u05D5\u05E3?',aZd='\u05EA\u05D5\u05DE\u05E8 \u05D2\u05E8\u05D9\u05DF';_=PPb.prototype=JPb.prototype=new is;_.gC=function QPb(){return Jlb};_.Dd=function UPb(){OPb()};_.cM={};_=f7b.prototype=d7b.prototype=new is;_.gC=function g7b(){return eob};_.gc=function h7b(b){_Sb(this.b,this.c+iZd)};_.cM={27:1,47:1};_.b=null;_.c=null;_=k7b.prototype=i7b.prototype=new is;_.gC=function l7b(){return fob};_.ic=function m7b(b){_6b(this.b)};_.cM={32:1,47:1};_.b=null;var Jlb=Sdd(XKd,jZd),bob=Udd(nNd,kZd),eob=Sdd(nNd,lZd),fob=Sdd(nNd,mZd);$entry(RPb)();