function Uwb(){}
function Owb(){}
function j5b(){}
function o5b(){}
function t5b(){}
function l5b(b){this.b=b}
function q5b(b){this.b=b}
function v5b(b){this.b=b}
function B5b(b){YOb(b.c,c5b(b.b))}
function Twb(){var b;while(Pwb){b=Pwb;Pwb=Pwb.c;!Pwb&&(Qwb=null);B5b(b.b)}}
function d5b(b,c){if(c==null){Qv(b.d.N,VVd,false)}else{cHc(b.d.b,c,false);Qv(b.d.rb(),VVd,true)}}
function Wwb(){Rwb=new Uwb;EC((BC(),AC),14);!!$stats&&$stats(vD(JWd,Pqd,-1,-1));Rwb.Bd();!!$stats&&$stats(vD(JWd,QNd,-1,-1))}
function XQb(b){var c,d;c=vab(b.b.Yc(KWd),54);if(c==null){d=gab(otb,{19:1,54:1},1,[LWd,MWd,NWd,OWd,PWd]);b.b.$c(KWd,d);return d}else{return c}}
function e5b(c){var b,e,f,g;f=dG(c.g.N,vPd);if(Xad(f,Fqd)){cHc(c.d.b,WVd,false)}else{try{g=z9c(f);e=JZ(c.b,g);cHc(c.d.b,e,false);d5b(c,null)}catch(b){b=Btb(b);if(zab(b,55)){d5b(c,XVd)}else throw b}}}
function f5b(c){var b,e;switch(c.f.N.selectedIndex){case 0:c.b=(DZ(),!yZ&&(yZ=new VZ(BZ.Hc(),LW((VU(),UU)),false)),DZ(),yZ);ZQc(c.e,c.b.v);c.e.N[fPd]=!false;break;case 1:c.b=(DZ(),!xZ&&(xZ=new VZ(BZ.Gc(),LW((VU(),UU)),false)),DZ(),xZ);ZQc(c.e,c.b.v);c.e.N[fPd]=!false;break;case 2:c.b=(DZ(),!AZ&&(AZ=new VZ(BZ.Tc(),LW((VU(),UU)),false)),DZ(),AZ);ZQc(c.e,c.b.v);c.e.N[fPd]=!false;break;case 3:c.b=(DZ(),!zZ&&(zZ=new VZ(BZ.Sc(),LW((VU(),UU)),false)),DZ(),zZ);ZQc(c.e,c.b.v);c.e.N[fPd]=!false;break;case 4:c.e.N[fPd]=!true;e=dG(c.e.N,vPd);try{c.b=(DZ(),new VZ(e,LW((VU(),UU)),true))}catch(b){b=Btb(b);if(zab(b,98)){d5b(c,RWd);return}else throw b}}e5b(c)}
function c5b(b){var c,d,e,f,g,i,j,k,n,o,p;c=new XKc(4,2);c.p[HCd]=5;b.f=new BOc;b.f.N.style[Mud]=SUd;g=XQb(b.c);for(e=0,f=g.length;e<f;++e){d=g[e];wOc(b.f,d)}Yv(b.f,new l5b(b),(mN(),mN(),lN));c.nf(0,0);i=(j=c.k.b.j.rows[0].cells[0],UJc(c,j,false),j);i.innerHTML=RVd;cKc(c,0,1,b.f);b.e=new kRc;b.e.N.style[Mud]=SUd;Yv(b.e,new q5b(b),(lP(),lP(),kP));cKc(c,1,1,b.e);b.g=new kRc;b.g.N.style[Mud]=SUd;ZQc(b.g,QWd);Yv(b.g,new v5b(b),kP);c.nf(2,0);k=(n=c.k.b.j.rows[2].cells[0],UJc(c,n,false),n);k.innerHTML=TVd;cKc(c,2,1,b.g);b.d=new IGc;b.d.N.style[Mud]=SUd;c.nf(3,0);o=(p=c.k.b.j.rows[3].cells[0],UJc(c,p,false),p);o.innerHTML=UVd;cKc(c,3,1,b.d);f5b(b);return c}
var GWd='#,##0%',HWd='#E0',QWd='31415926535.897932',SWd='AsyncLoader14',TWd='CwNumberFormat$1',UWd='CwNumberFormat$2',VWd='CwNumberFormat$3',KWd='cwNumberFormatPatterns',JWd='runCallbacks14',IWd='\xA4#0.00',FWd='\xA4\xA0#,##0.00;\xA4\xA0#,##0.00-',PWd='\u062A\u062E\u0635\u064A\u0635',LWd='\u0639\u0634\u0631\u064A',NWd='\u0639\u0644\u0645\u064A',MWd='\u0639\u0645\u0644\u0629',OWd='\u0646\u0633\u0628\u0629 \u0645\u0624\u0648\u064A\u0629',RWd='\u0646\u0645\u0637 \u063A\u064A\u0631 \u0635\u0627\u0644\u062D';var xZ=null,zZ=null,AZ=null;_=k$.prototype;_.Gc=function n$(){return FWd};_.Sc=function A$(){return GWd};_.Tc=function B$(){return HWd};_=D$.prototype;_.Gc=function G$(){return FWd};_.Sc=function T$(){return GWd};_.Tc=function U$(){return HWd};_=W$.prototype;_.Gc=function Z$(){return FWd};_.Sc=function k_(){return GWd};_.Tc=function l_(){return HWd};_=n_.prototype;_.Gc=function q_(){return FWd};_.Sc=function D_(){return GWd};_.Tc=function E_(){return HWd};_=G_.prototype;_.Gc=function J_(){return FWd};_.Sc=function W_(){return GWd};_.Tc=function X_(){return HWd};_=Z_.prototype;_.Gc=function a0(){return FWd};_.Sc=function n0(){return GWd};_.Tc=function o0(){return HWd};_=q0.prototype;_.Gc=function t0(){return FWd};_.Sc=function G0(){return GWd};_.Tc=function H0(){return HWd};_=J0.prototype;_.Gc=function M0(){return FWd};_.Sc=function Z0(){return GWd};_.Tc=function $0(){return HWd};_=a1.prototype;_.Gc=function d1(){return FWd};_.Sc=function q1(){return GWd};_.Tc=function r1(){return HWd};_=t1.prototype;_.Gc=function w1(){return FWd};_.Sc=function J1(){return GWd};_.Tc=function K1(){return HWd};_=M1.prototype;_.Gc=function P1(){return FWd};_.Sc=function a2(){return GWd};_.Tc=function b2(){return HWd};_=d2.prototype;_.Gc=function g2(){return IWd};_.Sc=function t2(){return GWd};_.Tc=function u2(){return HWd};_=w2.prototype;_.Gc=function z2(){return IWd};_.Sc=function M2(){return GWd};_.Tc=function N2(){return HWd};_=P2.prototype;_.Gc=function S2(){return FWd};_.Sc=function d3(){return GWd};_.Tc=function e3(){return HWd};_=g3.prototype;_.Gc=function j3(){return IWd};_.Sc=function w3(){return GWd};_.Tc=function x3(){return HWd};_=z3.prototype;_.Gc=function C3(){return IWd};_.Sc=function P3(){return GWd};_.Tc=function Q3(){return HWd};_=S3.prototype;_.Gc=function V3(){return IWd};_.Sc=function g4(){return GWd};_.Tc=function h4(){return HWd};_=Uwb.prototype=Owb.prototype=new Zr;_.gC=function Vwb(){return Xeb};_.Bd=function Zwb(){Twb()};_.cM={};_=l5b.prototype=j5b.prototype=new Zr;_.gC=function m5b(){return Tjb};_.fc=function n5b(b){f5b(this.b)};_.cM={26:1,47:1};_.b=null;_=q5b.prototype=o5b.prototype=new Zr;_.gC=function r5b(){return Ujb};_.ic=function s5b(b){f5b(this.b)};_.cM={32:1,47:1};_.b=null;_=v5b.prototype=t5b.prototype=new Zr;_.gC=function w5b(){return Vjb};_.ic=function x5b(b){e5b(this.b)};_.cM={32:1,47:1};_.b=null;var Xeb=i9c(qGd,SWd),Tjb=i9c(IId,TWd),Ujb=i9c(IId,UWd),Vjb=i9c(IId,VWd);$entry(Wwb)();