function showcase(){var P='',wb='" for "gwt:onLoadErrorFn"',ub='" for "gwt:onPropertyErrorFn"',ib='"><\/script>',Z='#',Eb='&',zc='.cache.html',_='/',Yb='2ECC0140B8C8BB074B3430946546CBE1',Zb='30E7395C86FBC37CC044F5E86310E749',$b='33564726C5E78C5AAF60C7FBE3D1BDF7',ac='34D879A229D6004682A06A40AD00E0A3',cc='4BEEC4BD23DE80AD2885E799EDD59328',dc='4D60378694A89986A5F25437B56859AA',fc='4EE63839B8AE3682C087ED09A3FD6E71',gc='52DA2AD481ED1931BCB6F13E3130771C',hc='540BCDE8F67A426375E24D87804714BA',ic='5C063B1403E0777F83B74CDD334A47E3',jc='5DB77472568D46E3DBE9B6F9E11CC034',kc='6AD846B12C20954CD84D9822AC2AD799',lc='787441EACA24C6B9FC321F2FE1FC25F9',mc='88B14ABDC858B24E5C1540DAF0A10104',nc='8F8CA057492A0CAAB487541BF951D0CA',oc='96E4B6E62C15C040D13F1300532D591C',yc=':',ob='::',Gb=';',Bc='<script defer="defer">showcase.onInjectionDone(\'showcase\')<\/script>',hb='<script id="',rb='=',$='?',pc='A8E2CEF4A2095D55E815FF890BC09AA6',qc='BE1F556F9E32C40233C5876FA2D81692',rc='BF50BA0B05439B42B6868BFAA50867EA',sc='BFF148B6A97EDC4CA6AB51EC3024EEC5',tb='Bad handler "',tc='C1D90411D69FB1C736D1955DEB3C4878',uc='D0CF3816D53574938525EC54D0E4A90C',vc='D312A7FACF7C9C8965B510083C91F093',Ac='DOMContentLoaded',wc='E32D4225E969FD8CFE1CB86D5B8DBA56',xc='F4EB9E672E96B7638D6EDFAA327366CD',jb='SCRIPT',Fb='SHOWCASE_LOCALE=',Jb='Unexpected exception in locale detection, using default: ',Ib='_',Hb='__gwt_Locale',gb='__gwt_marker_showcase',Xb='ar',kb='base',cb='baseUrl',T='begin',S='bootstrap',bb='clear.cache.gif',qb='content',ec='default',Cb='en',Y='end',_b='fr',Rb='gecko',Sb='gecko1_8',U='gwt.codesvr=',V='gwt.hosted=',W='gwt.hybrid',vb='gwt:onLoadErrorFn',sb='gwt:onPropertyErrorFn',pb='gwt:property',Vb='hosted.html?showcase',Qb='ie6',Pb='ie8',xb='iframe',ab='img',yb="javascript:''",Ub='loadExternalRefs',Bb='locale',Db='locale=',lb='meta',Ab='moduleRequested',X='moduleStartup',Ob='msie',mb='name',Lb='opera',zb='position:absolute;width:0;height:0;border:none',Nb='safari',db='script',Wb='selectingPermutation',Q='showcase',eb='showcase.nocache.js',nb='showcase::',R='startup',fb='undefined',Tb='unknown',Kb='user.agent',Mb='webkit',bc='zh';var l=window,m=document,n=l.__gwtStatsEvent?function(a){return l.__gwtStatsEvent(a)}:null,o=l.__gwtStatsSessionId?l.__gwtStatsSessionId:null,p,q,r,s=P,t={},u=[],v=[],w=[],x=0,y,z;n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:T});if(!l.__gwt_stylesLoaded){l.__gwt_stylesLoaded={}}if(!l.__gwt_scriptsLoaded){l.__gwt_scriptsLoaded={}}function A(){var b=false;try{var c=l.location.search;return (c.indexOf(U)!=-1||(c.indexOf(V)!=-1||l.external&&l.external.gwtOnLoad))&&c.indexOf(W)==-1}catch(a){}A=function(){return b};return b}
function B(){if(p&&q){var b=m.getElementById(Q);var c=b.contentWindow;if(A()){c.__gwt_getProperty=function(a){return H(a)}}showcase=null;c.gwtOnLoad(y,Q,s,x);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Y})}}
function C(){function e(a){var b=a.lastIndexOf(Z);if(b==-1){b=a.length}var c=a.indexOf($);if(c==-1){c=a.length}var d=a.lastIndexOf(_,Math.min(c,b));return d>=0?a.substring(0,d+1):P}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=m.createElement(ab);b.src=a+bb;a=e(b.src)}return a}
function g(){var a=F(cb);if(a!=null){return a}return P}
function h(){var a=m.getElementsByTagName(db);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(eb)!=-1){return e(a[b].src)}}return P}
function i(){var a;if(typeof isBodyLoaded==fb||!isBodyLoaded()){var b=gb;var c;m.write(hb+b+ib);c=m.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=jb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return P}
function j(){var a=m.getElementsByTagName(kb);if(a.length>0){return a[a.length-1].href}return P}
var k=g();if(k==P){k=h()}if(k==P){k=i()}if(k==P){k=j()}if(k==P){k=e(m.location.href)}k=f(k);s=k;return k}
function D(){var b=document.getElementsByTagName(lb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(mb),g;if(f){f=f.replace(nb,P);if(f.indexOf(ob)>=0){continue}if(f==pb){g=e.getAttribute(qb);if(g){var h,i=g.indexOf(rb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=P}t[f]=h}}else if(f==sb){g=e.getAttribute(qb);if(g){try{z=eval(g)}catch(a){alert(tb+g+ub)}}}else if(f==vb){g=e.getAttribute(qb);if(g){try{y=eval(g)}catch(a){alert(tb+g+wb)}}}}}}
function E(a,b){return b in u[a]}
function F(a){var b=t[a];return b==null?null:b}
function G(a,b){var c=w;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function H(a){var b=v[a](),c=u[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(z){z(a,d,b)}throw null}
var I;function J(){if(!I){I=true;var a=m.createElement(xb);a.src=yb;a.id=Q;a.style.cssText=zb;a.tabIndex=-1;m.body.appendChild(a);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Ab});a.contentWindow.location.replace(s+L)}}
v[Bb]=function(){var b=null;var c=Cb;try{if(!b){var d=location.search;var e=d.indexOf(Db);if(e>=0){var f=d.substring(e+7);var g=d.indexOf(Eb,e);if(g<0){g=d.length}b=d.substring(e+7,g)}}if(!b){var h=m.cookie;var i=h.indexOf(Fb);if(i>=0){var g=h.indexOf(Gb,i);if(g<0){g=h.length}b=h.substring(i+16,g)}}if(!b){b=F(Bb)}if(!b){b=l[Hb]}if(b){c=b}while(b&&!E(Bb,b)){var j=b.lastIndexOf(Ib);if(j<0){b=null;break}b=b.substring(0,j)}}catch(a){alert(Jb+a)}l[Hb]=c;return b||Cb};u[Bb]={ar:0,'default':1,en:2,fr:3,zh:4};v[Kb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(b.indexOf(Lb)!=-1){return Lb}else if(b.indexOf(Mb)!=-1){return Nb}else if(b.indexOf(Ob)!=-1){if(document.documentMode>=8){return Pb}else{var d=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(d&&d.length==3){var e=c(d);if(e>=6000){return Qb}}}}else if(b.indexOf(Rb)!=-1){return Sb}return Tb};u[Kb]={gecko1_8:0,ie6:1,ie8:2,opera:3,safari:4};showcase.onScriptLoad=function(){if(I){q=true;B()}};showcase.onInjectionDone=function(){p=true;n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:Ub,millis:(new Date).getTime(),type:Y});B()};D();C();var K;var L;if(A()){if(l.external&&(l.external.initModule&&l.external.initModule(Q))){l.location.reload();return}L=Vb;K=P}n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Wb});if(!A()){try{G([Xb,Nb],Yb);G([Cb,Lb],Zb);G([Xb,Sb],$b);G([_b,Pb],ac);G([bc,Qb],cc);G([bc,Nb],dc);G([ec,Pb],fc);G([ec,Qb],gc);G([Xb,Pb],hc);G([Cb,Pb],ic);G([ec,Nb],jc);G([Cb,Nb],kc);G([bc,Pb],lc);G([_b,Qb],mc);G([ec,Lb],nc);G([bc,Sb],oc);G([_b,Sb],pc);G([_b,Nb],qc);G([_b,Lb],rc);G([Cb,Sb],sc);G([Cb,Qb],tc);G([bc,Lb],uc);G([Xb,Qb],vc);G([Xb,Lb],wc);G([ec,Sb],xc);K=w[H(Bb)][H(Kb)];var M=K.indexOf(yc);if(M!=-1){x=Number(K.substring(M+1));K=K.substring(0,M)}L=K+zc}catch(a){return}}var N;function O(){if(!r){r=true;B();if(m.removeEventListener){m.removeEventListener(Ac,O,false)}if(N){clearInterval(N)}}}
if(m.addEventListener){m.addEventListener(Ac,function(){J();O()},false)}var N=setInterval(function(){if(/loaded|complete/.test(m.readyState)){J();O()}},50);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Y});n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:Ub,millis:(new Date).getTime(),type:T});m.write(Bc)}
showcase();