function Rwb(){}
function Lwb(){}
function g5b(){}
function l5b(){}
function q5b(){}
function i5b(b){this.b=b}
function n5b(b){this.b=b}
function s5b(b){this.b=b}
function y5b(b){VOb(b.c,_4b(b.b))}
function Qwb(){var b;while(Mwb){b=Mwb;Mwb=Mwb.c;!Mwb&&(Nwb=null);y5b(b.b)}}
function a5b(b,c){if(c==null){Qv(b.d.N,EVd,false)}else{WGc(b.d.b,c,false);Qv(b.d.rb(),EVd,true)}}
function Twb(){Owb=new Rwb;EC((BC(),AC),14);!!$stats&&$stats(vD(sWd,Aqd,-1,-1));Owb.Bd();!!$stats&&$stats(vD(sWd,zNd,-1,-1))}
function UQb(b){var c,d;c=sab(b.b.Yc(tWd),54);if(c==null){d=dab(ltb,{19:1,54:1},1,[uWd,vWd,wWd,xWd,yWd]);b.b.$c(tWd,d);return d}else{return c}}
function b5b(c){var b,e,f,g;f=fG(c.g.N,ePd);if(Iad(f,qqd)){WGc(c.d.b,FVd,false)}else{try{g=k9c(f);e=GZ(c.b,g);WGc(c.d.b,e,false);a5b(c,null)}catch(b){b=ytb(b);if(wab(b,55)){a5b(c,GVd)}else throw b}}}
function c5b(c){var b,e;switch(c.f.N.selectedIndex){case 0:c.b=(AZ(),!vZ&&(vZ=new SZ(yZ.Hc(),IW((SU(),RU)),false)),AZ(),vZ);$Qc(c.e,c.b.v);c.e.N[QOd]=!false;break;case 1:c.b=(AZ(),!uZ&&(uZ=new SZ(yZ.Gc(),IW((SU(),RU)),false)),AZ(),uZ);$Qc(c.e,c.b.v);c.e.N[QOd]=!false;break;case 2:c.b=(AZ(),!xZ&&(xZ=new SZ(yZ.Tc(),IW((SU(),RU)),false)),AZ(),xZ);$Qc(c.e,c.b.v);c.e.N[QOd]=!false;break;case 3:c.b=(AZ(),!wZ&&(wZ=new SZ(yZ.Sc(),IW((SU(),RU)),false)),AZ(),wZ);$Qc(c.e,c.b.v);c.e.N[QOd]=!false;break;case 4:c.e.N[QOd]=!true;e=fG(c.e.N,ePd);try{c.b=(AZ(),new SZ(e,IW((SU(),RU)),true))}catch(b){b=ytb(b);if(wab(b,98)){a5b(c,AWd);return}else throw b}}b5b(c)}
function _4b(b){var c,d,e,f,g,i,j,k,n,o,p;c=new YKc(4,2);c.p[rCd]=5;b.f=new COc;b.f.N.style[yud]=BUd;g=UQb(b.c);for(e=0,f=g.length;e<f;++e){d=g[e];xOc(b.f,d)}Yv(b.f,new i5b(b),(jN(),jN(),iN));c.nf(0,0);i=(j=c.k.b.j.rows[0].cells[0],VJc(c,j,false),j);i.innerHTML=AVd;dKc(c,0,1,b.f);b.e=new lRc;b.e.N.style[yud]=BUd;Yv(b.e,new n5b(b),(iP(),iP(),hP));dKc(c,1,1,b.e);b.g=new lRc;b.g.N.style[yud]=BUd;$Qc(b.g,zWd);Yv(b.g,new s5b(b),hP);c.nf(2,0);k=(n=c.k.b.j.rows[2].cells[0],VJc(c,n,false),n);k.innerHTML=CVd;dKc(c,2,1,b.g);b.d=new AGc;b.d.N.style[yud]=BUd;c.nf(3,0);o=(p=c.k.b.j.rows[3].cells[0],VJc(c,p,false),p);o.innerHTML=DVd;dKc(c,3,1,b.d);c5b(b);return c}
var pWd='#,##0%',qWd='#E0',zWd='31415926535.897932',BWd='AsyncLoader14',CWd='CwNumberFormat$1',DWd='CwNumberFormat$2',EWd='CwNumberFormat$3',tWd='cwNumberFormatPatterns',sWd='runCallbacks14',rWd='\xA4#0.00',oWd='\xA4\xA0#,##0.00;\xA4\xA0#,##0.00-',yWd='\u062A\u062E\u0635\u064A\u0635',uWd='\u0639\u0634\u0631\u064A',wWd='\u0639\u0644\u0645\u064A',vWd='\u0639\u0645\u0644\u0629',xWd='\u0646\u0633\u0628\u0629 \u0645\u0624\u0648\u064A\u0629',AWd='\u0646\u0645\u0637 \u063A\u064A\u0631 \u0635\u0627\u0644\u062D';var uZ=null,wZ=null,xZ=null;_=h$.prototype;_.Gc=function k$(){return oWd};_.Sc=function x$(){return pWd};_.Tc=function y$(){return qWd};_=A$.prototype;_.Gc=function D$(){return oWd};_.Sc=function Q$(){return pWd};_.Tc=function R$(){return qWd};_=T$.prototype;_.Gc=function W$(){return oWd};_.Sc=function h_(){return pWd};_.Tc=function i_(){return qWd};_=k_.prototype;_.Gc=function n_(){return oWd};_.Sc=function A_(){return pWd};_.Tc=function B_(){return qWd};_=D_.prototype;_.Gc=function G_(){return oWd};_.Sc=function T_(){return pWd};_.Tc=function U_(){return qWd};_=W_.prototype;_.Gc=function Z_(){return oWd};_.Sc=function k0(){return pWd};_.Tc=function l0(){return qWd};_=n0.prototype;_.Gc=function q0(){return oWd};_.Sc=function D0(){return pWd};_.Tc=function E0(){return qWd};_=G0.prototype;_.Gc=function J0(){return oWd};_.Sc=function W0(){return pWd};_.Tc=function X0(){return qWd};_=Z0.prototype;_.Gc=function a1(){return oWd};_.Sc=function n1(){return pWd};_.Tc=function o1(){return qWd};_=q1.prototype;_.Gc=function t1(){return oWd};_.Sc=function G1(){return pWd};_.Tc=function H1(){return qWd};_=J1.prototype;_.Gc=function M1(){return oWd};_.Sc=function Z1(){return pWd};_.Tc=function $1(){return qWd};_=a2.prototype;_.Gc=function d2(){return rWd};_.Sc=function q2(){return pWd};_.Tc=function r2(){return qWd};_=t2.prototype;_.Gc=function w2(){return rWd};_.Sc=function J2(){return pWd};_.Tc=function K2(){return qWd};_=M2.prototype;_.Gc=function P2(){return oWd};_.Sc=function a3(){return pWd};_.Tc=function b3(){return qWd};_=d3.prototype;_.Gc=function g3(){return rWd};_.Sc=function t3(){return pWd};_.Tc=function u3(){return qWd};_=w3.prototype;_.Gc=function z3(){return rWd};_.Sc=function M3(){return pWd};_.Tc=function N3(){return qWd};_=P3.prototype;_.Gc=function S3(){return rWd};_.Sc=function d4(){return pWd};_.Tc=function e4(){return qWd};_=Rwb.prototype=Lwb.prototype=new Zr;_.gC=function Swb(){return Ueb};_.Bd=function Wwb(){Qwb()};_.cM={};_=i5b.prototype=g5b.prototype=new Zr;_.gC=function j5b(){return Qjb};_.fc=function k5b(b){c5b(this.b)};_.cM={26:1,47:1};_.b=null;_=n5b.prototype=l5b.prototype=new Zr;_.gC=function o5b(){return Rjb};_.ic=function p5b(b){c5b(this.b)};_.cM={32:1,47:1};_.b=null;_=s5b.prototype=q5b.prototype=new Zr;_.gC=function t5b(){return Sjb};_.ic=function u5b(b){b5b(this.b)};_.cM={32:1,47:1};_.b=null;var Ueb=V8c(aGd,BWd),Qjb=V8c(sId,CWd),Rjb=V8c(sId,DWd),Sjb=V8c(sId,EWd);$entry(Twb)();