function ayb(){}
function Wxb(){}
function l7b(){}
function q7b(){}
function v7b(){}
function n7b(b){this.b=b}
function s7b(b){this.b=b}
function x7b(b){this.b=b}
function D7b(b){SQb(b.c,e7b(b.b))}
function _xb(){var b;while(Xxb){b=Xxb;Xxb=Xxb.c;!Xxb&&(Yxb=null);D7b(b.b)}}
function f7b(b,c){if(c==null){_v(b.d.N,S$d,false)}else{dKc(b.d.b,c,false);_v(b.d.tb(),S$d,true)}}
function cyb(){Zxb=new ayb;PC((MC(),LC),14);!!$stats&&$stats(GD(G_d,Qud,-1,-1));Zxb.Fd();!!$stats&&$stats(GD(G_d,$Sd,-1,-1))}
function RSb(b){var c,d;c=qbb(b.b.ad(H_d),54);if(c==null){d=bbb(wub,{19:1,54:1},1,[I_d,J_d,K_d,L_d,M_d]);b.b.cd(H_d,d);return d}else{return c}}
function g7b(c){var b,e,f,g;f=kG(c.g.N,DUd);if(Xed(f,Gud)){dKc(c.d.b,T$d,false)}else{try{g=zdd(f);e=E$(c.b,g);dKc(c.d.b,e,false);f7b(c,null)}catch(b){b=Jub(b);if(ubb(b,55)){f7b(c,U$d)}else throw b}}}
function h7b(c){var b,e;switch(c.f.N.selectedIndex){case 0:c.b=(y$(),!t$&&(t$=new Q$(w$.Lc(),GX((QV(),PV)),false)),y$(),t$);tUc(c.e,c.b.v);c.e.N[nUd]=!false;break;case 1:c.b=(y$(),!s$&&(s$=new Q$(w$.Kc(),GX((QV(),PV)),false)),y$(),s$);tUc(c.e,c.b.v);c.e.N[nUd]=!false;break;case 2:c.b=(y$(),!v$&&(v$=new Q$(w$.Xc(),GX((QV(),PV)),false)),y$(),v$);tUc(c.e,c.b.v);c.e.N[nUd]=!false;break;case 3:c.b=(y$(),!u$&&(u$=new Q$(w$.Wc(),GX((QV(),PV)),false)),y$(),u$);tUc(c.e,c.b.v);c.e.N[nUd]=!false;break;case 4:c.e.N[nUd]=!true;e=kG(c.e.N,DUd);try{c.b=(y$(),new Q$(e,GX((QV(),PV)),true))}catch(b){b=Jub(b);if(ubb(b,99)){f7b(c,O_d);return}else throw b}}g7b(c)}
function e7b(b){var c,d,e,f,g,i,j,k,n,o,p;c=new ZNc(4,2);c.p[gHd]=5;b.f=new WRc;b.f.N.style[Kyd]=PZd;g=RSb(b.c);for(e=0,f=g.length;e<f;++e){d=g[e];RRc(b.f,d)}hw(b.f,new n7b(b),(hO(),hO(),gO));c.xf(0,0);i=(j=c.k.b.j.rows[0].cells[0],WMc(c,j,false),j);i.innerHTML=O$d;eNc(c,0,1,b.f);b.e=new GUc;b.e.N.style[Kyd]=PZd;hw(b.e,new s7b(b),(gQ(),gQ(),fQ));eNc(c,1,1,b.e);b.g=new GUc;b.g.N.style[Kyd]=PZd;tUc(b.g,N_d);hw(b.g,new x7b(b),fQ);c.xf(2,0);k=(n=c.k.b.j.rows[2].cells[0],WMc(c,n,false),n);k.innerHTML=Q$d;eNc(c,2,1,b.g);b.d=new JJc;b.d.N.style[Kyd]=PZd;c.xf(3,0);o=(p=c.k.b.j.rows[3].cells[0],WMc(c,p,false),p);o.innerHTML=R$d;eNc(c,3,1,b.d);h7b(b);return c}
var D_d='#,##0%',E_d='#E0',N_d='31415926535.897932',P_d='AsyncLoader14',Q_d='CwNumberFormat$1',R_d='CwNumberFormat$2',S_d='CwNumberFormat$3',H_d='cwNumberFormatPatterns',G_d='runCallbacks14',F_d='\xA4#0.00',C_d='\xA4\xA0#,##0.00;\xA4\xA0#,##0.00-',M_d='\u062A\u062E\u0635\u064A\u0635',I_d='\u0639\u0634\u0631\u064A',K_d='\u0639\u0644\u0645\u064A',J_d='\u0639\u0645\u0644\u0629',L_d='\u0646\u0633\u0628\u0629 \u0645\u0624\u0648\u064A\u0629',O_d='\u0646\u0645\u0637 \u063A\u064A\u0631 \u0635\u0627\u0644\u062D';var s$=null,u$=null,v$=null;_=f_.prototype;_.Kc=function i_(){return C_d};_.Wc=function v_(){return D_d};_.Xc=function w_(){return E_d};_=y_.prototype;_.Kc=function B_(){return C_d};_.Wc=function O_(){return D_d};_.Xc=function P_(){return E_d};_=R_.prototype;_.Kc=function U_(){return C_d};_.Wc=function f0(){return D_d};_.Xc=function g0(){return E_d};_=i0.prototype;_.Kc=function l0(){return C_d};_.Wc=function y0(){return D_d};_.Xc=function z0(){return E_d};_=B0.prototype;_.Kc=function E0(){return C_d};_.Wc=function R0(){return D_d};_.Xc=function S0(){return E_d};_=U0.prototype;_.Kc=function X0(){return C_d};_.Wc=function i1(){return D_d};_.Xc=function j1(){return E_d};_=l1.prototype;_.Kc=function o1(){return C_d};_.Wc=function B1(){return D_d};_.Xc=function C1(){return E_d};_=E1.prototype;_.Kc=function H1(){return C_d};_.Wc=function U1(){return D_d};_.Xc=function V1(){return E_d};_=X1.prototype;_.Kc=function $1(){return C_d};_.Wc=function l2(){return D_d};_.Xc=function m2(){return E_d};_=o2.prototype;_.Kc=function r2(){return C_d};_.Wc=function E2(){return D_d};_.Xc=function F2(){return E_d};_=H2.prototype;_.Kc=function K2(){return C_d};_.Wc=function X2(){return D_d};_.Xc=function Y2(){return E_d};_=$2.prototype;_.Kc=function b3(){return F_d};_.Wc=function o3(){return D_d};_.Xc=function p3(){return E_d};_=r3.prototype;_.Kc=function u3(){return F_d};_.Wc=function H3(){return D_d};_.Xc=function I3(){return E_d};_=K3.prototype;_.Kc=function N3(){return C_d};_.Wc=function $3(){return D_d};_.Xc=function _3(){return E_d};_=b4.prototype;_.Kc=function e4(){return F_d};_.Wc=function r4(){return D_d};_.Xc=function s4(){return E_d};_=u4.prototype;_.Kc=function x4(){return F_d};_.Wc=function K4(){return D_d};_.Xc=function L4(){return E_d};_=N4.prototype;_.Kc=function Q4(){return F_d};_.Wc=function b5(){return D_d};_.Xc=function c5(){return E_d};_=ayb.prototype=Wxb.prototype=new is;_.gC=function byb(){return Qfb};_.Fd=function fyb(){_xb()};_.cM={};_=n7b.prototype=l7b.prototype=new is;_.gC=function o7b(){return Qkb};_.jc=function p7b(b){h7b(this.b)};_.cM={26:1,47:1};_.b=null;_=s7b.prototype=q7b.prototype=new is;_.gC=function t7b(){return Rkb};_.mc=function u7b(b){h7b(this.b)};_.cM={32:1,47:1};_.b=null;_=x7b.prototype=v7b.prototype=new is;_.gC=function y7b(){return Skb};_.mc=function z7b(b){g7b(this.b)};_.cM={32:1,47:1};_.b=null;var Qfb=idd(qLd,P_d),Qkb=idd(ONd,Q_d),Rkb=idd(ONd,R_d),Skb=idd(ONd,S_d);$entry(cyb)();