function X9(){}
function bab(){}
function VHb(){}
function PHb(){}
function pgc(){}
function ugc(){}
function kUc(){}
function aab(){aab=psd;_9=new bab}
function rgc(b,c){this.c=b;this.b=c}
function wgc(b,c){this.c=b;this.b=c}
function ggc(b,c){dKc(c.b,Rae+b.Df()+Nwd+b.Ef(),false)}
function XHb(){SHb=new VHb;PC((MC(),LC),38);!!$stats&&$stats(GD(Pae,Qud,-1,-1));SHb.Fd();!!$stats&&$stats(GD(Pae,$Sd,-1,-1))}
function b5c(c){try{var d=c.document.selection.createRange();if(d.parentElement()!==c)return 0;return d.text.length}catch(b){return 0}}
function a5c(c){try{var d=c.document.selection.createRange();if(d.parentElement()!==c)return -1;return -d.move(Uae,-65535)}catch(b){return 0}}
function KUc(){var b;BUc();uUc.call(this,(b=$doc.createElement(LGd),b.type=Sae,b),(!Fjc&&(Fjc=new Hjc),!Ajc&&(Ajc=new Cjc)));this.N[sud]=Tae}
function egc(b,c){var d,e,f,i;d=new APc;d.f[gHd]=4;f=vPc(d);d.c.appendChild(f);rw(b);S2c(d.j,b);f.appendChild(b.N);tw(b,d);if(c){e=new KJc(Qae);hw(b,new rgc(b,e),(gQ(),gQ(),fQ));hw(b,new wgc(b,e),(AO(),AO(),zO));i=vPc(d);d.c.appendChild(i);rw(e);S2c(d.j,e);i.appendChild(e.N);tw(e,d)}return d}
function d5c(c){try{var d=c.document.selection.createRange();if(d.parentElement()!==c)return 0;var e=d.text.length;var f=0;var g=d.duplicate();g.moveEnd(Uae,-1);var i=g.text.length;while(i==e&&g.parentElement()==c&&d.compareEndPoints(Wae,g)<=0){f+=2;g.moveEnd(Uae,-1);i=g.text.length}return e+f}catch(b){return 0}}
function c5c(c){try{var d=c.document.selection.createRange();if(d.parentElement()!==c)return -1;var e=d.duplicate();e.moveToElementText(c);e.setEndPoint(Vae,d);var f=e.text.length;var g=0;var i=e.duplicate();i.moveEnd(Uae,-1);var j=i.text.length;while(j==f&&i.parentElement()==c){g+=2;i.moveEnd(Uae,-1);j=i.text.length}return f+g}catch(b){return 0}}
function UHb(){var b,c,d,e,f,g,i;while(QHb){b=QHb;QHb=QHb.c;!QHb&&(RHb=null);SQb(b.b.b,(i=new R1c,i.f[gHd]=5,f=new GUc,e1c(f.N,Gud,Gae),sV(f.b,(aab(),aab(),_9)),d=new GUc,e1c(d.N,Gud,Hae),d.N[DUd]=Iae,rV(d.b),d.N[nUd]=true,N1c(i,new SJc(Jae)),N1c(i,egc(f,true)),N1c(i,egc(d,false)),e=new KUc,e1c(e.N,Gud,Kae),c=new KUc,e1c(c.N,Gud,Lae),c.N[DUd]=Iae,rV(c.b),c.N[nUd]=true,N1c(i,new SJc(Mae)),N1c(i,egc(e,true)),N1c(i,egc(c,false)),g=new V$c,e1c(g.N,Gud,Nae),g.N.rows=5,N1c(i,new SJc(Oae)),N1c(i,egc(g,true)),i))}}
var Jae='<b>\u0645\u0631\u0628\u0639 \u0646\u0635 \u0639\u0627\u062F\u064A:<\/b>',Mae='<br><br><b>\u0645\u0631\u0628\u0639 \u0646\u0635 \u0643\u0644\u0645\u0629 \u0627\u0644\u0633\u0631:<\/b>',Oae='<br><br><b>\u0645\u0646\u0637\u0642\u0629 \u0627\u0644\u0646\u0635:<\/b>',Xae='AnyRtlDirectionEstimator',Yae='AsyncLoader38',Zae='CwBasicText$2',$ae='CwBasicText$3',Vae='EndToStart',_ae='PasswordTextBox',Wae='StartToEnd',Uae='character',Kae='cwBasicText-password',Lae='cwBasicText-password-disabled',Nae='cwBasicText-textarea',Gae='cwBasicText-textbox',Hae='cwBasicText-textbox-disabled',Tae='gwt-PasswordTextBox',Sae='password',Pae='runCallbacks38',Iae='\u0642\u0631\u0627\u0621\u0629 \u0641\u0642\u0637',Rae='\u0645\u062E\u062A\u0627\u0631\u0629: ',Qae='\u0645\u062E\u062A\u0627\u0631\u0629: 0, 0';_=bab.prototype=X9.prototype=new Y9;_.Ed=function cab(b){return sab.test((Bab(),b))?(e$(),d$):(e$(),c$)};_.gC=function dab(){return vfb};_.cM={};var _9;_=VHb.prototype=PHb.prototype=new is;_.gC=function WHb(){return khb};_.Fd=function $Hb(){UHb()};_.cM={};_=rgc.prototype=pgc.prototype=new is;_.gC=function sgc(){return mmb};_.mc=function tgc(b){ggc(this.c,this.b)};_.cM={32:1,47:1};_.b=null;_.c=null;_=wgc.prototype=ugc.prototype=new is;_.gC=function xgc(){return nmb};_.kc=function ygc(b){ggc(this.c,this.b)};_.cM={27:1,47:1};_.b=null;_.c=null;_=nUc.prototype;_.Df=function wUc(){return a5c(this.N)};_.Ef=function xUc(){return b5c(this.N)};_=KUc.prototype=kUc.prototype=new lUc;_.gC=function LUc(){return hqb};_.cM={14:1,15:1,17:1,18:1,74:1,76:1};_=T$c.prototype;_.Df=function X$c(){return c5c(this.N)};_.Ef=function Y$c(){return d5c(this.N)};var vfb=idd(lLd,Xae),khb=idd(qLd,Yae),mmb=idd(_Od,Zae),nmb=idd(_Od,$ae),hqb=idd($Id,_ae);$entry(XHb)();