function lsb(){}
function fsb(){}
function K0b(){}
function P0b(){}
function U0b(){}
function M0b(b){this.b=b}
function R0b(b){this.b=b}
function W0b(b){this.b=b}
function a1b(b){xKb(b.c,D0b(b.b))}
function ksb(){var b;while(gsb){b=gsb;gsb=gsb.c;!gsb&&(hsb=null);a1b(b.b)}}
function E0b(b,c){if(c==null){wv(b.d.N,SSd,false)}else{SCc(b.d.b,c,false);wv(b.d.rb(),SSd,true)}}
function nsb(){isb=new lsb;jC((gC(),fC),14);!!$stats&&$stats(aD(JTd,cnd,-1,-1));isb.Od();!!$stats&&$stats(aD(JTd,QKd,-1,-1))}
function wMb(b){var c,d;c=g6(b.b.dd(KTd),54);if(c==null){d=T5(Hob,{19:1,54:1},1,[LTd,MTd,NTd,OTd,PTd]);b.b.fd(KTd,d);return d}else{return c}}
function F0b(c){var b,e,f,g;f=FF(c.g.N,tMd);if(j7c(f,Umd)){SCc(c.d.b,TSd,false)}else{try{g=N5c(f);e=hZ(c.b,g);SCc(c.d.b,e,false);E0b(c,null)}catch(b){b=Uob(b);if(k6(b,55)){E0b(c,USd)}else throw b}}}
function G0b(c){var b,e;switch(c.f.N.selectedIndex){case 0:c.b=(bZ(),!YY&&(YY=new tZ(_Y.Oc(),fW((TU(),SU)),false)),bZ(),YY);_Mc(c.e,c.b.v);c.e.N[dMd]=!false;break;case 1:c.b=(bZ(),!XY&&(XY=new tZ(_Y.Nc(),fW((TU(),SU)),false)),bZ(),XY);_Mc(c.e,c.b.v);c.e.N[dMd]=!false;break;case 2:c.b=(bZ(),!$Y&&($Y=new tZ(_Y.$c(),fW((TU(),SU)),false)),bZ(),$Y);_Mc(c.e,c.b.v);c.e.N[dMd]=!false;break;case 3:c.b=(bZ(),!ZY&&(ZY=new tZ(_Y.Zc(),fW((TU(),SU)),false)),bZ(),ZY);_Mc(c.e,c.b.v);c.e.N[dMd]=!false;break;case 4:c.e.N[dMd]=!true;e=FF(c.e.N,tMd);try{c.b=(bZ(),new tZ(e,fW((TU(),SU)),true))}catch(b){b=Uob(b);if(k6(b,98)){E0b(c,VSd);return}else throw b}}F0b(c)}
function D0b(b){var c,d,e,f,g,i,j,k,n,o,p;c=new LGc(4,2);c.p[Bzd]=5;b.f=new DKc;b.f.N.style[$qd]=PRd;g=wMb(b.c);for(e=0,f=g.length;e<f;++e){d=g[e];yKc(b.f,d)}Ev(b.f,new M0b(b),(kN(),kN(),jN));c.Af(0,0);i=(j=c.k.b.j.rows[0].cells[0],IFc(c,j,false),j);i.innerHTML=QTd;SFc(c,0,1,b.f);b.e=new mNc;b.e.N.style[$qd]=PRd;Ev(b.e,new R0b(b),(jP(),jP(),iP));SFc(c,1,1,b.e);b.g=new mNc;b.g.N.style[$qd]=PRd;_Mc(b.g,RTd);Ev(b.g,new W0b(b),iP);c.Af(2,0);k=(n=c.k.b.j.rows[2].cells[0],IFc(c,n,false),n);k.innerHTML=STd;SFc(c,2,1,b.g);b.d=new wCc;b.d.N.style[$qd]=PRd;c.Af(3,0);o=(p=c.k.b.j.rows[3].cells[0],IFc(c,p,false),p);o.innerHTML=TTd;SFc(c,3,1,b.d);G0b(b);return c}
var GTd='#,##0%',HTd='#E0',RTd='31415926535.897932',TTd='<b>\u683C\u5F0F\u5316\u503C\uFF1A<\/b>',QTd='<b>\u6A21\u677F\uFF1A<\/b>',STd='<b>\u9700\u8981\u683C\u5F0F\u7684\u503C\uFF1A<\/b>',UTd='AsyncLoader14',VTd='CwNumberFormat$1',WTd='CwNumberFormat$2',XTd='CwNumberFormat$3',KTd='cwNumberFormatPatterns',JTd='runCallbacks14',FTd='\xA4#,##0.00',ITd='\xA4#,##0.00;(\xA4#,##0.00)',LTd='\u5C0F\u6570',OTd='\u767E\u5206\u6570',NTd='\u79D1\u5B66',PTd='\u81EA\u5B9A\u4E49',MTd='\u8D27\u5E01';var XY=null,ZY=null,$Y=null;_=KZ.prototype;_.Nc=function NZ(){return FTd};_.Zc=function $Z(){return GTd};_.$c=function _Z(){return HTd};_=b$.prototype;_.Nc=function e$(){return FTd};_.Zc=function r$(){return GTd};_.$c=function s$(){return HTd};_=u$.prototype;_.Nc=function x$(){return FTd};_.Zc=function K$(){return GTd};_.$c=function L$(){return HTd};_=N$.prototype;_.Nc=function Q$(){return ITd};_.Zc=function b_(){return GTd};_.$c=function c_(){return HTd};_=e_.prototype;_.Nc=function h_(){return FTd};_.Zc=function u_(){return GTd};_.$c=function v_(){return HTd};_=x_.prototype;_.Nc=function A_(){return FTd};_.Zc=function N_(){return GTd};_.$c=function O_(){return HTd};_=lsb.prototype=fsb.prototype=new Fr;_.gC=function msb(){return hab};_.Od=function qsb(){ksb()};_.cM={};_=M0b.prototype=K0b.prototype=new Fr;_.gC=function N0b(){return efb};_.gc=function O0b(b){G0b(this.b)};_.cM={26:1,47:1};_.b=null;_=R0b.prototype=P0b.prototype=new Fr;_.gC=function S0b(){return ffb};_.jc=function T0b(b){G0b(this.b)};_.cM={32:1,47:1};_.b=null;_=W0b.prototype=U0b.prototype=new Fr;_.gC=function X0b(){return gfb};_.jc=function Y0b(b){F0b(this.b)};_.cM={32:1,47:1};_.b=null;var hab=w5c(mDd,UTd),efb=w5c(FFd,VTd),ffb=w5c(FFd,WTd),gfb=w5c(FFd,XTd);$entry(nsb)();