function bvb(){}
function Xub(){}
function NBc(){}
function jCc(){}
function hCc(){}
function lCc(){}
function sCc(){}
function qCc(){}
function bCc(b){if(b==RBc){return true}PX();return b==UBc}
function cCc(b){if(b==QBc){return true}PX();return b==PBc}
function oCc(b){this.c=(VEc(),QEc).b;this.e=(jFc(),iFc).b;this.b=b}
function dCc(){VBc();yvc.call(this);this.c=(VEc(),QEc);this.d=(jFc(),iFc);this.f[pvd]=0;this.f[qvd]=0}
function $Bc(b,c){var d;d=X3(b.L,116);d.c=c.b;!!d.d&&(d.d[nvd]=c.b,undefined)}
function _Bc(b,c){var d;d=X3(b.L,116);d.e=c.b;!!d.d&&(d.d.style[ovd]=c.b,undefined)}
function VBc(){VBc=ahd;OBc=new jCc;RBc=new jCc;QBc=new jCc;PBc=new jCc;SBc=new jCc;TBc=new jCc;UBc=new jCc}
function dvb(){$ub=new bvb;aC((ZB(),YB),27);!!$stats&&$stats(TC(MXd,Ajd,-1,-1));$ub.Bd();!!$stats&&$stats(TC(MXd,xGd,-1,-1))}
function XBc(b,c,d){var e;if(d==OBc){if(c==b.b){return}else if(b.b){throw new v2c(NXd)}}Ev(c);cUc(b.j,c);d==OBc&&(b.b=c);e=new oCc(d);c.L=e;$Bc(c,b.c);_Bc(c,b.d);ZBc(b);Gv(c,b)}
function YBc(b,c){var d,e,f,g,i,j,k,n;GSc(b.N,qjd,c);j=new pdd;k=new sUc(b.j);while(k.b<k.c.d-1){d=qUc(k);i=X3(d.L,116).b;f=X3(j.Zc(i),10);e=!f?1:f.b;g=i==SBc?OXd+e:i==TBc?PXd+e:i==UBc?QXd+e:i==PBc?RXd+e:i==RBc?SXd+e:i==QBc?TXd+e:Vud;GSc((n=d.N.parentNode,(!n||n.nodeType!=1)&&(n=null),n),c,g);j._c(i,V2c(e+1))}}
function avb(){var b,c,d,e;while(Yub){b=Yub;Yub=Yub.c;!Yub&&(Zub=null);WHb(b.b.b,(d=new dCc,d.N[djd]=BXd,d.f[pvd]=4,d.c=(VEc(),PEc),XBc(d,new Kzc(CXd),(VBc(),SBc)),XBc(d,new Kzc(DXd),TBc),XBc(d,new Kzc(EXd),PBc),XBc(d,new Kzc(FXd),UBc),XBc(d,new Kzc(GXd),SBc),XBc(d,new Kzc(HXd),TBc),c=new Kzc(IXd),e=new BNc(c),e.N.style[ynd]=JXd,e.N.style[znd]=KXd,XBc(d,e,OBc),YBc(d,LXd),d))}}
function ZBc(b){var c,d,e,f,g,i,j,k,n,o,p,q,r,s,t,u;c=b.e;while(Qsc(c)>0){c.removeChild(Psc(c,0))}r=1;f=1;for(j=new sUc(b.j);j.b<j.c.d-1;){e=qUc(j);g=X3(e.L,116).b;g==SBc||g==TBc?++r:(g==PBc||g==UBc||g==RBc||g==QBc)&&++f}s=H3(dmb,{19:1},71,r,0);for(i=0;i<r;++i){s[i]=new sCc;s[i].c=$doc.createElement(lvd);c.appendChild(s[i].c)}n=0;o=f-1;p=0;t=r-1;d=null;for(j=new sUc(b.j);j.b<j.c.d-1;){e=qUc(j);k=X3(e.L,116);u=$doc.createElement(mvd);k.d=u;k.d[nvd]=k.c;k.d.style[ovd]=k.e;k.d[ynd]=qjd;k.d[znd]=qjd;if(k.b==SBc){Tsc(s[p].c,u,s[p].b);u.appendChild(e.N);u[$Md]=o-n+1;++p}else if(k.b==TBc){Tsc(s[t].c,u,s[t].b);u.appendChild(e.N);u[$Md]=o-n+1;--t}else if(k.b==OBc){d=u}else if(bCc(k.b)){q=s[p];Tsc(q.c,u,q.b++);u.appendChild(e.N);u[UXd]=t-p+1;++n}else if(cCc(k.b)){q=s[p];Tsc(q.c,u,q.b);u.appendChild(e.N);u[UXd]=t-p+1;--o}}if(b.b){q=s[p];Tsc(q.c,d,q.b);d.appendChild(b.b.N)}}
var KXd='100px',VXd='AsyncLoader27',EXd='Ceci est le composant est',FXd='Ceci est le composant ouest',CXd='Ceci est le premier composant nord',DXd='Ceci est le premier composant sud',GXd='Ceci est le second composant nord',HXd='Ceci est le second composant sud',YXd='DockPanel',ZXd='DockPanel$DockLayoutConstant',$Xd='DockPanel$LayoutData',WXd='DockPanel$TmpRow',XXd='DockPanel$TmpRow;',NXd='Only one CENTER widget may be added',IXd="Voici un <code>panneau de d\xE9filement<\/code> situ\xE9 au centre d'un <code>panneau d'ancrage<\/code>. Si des contenus relativement volumineux sont ins\xE9r\xE9s au milieu de ce panneau \xE0 d\xE9filement et si sa taille est d\xE9finie, il prend la forme d'une zone dot\xE9e d'une fonction de d\xE9filement \xE0 l'int\xE9rieur de la page, sans l'utilisation d'un IFRAME.<br><br>Voici un texte encore plus obscur qui va surtout servir \xE0 faire d\xE9filer cet \xE9l\xE9ment jusqu'en bas de sa zone visible. Sinon, il vous faudra r\xE9duire ce panneau \xE0 une taille minuscule pour pouvoir afficher ces formidables barres de d\xE9filement!",BXd='cw-DockPanel',LXd='cwDockPanel',RXd='east',TXd='lineend',SXd='linestart',OXd='north',MXd='runCallbacks27',PXd='south',QXd='west';_=bvb.prototype=Xub.prototype=new vr;_.gC=function cvb(){return H8};_.Bd=function gvb(){avb()};_.cM={};_=dCc.prototype=NBc.prototype=new svc;_.gC=function eCc(){return ihb};_.sb=function fCc(b){YBc(this,b)};_.Hb=function gCc(b){var c;c=Ztc(this,b);if(c){b==this.b&&(this.b=null);ZBc(this)}return c};_.cM={14:1,15:1,17:1,18:1,73:1,75:1,128:1};_.b=null;var OBc,PBc,QBc,RBc,SBc,TBc,UBc;_=jCc.prototype=hCc.prototype=new vr;_.gC=function kCc(){return fhb};_.cM={};_=oCc.prototype=lCc.prototype=new vr;_.gC=function pCc(){return ghb};_.cM={116:1};_.b=null;_.d=null;_=sCc.prototype=qCc.prototype=new vr;_.gC=function tCc(){return hhb};_.cM={71:1};_.b=0;_.c=null;var H8=V1c($yd,VXd),hhb=V1c(Iwd,WXd),dmb=U1c(pEd,XXd,hhb),ihb=V1c(Iwd,YXd),fhb=V1c(Iwd,ZXd),ghb=V1c(Iwd,$Xd);$entry(dvb)();