function Bxb(){}
function vxb(){}
function S5b(){}
function X5b(){}
function a6b(){}
function c6b(b){this.b=b}
function U5b(b){this.b=b}
function Z5b(b){this.b=b}
function i6b(b){FPb(b.c,L5b(b.b))}
function Axb(){var b;while(wxb){b=wxb;wxb=wxb.c;!wxb&&(xxb=null);i6b(b.b)}}
function M5b(b,c){if(c==null){Xv(b.d.N,UWd,false)}else{JHc(b.d.b,c,false);Xv(b.d.rb(),UWd,true)}}
function Dxb(){yxb=new Bxb;LC((IC(),HC),14);!!$stats&&$stats(CD(IXd,Erd,-1,-1));yxb.Fd();!!$stats&&$stats(CD(IXd,SOd,-1,-1))}
function ERb(b){var c,d;c=Xab(b.b.ad(JXd),54);if(c==null){d=Iab(Xtb,{19:1,54:1},1,[KXd,LXd,MXd,NXd,OXd]);b.b.cd(JXd,d);return d}else{return c}}
function N5b(c){var b,e,f,g;f=DG(c.g.N,vQd);if(Mbd(f,urd)){JHc(c.d.b,VWd,false)}else{try{g=oad(f);e=j$(c.b,g);JHc(c.d.b,e,false);M5b(c,null)}catch(b){b=iub(b);if(_ab(b,55)){M5b(c,WWd)}else throw b}}}
function O5b(c){var b,e;switch(c.f.N.selectedIndex){case 0:c.b=(d$(),!$Z&&($Z=new v$(b$.Lc(),lX((vV(),uV)),false)),d$(),$Z);MRc(c.e,c.b.v);c.e.N[fQd]=!false;break;case 1:c.b=(d$(),!ZZ&&(ZZ=new v$(b$.Kc(),lX((vV(),uV)),false)),d$(),ZZ);MRc(c.e,c.b.v);c.e.N[fQd]=!false;break;case 2:c.b=(d$(),!a$&&(a$=new v$(b$.Xc(),lX((vV(),uV)),false)),d$(),a$);MRc(c.e,c.b.v);c.e.N[fQd]=!false;break;case 3:c.b=(d$(),!_Z&&(_Z=new v$(b$.Wc(),lX((vV(),uV)),false)),d$(),_Z);MRc(c.e,c.b.v);c.e.N[fQd]=!false;break;case 4:c.e.N[fQd]=!true;e=DG(c.e.N,vQd);try{c.b=(d$(),new v$(e,lX((vV(),uV)),true))}catch(b){b=iub(b);if(_ab(b,98)){M5b(c,QXd);return}else throw b}}N5b(c)}
function L5b(b){var c,d,e,f,g,i,j,k,n,o,p;c=new FLc(4,2);c.p[ADd]=5;b.f=new nPc;b.f.N.style[Hvd]=RVd;g=ERb(b.c);for(e=0,f=g.length;e<f;++e){d=g[e];iPc(b.f,d)}dw(b.f,new U5b(b),(ON(),ON(),NN));c.rf(0,0);i=(j=c.k.b.j.rows[0].cells[0],zKc(c,j,false),j);i.innerHTML=QWd;JKc(c,0,1,b.f);b.e=new ZRc;b.e.N.style[Hvd]=RVd;dw(b.e,new Z5b(b),(NP(),NP(),MP));JKc(c,1,1,b.e);b.g=new ZRc;b.g.N.style[Hvd]=RVd;MRc(b.g,PXd);dw(b.g,new c6b(b),MP);c.rf(2,0);k=(n=c.k.b.j.rows[2].cells[0],zKc(c,n,false),n);k.innerHTML=SWd;JKc(c,2,1,b.g);b.d=new nHc;b.d.N.style[Hvd]=RVd;c.rf(3,0);o=(p=c.k.b.j.rows[3].cells[0],zKc(c,p,false),p);o.innerHTML=TWd;JKc(c,3,1,b.d);O5b(b);return c}
var FXd='#,##0%',GXd='#E0',PXd='31415926535.897932',RXd='AsyncLoader14',SXd='CwNumberFormat$1',TXd='CwNumberFormat$2',UXd='CwNumberFormat$3',JXd='cwNumberFormatPatterns',IXd='runCallbacks14',HXd='\xA4#0.00',EXd='\xA4\xA0#,##0.00;\xA4\xA0#,##0.00-',OXd='\u062A\u062E\u0635\u064A\u0635',KXd='\u0639\u0634\u0631\u064A',MXd='\u0639\u0644\u0645\u064A',LXd='\u0639\u0645\u0644\u0629',NXd='\u0646\u0633\u0628\u0629 \u0645\u0624\u0648\u064A\u0629',QXd='\u0646\u0645\u0637 \u063A\u064A\u0631 \u0635\u0627\u0644\u062D';var ZZ=null,_Z=null,a$=null;_=M$.prototype;_.Kc=function P$(){return EXd};_.Wc=function a_(){return FXd};_.Xc=function b_(){return GXd};_=d_.prototype;_.Kc=function g_(){return EXd};_.Wc=function t_(){return FXd};_.Xc=function u_(){return GXd};_=w_.prototype;_.Kc=function z_(){return EXd};_.Wc=function M_(){return FXd};_.Xc=function N_(){return GXd};_=P_.prototype;_.Kc=function S_(){return EXd};_.Wc=function d0(){return FXd};_.Xc=function e0(){return GXd};_=g0.prototype;_.Kc=function j0(){return EXd};_.Wc=function w0(){return FXd};_.Xc=function x0(){return GXd};_=z0.prototype;_.Kc=function C0(){return EXd};_.Wc=function P0(){return FXd};_.Xc=function Q0(){return GXd};_=S0.prototype;_.Kc=function V0(){return EXd};_.Wc=function g1(){return FXd};_.Xc=function h1(){return GXd};_=j1.prototype;_.Kc=function m1(){return EXd};_.Wc=function z1(){return FXd};_.Xc=function A1(){return GXd};_=C1.prototype;_.Kc=function F1(){return EXd};_.Wc=function S1(){return FXd};_.Xc=function T1(){return GXd};_=V1.prototype;_.Kc=function Y1(){return EXd};_.Wc=function j2(){return FXd};_.Xc=function k2(){return GXd};_=m2.prototype;_.Kc=function p2(){return EXd};_.Wc=function C2(){return FXd};_.Xc=function D2(){return GXd};_=F2.prototype;_.Kc=function I2(){return HXd};_.Wc=function V2(){return FXd};_.Xc=function W2(){return GXd};_=Y2.prototype;_.Kc=function _2(){return HXd};_.Wc=function m3(){return FXd};_.Xc=function n3(){return GXd};_=p3.prototype;_.Kc=function s3(){return EXd};_.Wc=function F3(){return FXd};_.Xc=function G3(){return GXd};_=I3.prototype;_.Kc=function L3(){return HXd};_.Wc=function Y3(){return FXd};_.Xc=function Z3(){return GXd};_=_3.prototype;_.Kc=function c4(){return HXd};_.Wc=function p4(){return FXd};_.Xc=function q4(){return GXd};_=s4.prototype;_.Kc=function v4(){return HXd};_.Wc=function I4(){return FXd};_.Xc=function J4(){return GXd};_=Bxb.prototype=vxb.prototype=new es;_.gC=function Cxb(){return Afb};_.Fd=function Gxb(){Axb()};_.cM={};_=U5b.prototype=S5b.prototype=new es;_.gC=function V5b(){return wkb};_.jc=function W5b(b){O5b(this.b)};_.cM={26:1,47:1};_.b=null;_=Z5b.prototype=X5b.prototype=new es;_.gC=function $5b(){return xkb};_.mc=function _5b(b){O5b(this.b)};_.cM={32:1,47:1};_.b=null;_=c6b.prototype=a6b.prototype=new es;_.gC=function d6b(){return ykb};_.mc=function e6b(b){N5b(this.b)};_.cM={32:1,47:1};_.b=null;var Afb=Z9c(oHd,RXd),wkb=Z9c(GJd,SXd),xkb=Z9c(GJd,TXd),ykb=Z9c(GJd,UXd);$entry(Dxb)();