function Lrb(){}
function Frb(){}
function a0b(){}
function f0b(){}
function k0b(){}
function c0b(b){this.b=b}
function h0b(b){this.b=b}
function m0b(b){this.b=b}
function s0b(b){PJb(b.c,V_b(b.b))}
function Krb(){var b;while(Grb){b=Grb;Grb=Grb.c;!Grb&&(Hrb=null);s0b(b.b)}}
function W_b(b,c){if(c==null){rv(b.d.N,GQd,false)}else{SBc(b.d.b,c,false);rv(b.d.rb(),GQd,true)}}
function Nrb(){Irb=new Lrb;fC((cC(),bC),14);!!$stats&&$stats(YC(xRd,Cld,-1,-1));Irb.Nd();!!$stats&&$stats(YC(xRd,CId,-1,-1))}
function OLb(b){var c,d;c=L5(b.b.cd(yRd),54);if(c==null){d=w5(fob,{19:1,54:1},1,[zRd,ARd,BRd,CRd,DRd]);b.b.ed(yRd,d);return d}else{return c}}
function X_b(c){var b,e,f,g;f=GF(c.g.N,hKd);if(K5c(f,sld)){SBc(c.d.b,HQd,false)}else{try{g=m4c(f);e=MY(c.b,g);SBc(c.d.b,e,false);W_b(c,null)}catch(b){b=sob(b);if(P5(b,55)){W_b(c,IQd)}else throw b}}}
function Y_b(c){var b,e;switch(c.f.N.selectedIndex){case 0:c.b=(GY(),!BY&&(BY=new YY(EY.Nc(),KV((wU(),vU)),false)),GY(),BY);NLc(c.e,c.b.v);c.e.N[TJd]=!false;break;case 1:c.b=(GY(),!AY&&(AY=new YY(EY.Mc(),KV((wU(),vU)),false)),GY(),AY);NLc(c.e,c.b.v);c.e.N[TJd]=!false;break;case 2:c.b=(GY(),!DY&&(DY=new YY(EY.Zc(),KV((wU(),vU)),false)),GY(),DY);NLc(c.e,c.b.v);c.e.N[TJd]=!false;break;case 3:c.b=(GY(),!CY&&(CY=new YY(EY.Yc(),KV((wU(),vU)),false)),GY(),CY);NLc(c.e,c.b.v);c.e.N[TJd]=!false;break;case 4:c.e.N[TJd]=!true;e=GF(c.e.N,hKd);try{c.b=(GY(),new YY(e,KV((wU(),vU)),true))}catch(b){b=sob(b);if(P5(b,98)){W_b(c,JQd);return}else throw b}}X_b(c)}
function V_b(b){var c,d,e,f,g,i,j,k,n,o,p;c=new LFc(4,2);c.p[txd]=5;b.f=new pJc;b.f.N.style[zpd]=DPd;g=OLb(b.c);for(e=0,f=g.length;e<f;++e){d=g[e];kJc(b.f,d)}zv(b.f,new c0b(b),(PM(),PM(),OM));c.zf(0,0);i=(j=c.k.b.j.rows[0].cells[0],IEc(c,j,false),j);i.innerHTML=ERd;SEc(c,0,1,b.f);b.e=new $Lc;b.e.N.style[zpd]=DPd;zv(b.e,new h0b(b),(OO(),OO(),NO));SEc(c,1,1,b.e);b.g=new $Lc;b.g.N.style[zpd]=DPd;NLc(b.g,FRd);zv(b.g,new m0b(b),NO);c.zf(2,0);k=(n=c.k.b.j.rows[2].cells[0],IEc(c,n,false),n);k.innerHTML=GRd;SEc(c,2,1,b.g);b.d=new wBc;b.d.N.style[zpd]=DPd;c.zf(3,0);o=(p=c.k.b.j.rows[3].cells[0],IEc(c,p,false),p);o.innerHTML=HRd;SEc(c,3,1,b.d);Y_b(b);return c}
var uRd='#,##0%',vRd='#E0',FRd='31415926535.897932',HRd='<b>\u683C\u5F0F\u5316\u503C\uFF1A<\/b>',ERd='<b>\u6A21\u677F\uFF1A<\/b>',GRd='<b>\u9700\u8981\u683C\u5F0F\u7684\u503C\uFF1A<\/b>',IRd='AsyncLoader14',JRd='CwNumberFormat$1',KRd='CwNumberFormat$2',LRd='CwNumberFormat$3',yRd='cwNumberFormatPatterns',xRd='runCallbacks14',tRd='\xA4#,##0.00',wRd='\xA4#,##0.00;(\xA4#,##0.00)',zRd='\u5C0F\u6570',CRd='\u767E\u5206\u6570',BRd='\u79D1\u5B66',DRd='\u81EA\u5B9A\u4E49',ARd='\u8D27\u5E01';var AY=null,CY=null,DY=null;_=nZ.prototype;_.Mc=function qZ(){return tRd};_.Yc=function DZ(){return uRd};_.Zc=function EZ(){return vRd};_=GZ.prototype;_.Mc=function JZ(){return tRd};_.Yc=function WZ(){return uRd};_.Zc=function XZ(){return vRd};_=ZZ.prototype;_.Mc=function a$(){return tRd};_.Yc=function n$(){return uRd};_.Zc=function o$(){return vRd};_=q$.prototype;_.Mc=function t$(){return wRd};_.Yc=function G$(){return uRd};_.Zc=function H$(){return vRd};_=J$.prototype;_.Mc=function M$(){return tRd};_.Yc=function Z$(){return uRd};_.Zc=function $$(){return vRd};_=a_.prototype;_.Mc=function d_(){return tRd};_.Yc=function q_(){return uRd};_.Zc=function r_(){return vRd};_=Lrb.prototype=Frb.prototype=new Ar;_.gC=function Mrb(){return O9};_.Nd=function Qrb(){Krb()};_.cM={};_=c0b.prototype=a0b.prototype=new Ar;_.gC=function d0b(){return Keb};_.fc=function e0b(b){Y_b(this.b)};_.cM={26:1,47:1};_.b=null;_=h0b.prototype=f0b.prototype=new Ar;_.gC=function i0b(){return Leb};_.ic=function j0b(b){Y_b(this.b)};_.cM={32:1,47:1};_.b=null;_=m0b.prototype=k0b.prototype=new Ar;_.gC=function n0b(){return Meb};_.ic=function o0b(b){X_b(this.b)};_.cM={32:1,47:1};_.b=null;var O9=X3c(cBd,IRd),Keb=X3c(uDd,JRd),Leb=X3c(uDd,KRd),Meb=X3c(uDd,LRd);$entry(Nrb)();