function lEb(){}
function fEb(){}
function Ydc(){}
function dec(){}
function iMc(){}
function hMc(){}
function uec(){sec()}
function Vdc(b){zVb(b.c,Odc(b.b))}
function lMc(b,c,d){nMc(b,c,b.j.d);rMc(b,b.j.d-1,d)}
function h4c(b){this.b=new gtd;Q3c(this,new x4c(b))}
function $dc(b,c,d,e,f){this.c=b;this.e=c;this.b=d;this.d=e;this.f=f}
function Jdc(b,c,d){F4c(b,x8c(new y8c(c.e,c.c,c.d,c.f,c.b))+Jzd+d)}
function CMc(){CMc=Twd;BMc=Afb(dzb,{19:1,54:1},1,[W6d,X6d])}
function kEb(){var b;while(gEb){b=gEb;gEb=gEb.c;!gEb&&(hEb=null);Vdc(b.b)}}
function EMc(b){var c,d,e;c=ZG(b);e=c.children[1];d=e.children[1];return ZG(d)}
function rMc(b,c,d){var e,f;if(c>=b.j.d){return}f=eHc(b.b.children[c*2],0);e=ZG(f);EMc(e).innerHTML=d||izd}
function uMc(b,c){var d,e,f,g;for(g=c,d=b.j.d;g<d;++g){f=b.b.children[g*2];e=ZG(f);e[L6d]=g;c==0?jw(e,V6d,true):jw(e,V6d,false)}}
function tMc(b,c){if(c>=b.j.d||c<0||c==b.c){return}b.c>=0&&sMc(b,b.c,false);b.c=c;sMc(b,b.c,true)}
function Ldc(b){var c,d,e,f,g;g=new t6c;g.f[HLd]=4;for(d=DXb(b.b),e=0,f=d.length;e<f;++e){c=d[e];p6c(g,new yKc(c))}return g}
function EXb(b){var c,d;c=Pfb(b.b.Vc(u6d),54);if(c==null){d=Afb(dzb,{19:1,54:1},1,[v6d,w6d,x6d,y6d,z6d]);b.b.Xc(u6d,d);return d}else{return c}}
function DXb(b){var c,d;c=Pfb(b.b.Vc(p6d),54);if(c==null){d=Afb(dzb,{19:1,54:1},1,[gNd,q6d,r6d,s6d,r5d,t6d]);b.b.Xc(p6d,d);return d}else{return c}}
function CXb(b){var c,d;c=Pfb(b.b.Vc(g6d),54);if(c==null){d=Afb(dzb,{19:1,54:1},1,[h6d,i6d,j6d,k6d,l6d,m6d,n6d,o6d]);b.b.Xc(g6d,d);return d}else{return c}}
function BXb(b){var c,d;c=Pfb(b.b.Vc(Z5d),54);if(c==null){d=Afb(dzb,{19:1,54:1},1,[$5d,_5d,a6d,b6d,c6d,d6d,e6d,f6d]);b.b.Xc(Z5d,d);return d}else{return c}}
function nEb(){iEb=new lEb;ZC((WC(),VC),18);!!$stats&&$stats(QD(Y5d,szd,-1,-1));iEb.Hd();!!$stats&&$stats(QD(Y5d,zXd,-1,-1))}
function DMc(){var b,c,d;c=sH($doc,gLd);d=sH($doc,hLd);c.appendChild(d);c.style[mDd]=U_d;c[HLd]=0;c[ILd]=0;for(b=0;b<BMc.length;++b){d.appendChild(zNc(BMc[b]))}return c}
function mMc(b,c){var d,e;while(!!c&&c!=b.N){d=c[L6d]==null?null:String(c[L6d]);if(d!=null){e=parseInt(c[M6d])||0;return e==(b.$H||(b.$H=++VD))?cid(d):-1}c=aH(c)}return -1}
function pMc(b,c,d){var e,f,g;e=OIc(b,c);if(e){f=2*d;g=b.b.children[f];b.b.removeChild(g);g=b.b.children[f];b.b.removeChild(g);b.c==d?(b.c=-1):b.c>d&&--b.c;uMc(b,d)}return e}
function FMc(){var b;CMc();this.j=new B7c(this);b=sH($doc,gLd);this.N=b;this.b=sH($doc,hLd);b.appendChild(this.b);b[HLd]=0;b[ILd]=0;WGc();mHc(b,1);this.N[Wyd]=Y6d;kw(this.N,Z6d)}
function oMc(b,c){var d,e,f,g,i;I5c(b.N,izd,c);g=b.b.children.length>>1;for(f=0;f<g;++f){i=ZG(b.b.children[2*f]);e=ZG(i);d=ZG(b.b.children[2*f+1]);I5c(i,c,Q6d+f);I5c(d,c,R6d+f);I5c(b.rf(e),c,S6d+f)}}
function Ndc(b,c){var d,e,f;d=new hUc;d.f[HLd]=0;d.d=(STc(),QTc);bUc(d,new kDc(c));e=new zOc(b);e.N[Wyd]=A6d;f=cUc(d);d.c.appendChild(f);Bw(e);u7c(d.j,e);f.appendChild(e.N);Dw(e,d);return d.N.outerHTML}
function sMc(b,c,d){var e,f,g,i,j;g=b.b.children[c*2];if(!g){return}e=ZG(g);jw(e,T6d,d);j=b.b.children[c*2+1];j.style.display=d?izd:jEd;v7c(b.j,c).xb(d);i=b.b.children[(c+1)*2];if(i){f=ZG(i);jw(f,U6d,d)}}
function Odc(b){var c,d,e,f,g,i,j,k;e=new uec;g=new FMc;g.N.style[mDd]=B6d;f=Ndc(C6d,(sec(),lec));lMc(g,(j=new h4c(e),k=F4c(j.j,D6d),i=EXb(b.b),Jdc(k,kec,i[0]),Jdc(k,hec,i[1]),Jdc(k,nec,i[2]),Jdc(k,mec,i[3]),Jdc(k,oec,i[4]),Q4c(k,true,true),j),f);d=Ndc(E6d,jec);lMc(g,Ldc(b),d);c=Ndc(F6d,fec);lMc(g,Kdc(b),c);oMc(g,G6d);return g}
function Kdc(b){var c,d,e,f,g,i,j,k,n,o,p;k=new hUc;k.f[HLd]=5;bUc(k,new kDc((sec(),gec)));e=new xOc;p=cUc(k);k.c.appendChild(p);Bw(e);u7c(k.j,e);p.appendChild(e.N);Dw(e,k);j=new Nx(true,false);j.Nb(k);n=new t6c;n.f[HLd]=4;i=BXb(b.b);d=CXb(b.b);for(o=0;o<i.length;++o){g=i[o];c=d[o];f=new zJc(g);p6c(n,f);rw(f,new $dc(e,g,c,f,j),(KO(),KO(),JO))}return n}
function nMc(b,c,d){var e,f,g,i,j;j=sH($doc,DLd);g=sH($doc,ELd);j.appendChild(g);g.appendChild(DMc());i=sH($doc,DLd);f=sH($doc,ELd);i.appendChild(f);d=IIc(b,c,d);e=d*2;iHc(b.b,i,e);iHc(b.b,j,e);jw(g,N6d,true);g[M6d]=b.$H||(b.$H=++VD);g[nDd]=KXd;jw(f,O6d,true);f[nDd]=U_d;f[P6d]=lDd;MIc(b,c,f,d,false);uMc(b,d);if(b.c==-1){tMc(b,0)}else{sMc(b,d,false);b.c>=d&&++b.c;sMc(b,b.c,true)}}
function sec(){sec=Twd;eec=$moduleBase+J6d;iec=$moduleBase+K6d;fec=new MTb(eec,64,0,32,32);gec=new MTb(iec,0,0,32,32);hec=new MTb(eec,144,0,15,16);jec=new MTb(eec,32,0,32,32);kec=new MTb(eec,128,16,16,16);lec=new MTb(eec,0,0,32,32);mec=new MTb(eec,128,0,16,16);nec=new MTb(eec,112,16,16,16);oec=new MTb(eec,112,0,16,16);pec=new MTb(eec,96,16,16,16);qec=new MTb(eec,144,16,1,1);rec=new MTb(eec,96,0,16,16)}
var B6d='200px',J6d='55414EBEFCEF03959C9B6A2E58903034.cache.png',K6d='662D45A7A4C7FF83F80FDD5504D9CCE3.cache.jpg',I6d='<\/i>',H6d='<br><i>',e6d='Alan Turing',_5d='Albert Einstein',$6d='AsyncLoader18',$5d='Benoit Mandelbrot',b6d='Bob Saget',_6d='CwStackPanel$2',a7d='CwStackPanel_Images_en_StaticClientBundleGenerator',c7d='DecoratedStackPanel',w6d='Drafts',E6d='Filters',v6d='Inbox',f6d='John von Neumann',c6d='Ludwig von Beethoven',C6d='Mail',r6d='Read',a6d='Rene Descartes',d6d='Richard Feynman',y6d='Sent',t6d='Sent by me',b7d='StackPanel',q6d='Starred',x6d='Templates',z6d='Trash',s6d='Unread',L6d='__index',M6d='__owner',n6d='alan@example.com',i6d='albert@example.com',h6d='benoit@example.com',k6d='bob@example.com',A6d='cw-StackPanelHeader',G6d='cwStackPanel',Z5d='cwStackPanelContacts',g6d='cwStackPanelContactsEmails',p6d='cwStackPanelFilters',u6d='cwStackPanelMailFolders',D6d='foo@example.com',Z6d='gwt-DecoratedStackPanel',Y6d='gwt-StackPanel',O6d='gwt-StackPanelContent',N6d='gwt-StackPanelItem',U6d='gwt-StackPanelItem-below-selected',V6d='gwt-StackPanelItem-first',T6d='gwt-StackPanelItem-selected',o6d='john@example.com',l6d='ludwig@example.com',j6d='rene@example.com',m6d='richard@example.com',Y5d='runCallbacks18',X6d='stackItemMiddle',W6d='stackItemTop',Q6d='text-wrapper';_=lEb.prototype=fEb.prototype=new ss;_.gC=function mEb(){return Kkb};_.Hd=function qEb(){kEb()};_.cM={};_=$dc.prototype=Ydc.prototype=new ss;_.gC=function _dc(){return Spb};_.kc=function aec(b){var c,d;MOc(this.c.b,this.e+H6d+this.b+I6d,true);c=VH(this.d.N)+14;d=WH(this.d.N)+14;Cx(this.f,c,d);this.f.Qb()};_.cM={27:1,47:1};_.b=null;_.c=null;_.d=null;_.e=null;_.f=null;_=uec.prototype=dec.prototype=new ss;_.gC=function vec(){return Tpb};_.ae=function wec(){return pec};_._d=function xec(){return qec};_.be=function yec(){return rec};_.cM={};var eec,fec=null,gec=null,hec=null,iec,jec=null,kec=null,lec=null,mec=null,nec=null,oec=null,pec=null,qec=null,rec=null;_=iMc.prototype=new EIc;_.gC=function wMc(){return svb};_.rf=function xMc(b){return b};_.Eb=function yMc(b){var c,d;if(TGc(b.type)==1){d=b.srcElement;c=mMc(this,d);c!=-1&&tMc(this,c)}xw(this,b)};_.ub=function zMc(b){oMc(this,b)};_.Jb=function AMc(b){return pMc(this,b,w7c(this.j,b))};_.cM={14:1,15:1,17:1,18:1,74:1,76:1,129:1};_.b=null;_.c=-1;_=FMc.prototype=hMc.prototype=new iMc;_.gC=function GMc(){return Btb};_.rf=function HMc(b){return EMc(b)};_.cM={14:1,15:1,17:1,18:1,74:1,76:1,129:1};var BMc;_=h4c.prototype=G3c.prototype;var Kkb=Mhd(RPd,$6d),Spb=Mhd(GSd,_6d),Tpb=Mhd(GSd,a7d),svb=Mhd(zNd,b7d),Btb=Mhd(zNd,c7d);$entry(nEb)();