function UHb(){}
function OHb(){}
function DQc(){}
function _Qc(){}
function ZQc(){}
function bRc(){}
function iRc(){}
function gRc(){}
function TQc(b){if(b==HQc){return true}i_();return b==KQc}
function UQc(b){if(b==GQc){return true}i_();return b==FQc}
function eRc(b){this.c=(CTc(),xTc).b;this.e=(STc(),RTc).b;this.b=b}
function VQc(){LQc();nKc.call(this);this.c=(CTc(),xTc);this.d=(STc(),RTc);this.f[HLd]=0;this.f[ILd]=0}
function QQc(b,c){var d;d=Pfb(b.L,117);d.c=c.b;!!d.d&&(d.d[FLd]=c.b,undefined)}
function RQc(b,c){var d;d=Pfb(b.L,117);d.e=c.b;!!d.d&&(d.d.style[GLd]=c.b,undefined)}
function LQc(){LQc=Twd;EQc=new _Qc;HQc=new _Qc;GQc=new _Qc;FQc=new _Qc;IQc=new _Qc;JQc=new _Qc;KQc=new _Qc}
function WHb(){RHb=new UHb;ZC((WC(),VC),27);!!$stats&&$stats(QD(jce,szd,-1,-1));RHb.Hd();!!$stats&&$stats(QD(jce,zXd,-1,-1))}
function NQc(b,c,d){var e;if(d==EQc){if(c==b.b){return}else if(b.b){throw new mid(kce)}}Bw(c);u7c(b.j,c);d==EQc&&(b.b=c);e=new eRc(d);c.L=e;QQc(c,b.c);RQc(c,b.d);PQc(b);Dw(c,b)}
function OQc(b,c){var d,e,f,g,i,j,k,n;I5c(b.N,izd,c);j=new gtd;k=new K7c(b.j);while(k.b<k.c.d-1){d=I7c(k);i=Pfb(d.L,117).b;f=Pfb(j.Vc(i),10);e=!f?1:f.b;g=i==IQc?lce+e:i==JQc?mce+e:i==KQc?nce+e:i==FQc?oce+e:i==HQc?pce+e:i==GQc?qce+e:tLd;I5c((n=d.N.parentNode,(!n||n.nodeType!=1)&&(n=null),n),c,g);j.Xc(i,Mid(e+1))}}
function THb(){var b,c,d,e;while(PHb){b=PHb;PHb=PHb.c;!PHb&&(QHb=null);zVb(b.b.b,(d=new VQc,d.N[Wyd]=$be,d.f[HLd]=4,d.c=(CTc(),wTc),NQc(d,new zOc(_be),(LQc(),IQc)),NQc(d,new zOc(ace),JQc),NQc(d,new zOc(bce),FQc),NQc(d,new zOc(cce),KQc),NQc(d,new zOc(dce),IQc),NQc(d,new zOc(ece),JQc),c=new zOc(fce),e=new y0c(c),e.N.style[mDd]=gce,e.N.style[nDd]=hce,NQc(d,e,EQc),OQc(d,ice),d))}}
function PQc(b){var c,d,e,f,g,i,j,k,n,o,p,q,r,s,t,u;c=b.e;while(c.children.length>0){c.removeChild(c.children[0])}r=1;f=1;for(j=new K7c(b.j);j.b<j.c.d-1;){e=I7c(j);g=Pfb(e.L,117).b;g==IQc||g==JQc?++r:(g==FQc||g==KQc||g==HQc||g==GQc)&&++f}s=zfb(Wyb,{19:1},72,r,0);for(i=0;i<r;++i){s[i]=new iRc;s[i].c=sH($doc,DLd);c.appendChild(s[i].c)}n=0;o=f-1;p=0;t=r-1;d=null;for(j=new K7c(b.j);j.b<j.c.d-1;){e=I7c(j);k=Pfb(e.L,117);u=sH($doc,ELd);k.d=u;k.d[FLd]=k.c;k.d.style[GLd]=k.e;k.d[mDd]=izd;k.d[nDd]=izd;if(k.b==IQc){iHc(s[p].c,u,s[p].b);u.appendChild(e.N);u[O1d]=o-n+1;++p}else if(k.b==JQc){iHc(s[t].c,u,s[t].b);u.appendChild(e.N);u[O1d]=o-n+1;--t}else if(k.b==EQc){d=u}else if(TQc(k.b)){q=s[p];iHc(q.c,u,q.b++);u.appendChild(e.N);u[rce]=t-p+1;++n}else if(UQc(k.b)){q=s[p];iHc(q.c,u,q.b);u.appendChild(e.N);u[rce]=t-p+1;--o}}if(b.b){q=s[p];iHc(q.c,d,q.b);d.appendChild(b.b.N)}}
var hce='100px',sce='AsyncLoader27',vce='DockPanel',wce='DockPanel$DockLayoutConstant',xce='DockPanel$LayoutData',tce='DockPanel$TmpRow',uce='DockPanel$TmpRow;',kce='Only one CENTER widget may be added',fce="This is a <code>ScrollPanel<\/code> contained at the center of a <code>DockPanel<\/code>.  By putting some fairly large contents in the middle and setting its size explicitly, it becomes a scrollable area within the page, but without requiring the use of an IFRAME.<br><br>Here's quite a bit more meaningless text that will serve primarily to make this thing scroll off the bottom of its visible area.  Otherwise, you might have to make it really, really small in order to see the nifty scroll bars!",bce='This is the east component',_be='This is the first north component',ace='This is the first south component',dce='This is the second north component',ece='This is the second south component',cce='This is the west component',$be='cw-DockPanel',ice='cwDockPanel',oce='east',qce='lineend',pce='linestart',lce='north',jce='runCallbacks27',mce='south',nce='west';_=UHb.prototype=OHb.prototype=new ss;_.gC=function VHb(){return klb};_.Hd=function ZHb(){THb()};_.cM={};_=VQc.prototype=DQc.prototype=new hKc;_.gC=function WQc(){return Vtb};_.ub=function XQc(b){OQc(this,b)};_.Jb=function YQc(b){var c;c=OIc(this,b);if(c){b==this.b&&(this.b=null);PQc(this)}return c};_.cM={14:1,15:1,17:1,18:1,74:1,76:1,129:1};_.b=null;var EQc,FQc,GQc,HQc,IQc,JQc,KQc;_=_Qc.prototype=ZQc.prototype=new ss;_.gC=function aRc(){return Stb};_.cM={};_=eRc.prototype=bRc.prototype=new ss;_.gC=function fRc(){return Ttb};_.cM={117:1};_.b=null;_.d=null;_=iRc.prototype=gRc.prototype=new ss;_.gC=function jRc(){return Utb};_.cM={72:1};_.b=0;_.c=null;var klb=Mhd(RPd,sce),Utb=Mhd(zNd,tce),Wyb=Lhd(rVd,uce,Utb),Vtb=Mhd(zNd,vce),Stb=Mhd(zNd,wce),Ttb=Mhd(zNd,xce);$entry(WHb)();