function vqb(){}
function pqb(){}
function U$b(){}
function Z$b(){}
function c_b(){}
function e_b(b){this.b=b}
function W$b(b){this.b=b}
function _$b(b){this.b=b}
function k_b(b){HIb(b.c,N$b(b.b))}
function uqb(){var b;while(qqb){b=qqb;qqb=qqb.c;!qqb&&(rqb=null);k_b(b.b)}}
function O$b(b,c){if(c==null){rv(b.d.N,dRd,false)}else{dBc(b.d.b,c,false);rv(b.d.rb(),dRd,true)}}
function xqb(){sqb=new vqb;eC((bC(),aC),14);!!$stats&&$stats(XC(WRd,pld,-1,-1));sqb.Cd();!!$stats&&$stats(XC(WRd,aJd,-1,-1))}
function GKb(b){var c,d;c=v4(b.b.$c(XRd),54);if(c==null){d=g4(Rmb,{19:1,54:1},1,[YRd,ZRd,$Rd,_Rd,aSd]);b.b.ad(XRd,d);return d}else{return c}}
function P$b(c){var b,e,f,g;f=AF(c.g.N,FKd);if(w5c(f,fld)){dBc(c.d.b,eRd,false)}else{try{g=$3c(f);e=HY(c.b,g);dBc(c.d.b,e,false);O$b(c,null)}catch(b){b=cnb(b);if(z4(b,55)){O$b(c,fRd)}else throw b}}}
function Q$b(c){var b,e;switch(c.f.N.selectedIndex){case 0:c.b=(BY(),!wY&&(wY=new TY(zY.Jc(),HV((OU(),NU)),false)),BY(),wY);mLc(c.e,c.b.v);c.e.N[pKd]=!false;break;case 1:c.b=(BY(),!vY&&(vY=new TY(zY.Ic(),HV((OU(),NU)),false)),BY(),vY);mLc(c.e,c.b.v);c.e.N[pKd]=!false;break;case 2:c.b=(BY(),!yY&&(yY=new TY(zY.Vc(),HV((OU(),NU)),false)),BY(),yY);mLc(c.e,c.b.v);c.e.N[pKd]=!false;break;case 3:c.b=(BY(),!xY&&(xY=new TY(zY.Uc(),HV((OU(),NU)),false)),BY(),xY);mLc(c.e,c.b.v);c.e.N[pKd]=!false;break;case 4:c.e.N[pKd]=!true;e=AF(c.e.N,FKd);try{c.b=(BY(),new TY(e,HV((OU(),NU)),true))}catch(b){b=cnb(b);if(z4(b,98)){O$b(c,gRd);return}else throw b}}P$b(c)}
function N$b(b){var c,d,e,f,g,i,j,k,n,o,p;c=new YEc(4,2);c.p[Nxd]=5;b.f=new QIc;b.f.N.style[lpd]=_Pd;g=GKb(b.c);for(e=0,f=g.length;e<f;++e){d=g[e];LIc(b.f,d)}zv(b.f,new W$b(b),(fN(),fN(),eN));c.of(0,0);i=(j=c.k.b.j.rows[0].cells[0],VDc(c,j,false),j);i.innerHTML=_Qd;dEc(c,0,1,b.f);b.e=new zLc;b.e.N.style[lpd]=_Pd;zv(b.e,new _$b(b),(eP(),eP(),dP));dEc(c,1,1,b.e);b.g=new zLc;b.g.N.style[lpd]=_Pd;mLc(b.g,bSd);zv(b.g,new e_b(b),dP);c.of(2,0);k=(n=c.k.b.j.rows[2].cells[0],VDc(c,n,false),n);k.innerHTML=bRd;dEc(c,2,1,b.g);b.d=new JAc;b.d.N.style[lpd]=_Pd;c.of(3,0);o=(p=c.k.b.j.rows[3].cells[0],VDc(c,p,false),p);o.innerHTML=cRd;dEc(c,3,1,b.d);Q$b(b);return c}
var RRd='#,##0.00\xA0\xA4',URd='#,##0.00\xA0\xA4;(#,##0.00\xA0\xA4)',SRd='#,##0\xA0%',TRd='#E0',bSd='31415926535.897932',cSd='AsyncLoader14',dSd='CwNumberFormat$1',eSd='CwNumberFormat$2',fSd='CwNumberFormat$3',YRd='D\xE9cimales',XRd='cwNumberFormatPatterns',ZRd='devise',aSd='personnalis\xE9',_Rd='pourcentage',WRd='runCallbacks14',$Rd='scientifique',VRd='\xA4\xA0#,##0.00;\xA4-#,##0.00';var vY=null,xY=null,yY=null;_=iZ.prototype;_.Ic=function lZ(){return RRd};_.Uc=function yZ(){return SRd};_.Vc=function zZ(){return TRd};_=BZ.prototype;_.Ic=function EZ(){return RRd};_.Uc=function RZ(){return SRd};_.Vc=function SZ(){return TRd};_=UZ.prototype;_.Ic=function XZ(){return URd};_.Uc=function i$(){return SRd};_.Vc=function j$(){return TRd};_=l$.prototype;_.Ic=function o$(){return VRd};_.Uc=function B$(){return SRd};_.Vc=function C$(){return TRd};_=E$.prototype;_.Ic=function H$(){return RRd};_.Uc=function U$(){return SRd};_.Vc=function V$(){return TRd};_=X$.prototype;_.Ic=function $$(){return RRd};_.Uc=function l_(){return SRd};_.Vc=function m_(){return TRd};_=vqb.prototype=pqb.prototype=new Ar;_.gC=function wqb(){return r8};_.Cd=function Aqb(){uqb()};_.cM={};_=W$b.prototype=U$b.prototype=new Ar;_.gC=function X$b(){return odb};_.gc=function Y$b(b){Q$b(this.b)};_.cM={26:1,47:1};_.b=null;_=_$b.prototype=Z$b.prototype=new Ar;_.gC=function a_b(){return pdb};_.jc=function b_b(b){Q$b(this.b)};_.cM={32:1,47:1};_.b=null;_=e_b.prototype=c_b.prototype=new Ar;_.gC=function f_b(){return qdb};_.jc=function g_b(b){P$b(this.b)};_.cM={32:1,47:1};_.b=null;var r8=J3c(yBd,cSd),odb=J3c(RDd,dSd),pdb=J3c(RDd,eSd),qdb=J3c(RDd,fSd);$entry(xqb)();