function Gvb(){}
function Avb(){}
function ADc(){}
function rDc(){}
function pDc(){}
function tDc(){}
function yDc(){}
function VCc(){}
function jDc(b){if(b==ZCc){return true}nY();return b==aDc}
function kDc(b){if(b==YCc){return true}nY();return b==XCc}
function wDc(b){this.c=(UFc(),PFc).b;this.e=(iGc(),hGc).b;this.b=b}
function lDc(){bDc();Gwc.call(this);this.c=(UFc(),PFc);this.d=(iGc(),hGc);this.f[Nxd]=0;this.f[Oxd]=0}
function gDc(b,c){var d;d=v4(b.L,116);d.c=c.b;!!d.d&&(d.d[Lxd]=c.b,undefined)}
function hDc(b,c){var d;d=v4(b.L,116);d.e=c.b;!!d.d&&(d.d.style[Mxd]=c.b,undefined)}
function bDc(){bDc=Qid;WCc=new rDc;ZCc=new rDc;YCc=new rDc;XCc=new rDc;$Cc=new rDc;_Cc=new rDc;aDc=new rDc}
function Ivb(){Dvb=new Gvb;eC((bC(),aC),27);!!$stats&&$stats(XC(n$d,pld,-1,-1));Dvb.Cd();!!$stats&&$stats(XC(n$d,aJd,-1,-1))}
function dDc(b,c,d){var e;if(d==WCc){if(c==b.b){return}else if(b.b){throw new j4c(o$d)}}Jv(c);IVc(b.j,c);d==WCc&&(b.b=c);e=new wDc(d);c.L=e;gDc(c,b.c);hDc(c,b.d);fDc(b);Lv(c,b)}
function eDc(b,c){var d,e,f,g,i,j,k,n;XTc(b.N,fld,c);j=new dfd;k=new YVc(b.j);while(k.b<k.c.d-1){d=WVc(k);i=v4(d.L,116).b;f=v4(j.$c(i),10);e=!f?1:f.b;g=i==$Cc?p$d+e:i==_Cc?q$d+e:i==aDc?r$d+e:i==XCc?s$d+e:i==ZCc?t$d+e:i==YCc?u$d+e:sxd;XTc((n=d.N.parentNode,(!n||n.nodeType!=1)&&(n=null),n),c,g);j.ad(i,J4c(e+1))}}
function Fvb(){var b,c,d,e;while(Bvb){b=Bvb;Bvb=Bvb.c;!Bvb&&(Cvb=null);HIb(b.b.b,(d=new lDc,d.N[Tkd]=c$d,d.f[Nxd]=4,d.c=(UFc(),OFc),dDc(d,new SAc(d$d),(bDc(),$Cc)),dDc(d,new SAc(e$d),_Cc),dDc(d,new SAc(f$d),XCc),dDc(d,new SAc(g$d),aDc),dDc(d,new SAc(h$d),$Cc),dDc(d,new SAc(i$d),_Cc),c=new SAc(j$d),e=new OOc(c),e.N.style[lpd]=k$d,e.N.style[mpd]=l$d,dDc(d,e,WCc),eDc(d,m$d),d))}}
function fDc(b){var c,d,e,f,g,i,j,k,n,o,p,q,r,s,t,u;c=b.e;while(c.children.length>0){c.removeChild(c.children[0])}r=1;f=1;for(j=new YVc(b.j);j.b<j.c.d-1;){e=WVc(j);g=v4(e.L,116).b;g==$Cc||g==_Cc?++r:(g==XCc||g==aDc||g==ZCc||g==YCc)&&++f}s=f4(Imb,{19:1},71,r,0);for(i=0;i<r;++i){s[i]=new ADc;s[i].c=yG($doc,Jxd);c.appendChild(s[i].c)}n=0;o=f-1;p=0;t=r-1;d=null;for(j=new YVc(b.j);j.b<j.c.d-1;){e=WVc(j);k=v4(e.L,116);u=yG($doc,Kxd);k.d=u;k.d[Lxd]=k.c;k.d.style[Mxd]=k.e;k.d[lpd]=fld;k.d[mpd]=fld;if(k.b==$Cc){Stc(s[p].c,u,s[p].b);u.appendChild(e.N);u[BPd]=o-n+1;++p}else if(k.b==_Cc){Stc(s[t].c,u,s[t].b);u.appendChild(e.N);u[BPd]=o-n+1;--t}else if(k.b==WCc){d=u}else if(jDc(k.b)){q=s[p];Stc(q.c,u,q.b++);u.appendChild(e.N);u[v$d]=t-p+1;++n}else if(kDc(k.b)){q=s[p];Stc(q.c,u,q.b);u.appendChild(e.N);u[v$d]=t-p+1;--o}}if(b.b){q=s[p];Stc(q.c,d,q.b);d.appendChild(b.b.N)}}
var l$d='100px',w$d='AsyncLoader27',f$d='Ceci est le composant est',g$d='Ceci est le composant ouest',d$d='Ceci est le premier composant nord',e$d='Ceci est le premier composant sud',h$d='Ceci est le second composant nord',i$d='Ceci est le second composant sud',z$d='DockPanel',A$d='DockPanel$DockLayoutConstant',B$d='DockPanel$LayoutData',x$d='DockPanel$TmpRow',y$d='DockPanel$TmpRow;',o$d='Only one CENTER widget may be added',j$d="Voici un <code>panneau de d\xE9filement<\/code> situ\xE9 au centre d'un <code>panneau d'ancrage<\/code>. Si des contenus relativement volumineux sont ins\xE9r\xE9s au milieu de ce panneau \xE0 d\xE9filement et si sa taille est d\xE9finie, il prend la forme d'une zone dot\xE9e d'une fonction de d\xE9filement \xE0 l'int\xE9rieur de la page, sans l'utilisation d'un IFRAME.<br><br>Voici un texte encore plus obscur qui va surtout servir \xE0 faire d\xE9filer cet \xE9l\xE9ment jusqu'en bas de sa zone visible. Sinon, il vous faudra r\xE9duire ce panneau \xE0 une taille minuscule pour pouvoir afficher ces formidables barres de d\xE9filement!",c$d='cw-DockPanel',m$d='cwDockPanel',s$d='east',u$d='lineend',t$d='linestart',p$d='north',n$d='runCallbacks27',q$d='south',r$d='west';_=Gvb.prototype=Avb.prototype=new Ar;_.gC=function Hvb(){return d9};_.Cd=function Lvb(){Fvb()};_.cM={};_=lDc.prototype=VCc.prototype=new Awc;_.gC=function mDc(){return Khb};_.sb=function nDc(b){eDc(this,b)};_.Hb=function oDc(b){var c;c=fvc(this,b);if(c){b==this.b&&(this.b=null);fDc(this)}return c};_.cM={14:1,15:1,17:1,18:1,73:1,75:1,128:1};_.b=null;var WCc,XCc,YCc,ZCc,$Cc,_Cc,aDc;_=rDc.prototype=pDc.prototype=new Ar;_.gC=function sDc(){return Hhb};_.cM={};_=wDc.prototype=tDc.prototype=new Ar;_.gC=function xDc(){return Ihb};_.cM={116:1};_.b=null;_.d=null;_=ADc.prototype=yDc.prototype=new Ar;_.gC=function BDc(){return Jhb};_.cM={71:1};_.b=0;_.c=null;var d9=J3c(yBd,w$d),Jhb=J3c(gzd,x$d),Imb=I3c(SGd,y$d,Jhb),Khb=J3c(gzd,z$d),Hhb=J3c(gzd,A$d),Ihb=J3c(gzd,B$d);$entry(Ivb)();