function qrb(){}
function krb(){}
function kzc(){}
function bzc(){}
function dzc(){}
function izc(){}
function Fyc(){}
function _yc(){}
function Vyc(b){if(b==Jyc){return true}bX();return b==Myc}
function Wyc(b){if(b==Iyc){return true}bX();return b==Hyc}
function gzc(b){this.c=(EBc(),zBc).b;this.e=(UBc(),TBc).b;this.b=b}
function Xyc(){Nyc();qsc.call(this);this.c=(EBc(),zBc);this.d=(UBc(),TBc);this.f[vtd]=0;this.f[wtd]=0}
function Syc(b,c){var d;d=y0(b.L,116);d.c=c.b;!!d.d&&(d.d[ttd]=c.b,undefined)}
function Tyc(b,c){var d;d=y0(b.L,116);d.e=c.b;!!d.d&&(d.d.style[utd]=c.b,undefined)}
function Nyc(){Nyc=Aed;Gyc=new bzc;Jyc=new bzc;Iyc=new bzc;Hyc=new bzc;Kyc=new bzc;Lyc=new bzc;Myc=new bzc}
function srb(){nrb=new qrb;OB((LB(),KB),27);!!$stats&&$stats(FC(OVd,_gd,-1,-1));nrb.ld();!!$stats&&$stats(FC(OVd,KEd,-1,-1))}
function Pyc(b,c,d){var e;if(d==Gyc){if(c==b.b){return}else if(b.b){throw new V_c(PVd)}}rv(c);sRc(b.j,c);d==Gyc&&(b.b=c);e=new gzc(d);c.L=e;Syc(c,b.c);Tyc(c,b.d);Ryc(b);tv(c,b)}
function Qyc(b,c){var d,e,f,g,i,j,k,n;HPc(b.N,Rgd,c);j=new Pad;k=new IRc(b.j);while(k.b<k.c.d-1){d=GRc(k);i=y0(d.L,116).b;f=y0(j.Qc(i),10);e=!f?1:f.b;g=i==Kyc?QVd+e:i==Lyc?RVd+e:i==Myc?SVd+e:i==Hyc?TVd+e:i==Jyc?UVd+e:i==Iyc?VVd+e:atd;HPc((n=d.N.parentNode,(!n||n.nodeType!=1)&&(n=null),n),c,g);j.Sc(i,t0c(e+1))}}
function prb(){var b,c,d,e;while(lrb){b=lrb;lrb=lrb.c;!lrb&&(mrb=null);rEb(b.b.b,(d=new Xyc,d.N[Dgd]=DVd,d.f[vtd]=4,d.c=(EBc(),yBc),Pyc(d,new Cwc(EVd),(Nyc(),Kyc)),Pyc(d,new Cwc(FVd),Lyc),Pyc(d,new Cwc(GVd),Hyc),Pyc(d,new Cwc(HVd),Myc),Pyc(d,new Cwc(IVd),Kyc),Pyc(d,new Cwc(JVd),Lyc),c=new Cwc(KVd),e=new yKc(c),e.N.style[Vkd]=LVd,e.N.style[Wkd]=MVd,Pyc(d,e,Gyc),Qyc(d,NVd),d))}}
function Ryc(b){var c,d,e,f,g,i,j,k,n,o,p,q,r,s,t,u;c=b.e;while(c.children.length>0){c.removeChild(c.children[0])}r=1;f=1;for(j=new IRc(b.j);j.b<j.c.d-1;){e=GRc(j);g=y0(e.L,116).b;g==Kyc||g==Lyc?++r:(g==Hyc||g==Myc||g==Jyc||g==Iyc)&&++f}s=i0(sib,{19:1},81,r,0);for(i=0;i<r;++i){s[i]=new kzc;s[i].c=gG($doc,rtd);c.appendChild(s[i].c)}n=0;o=f-1;p=0;t=r-1;d=null;for(j=new IRc(b.j);j.b<j.c.d-1;){e=GRc(j);k=y0(e.L,116);u=gG($doc,std);k.d=u;k.d[ttd]=k.c;k.d.style[utd]=k.e;k.d[Vkd]=Rgd;k.d[Wkd]=Rgd;if(k.b==Kyc){Cpc(s[p].c,u,s[p].b);u.appendChild(e.N);u[lLd]=o-n+1;++p}else if(k.b==Lyc){Cpc(s[t].c,u,s[t].b);u.appendChild(e.N);u[lLd]=o-n+1;--t}else if(k.b==Gyc){d=u}else if(Vyc(k.b)){q=s[p];Cpc(q.c,u,q.b++);u.appendChild(e.N);u[WVd]=t-p+1;++n}else if(Wyc(k.b)){q=s[p];Cpc(q.c,u,q.b);u.appendChild(e.N);u[WVd]=t-p+1;--o}}if(b.b){q=s[p];Cpc(q.c,d,q.b);d.appendChild(b.b.N)}}
var MVd='100px',XVd='AsyncLoader27',$Vd='DockPanel',_Vd='DockPanel$DockLayoutConstant',aWd='DockPanel$LayoutData',YVd='DockPanel$TmpRow',ZVd='DockPanel$TmpRow;',PVd='Only one CENTER widget may be added',KVd="This is a <code>ScrollPanel<\/code> contained at the center of a <code>DockPanel<\/code>.  By putting some fairly large contents in the middle and setting its size explicitly, it becomes a scrollable area within the page, but without requiring the use of an IFRAME.<br><br>Here's quite a bit more meaningless text that will serve primarily to make this thing scroll off the bottom of its visible area.  Otherwise, you might have to make it really, really small in order to see the nifty scroll bars!",GVd='This is the east component',EVd='This is the first north component',FVd='This is the first south component',IVd='This is the second north component',JVd='This is the second south component',HVd='This is the west component',DVd='cw-DockPanel',NVd='cwDockPanel',TVd='east',VVd='lineend',UVd='linestart',QVd='north',OVd='runCallbacks27',RVd='south',SVd='west';_=qrb.prototype=krb.prototype=new ir;_.gC=function rrb(){return P4};_.ld=function vrb(){prb()};_.cM={};_=Xyc.prototype=Fyc.prototype=new ksc;_.gC=function Yyc(){return udb};_.sb=function Zyc(b){Qyc(this,b)};_.Hb=function $yc(b){var c;c=Rqc(this,b);if(c){b==this.b&&(this.b=null);Ryc(this)}return c};_.cM={14:1,15:1,17:1,18:1,83:1,85:1,128:1};_.b=null;var Gyc,Hyc,Iyc,Jyc,Kyc,Lyc,Myc;_=bzc.prototype=_yc.prototype=new ir;_.gC=function czc(){return rdb};_.cM={};_=gzc.prototype=dzc.prototype=new ir;_.gC=function hzc(){return sdb};_.cM={116:1};_.b=null;_.d=null;_=kzc.prototype=izc.prototype=new ir;_.gC=function lzc(){return tdb};_.cM={81:1};_.b=0;_.c=null;var P4=t_c(gxd,XVd),tdb=t_c(Qud,YVd),sib=s_c(ACd,ZVd,tdb),udb=t_c(Qud,$Vd),rdb=t_c(Qud,_Vd),sdb=t_c(Qud,aWd);$entry(srb)();